### ISSUE TITLE
Having this sensor for 2 addresses is not working.

### ISSUE THREAD

**Issue by tonsmets** [xirixiz/homeassistant-afvalwijzer#101]
Hi,

I tried filling the config for 2 addresses like this:
```
  - platform: afvalwijzer
    provider: mijnafvalwijzer
    postal_code: 1234AB
    street_number:  1
    include_date_today: false
    default_label: Geen
  - platform: afvalwijzer
    provider: mijnafvalwijzer
    postal_code: 2345BC 
    street_number:  1
    include_date_today: false
    default_label: Geen
```

But I only get 1 set of entities. Is there an option to track 2 addresses?

**Comment by xirixiz** [comment]
Good question, I`m not sure, but I don't think it's possible as the sensors would end up overwriting eachother. However, it could be a nice addition/feature and easy to implement I guess...

**Comment by tonsmets** [comment]
I tried to fix it by changing the way the entities are named (https://github.com/tonsmets/homeassistant-afvalwijzer/commit/61d2e694dfd8a95a37f9939b7520caa8171e3c4e). Unfortunately it still only works for 1 configuration entry. I'm not very familiar with the HA custom component code. What has to be changed or added to make this work? I'm willing to do this myself and contribute back to the project.

**Comment by xirixiz** [comment]
Hi Ton, nice to see you'd like to contribute,very much appreciated! Did you fork the repo and test your code from there?
If so, please provide me the link to your code so I can help you out. Anyway, good job your willing to solve this yourself!

**Comment by tonsmets** [comment]
I did! I mentioned the repository and corresponding commit in my comment. Check it out here: https://github.com/tonsmets/homeassistant-afvalwijzer/commit/61d2e694dfd8a95a37f9939b7520caa8171e3c4e

I can see the new naming of the entities but it still only shows 1 address so one set of entities.

**Comment by xirixiz** [comment]
I`ll try to implement this next week. If it's too much work, then I won't add this feature request as nobody has requested this before.

**Comment by xirixiz** [comment]
Done! Added in release 5.0.6!
