### ISSUE TITLE
Added Rova as provider

### ISSUE THREAD

**Issue by ronaldvandervegt** [xirixiz/homeassistant-afvalwijzer#102]
I manually added Rova as provider, and it's working fine. The current code won't allow Rova, as Rova uses a subdomain: inzamelkalender.rova.nl , instead of www.rova.nl. However, from that point off the url is the same way as the other providers.

This is the first time im trying to contribute to any home assistant integrtation on Github, and I'm afraid that I'm not experienced enough to change this throught the entire code. But I manually got Rova as provider working this way:

1. /config/custom_components/afvalwijzer/provider/mijnafvalwijzer.py , line 30:
        _providers = ("mijnafvalwijzer", "afvalstoffendienstkalender", "rova")
2. /config/custom_compontents/afvalwijzer/const/const.py , line 5:
    "mijnafvalwijzer_scraper": ["https://inzamelkalender.{0}.nl/nl/{1}/{2}/{3}/"],

And offcourse in sensors.yaml or wherever you have your sensors set provider to 'rova'

**Comment by xirixiz** [comment]
Good job! I`ll add Rova via a pull request, so you can see what has been modified!

This is because the documenation also has to be modified ofcourse. I`ll inform you once the PR has been created.

**Comment by xirixiz** [comment]
Added: https://github.com/xirixiz/homeassistant-afvalwijzer/pull/104

**Comment by xirixiz** [comment]
Just to inform, Rova has been added again in release 5.3.0
