### ISSUE TITLE
platform: time_pattern minutes: '/60' not supported anymore

### ISSUE THREAD

**Issue by yfands** [xirixiz/homeassistant-afvalwijzer#103]
Hey new user here, fresh install of home assistant and HACS, my new version doesnt support the '/60' anymore 

in automation
 - alias: Waste has not been moved
    trigger:
      platform: time_pattern
     minutes: '/60'
      seconds: 00

changed it into 
      hours: /1
      minutes: 00

no errors so far, 
struggling further how to get your card up and running in lovelace, a more beginners guide would be welcome.

Regards Frank.

**Comment by xirixiz** [comment]
Fixed! I had to modify it myself as well a while ago indeed.

You could also have created a pull request ;).

As for the description of implementing this component with lovelace, my opinion is that this is very well documented by HASS itself. It wouldn't make sense to add it here again, so therefor I just included an example. Ofcourse, everyone is free to contribute and add instructions to the component.
