### ISSUE TITLE
Jammer

### ISSUE THREAD

**Issue by JeroenSchwab** [xirixiz/homeassistant-afvalwijzer#109]
Erg jammer dat jullie niet veredr willen helpen.
Als het dus niet standaard is dan sluiten we de boel maar.
Een fijne dag nog

**Comment by xirixiz** [comment]
Het zit hem in de toon. Je zegt steeds dat het niet aan jouw kant ligt, dat je alles goed doet, en het uiteindelijk nog omdraait dat wat ik of @Mariusthvdb zegt niet klopt/deugt wanneer het niet werkt, daarnaast zonder gedegen tekst en uitleg wat je nou precies gedaan hebt. Voor jouw gevoel doe jij niets fout en doen wij dat wel, dat blijkt ook wel weer uit deze reactie. Het geeft mij geen voldoening daar mijn vrije tijd in te steken.

Hulp wordt er al jaren zonder problemen geboden en dit is de eerste keer dat ik het meemaak dat het op deze manier gaat. Wij zijn er niet om jouw Home Assistant op te zetten maar slechts om te helpen dit custom_component aan de praat te krijgen voor iedereen die daar behoefte aan heeft. Een bepaalde basiskennis of mate van zelfstudie van Home Assistant mag verwacht worden.

Wij willen jou en anderen met alle plezier helpen maar wel op een respectvolle manier.

Wellicht heb je hier iets aan als startpunt: 
https://community.home-assistant.io/
https://www.home-assistant.io/docs/
https://www.home-assistant.io/lovelace/

**Comment by JeroenSchwab** [comment]
@xirixiz  @Mariusthvdb Ik ben naar mijn mening niet begonnen met de toon veranderen.

Verder heb ik naar mijn mening niet gezegt dat ik niets fout doe dat is dan verkeerd begrepen. Ik ben de laatste persoon die zou zeggen dat ik het niet fout doe. Daarom vraag ik om hulp. Omdat ik er zelf niet uit kom. Ik heb nooit gezegt dat wat jullie aangeven niet klopt ik ga er van uit dat jullie de gene zijn die weten hoe het werkt. Ik heb alleen aangegeven dat het bij mij niet werkt met jullie code.  
Ik ben het met je eens dat er verwacht mag worden dat er enige basiskennis over het systeem is. Ik dacht dat ik deze kennis had. Ik heb echter de uitleg in de README verkeerd begrepen/gelezen. Waardoor ik de code op de verkeerde plek in het systeem heb gezet. Mocht ik mensen hebben gekwetst dan bied ik mijn excusses hiervoor aan.

**Comment by xirixiz** [comment]
Het is je vergeven 😄. Het hoeft ook geen oorlog te worden....

Kijk even hoe ver je komt en stel gerust een vraag, niemand is beroerd je daarbij te helpen. Zorg voor een heldere uitleg en waar je wat hebt aangepast, het liefst aangevuld met logfiles.

Nou ja, het komt vast goed. Uiteindelijk zal je van je HASS config genieten!
