### ISSUE TITLE
Papier sensor functioneert niet

### ISSUE THREAD

**Issue by euroman2007** [xirixiz/homeassistant-afvalwijzer#110]
Hallo, ik ben na een paar weken mijn HA volledig opnieuw aan het configureren. Nu heb ik bij Afvalwijzer het probleem dat van alle sensoren alleen mijn sensor_afvalwijzer_papier.  niet functioneert.
Meer mensen hier problemen mee ?

**Comment by xirixiz** [comment]
Hey, ik heb verder geen meldingen gehad dat er data voor sensors ontbreekt. Kan je jouw postcode en een willekeurig huisnummer delen (mag ook via PB in de home assistant community). Dan test ik het even voor je.

**Comment by euroman2007** [comment]
Hey, dankjewel voor jouw reactie.
ik heb het heel basic gehouden en alleen het standard gebruikt in mijn config.
de intergratie heb ik eerst gedaan via HACS.
daarna heb ik dit in mijn config gezet.

sensor:
  - platform: afvalwijzer
    provider: mijnafvalwijzer 
    postal_code: 6691XX
    street_number: 22

Groetjes Fernando

**Comment by xirixiz** [comment]
Gevonden! Dit jaar komt er volgens de kalender geen ophaalmoment meer voor oud papier, vandaar er "Geen" datum bekend is. De sensor wordt wel aangemaakt omdat het afgelopen jaar wel is voorgekomen dat papier is opgehaald. De functionaliteit van het component werkt dus naar behoren :)

15 oktober was het laatste ophaalmoment:
https://www.mijnafvalwijzer.nl/nl/6691XX/22/

**Comment by euroman2007** [comment]
AHAAA! Duidelijk :D 
Dankjewel voor de ondersteuning en jouw tijd.
Groetjes Fernando
