### ISSUE TITLE
Integratie werkt niet

### ISSUE THREAD

**Issue by rikmaris** [xirixiz/homeassistant-afvalwijzer#111]
Hi,

Ik heb de integratie al langer geleden gebruikt, maar de huidige versie krijg ik niet aan de praat. 

Wat heb ik gedaan:
alle nieuwe bestanden in de map custom components gezet met als naam afvalwijzer zie:
![image](https://user-images.githubusercontent.com/38853245/97425193-0e99d380-1912-11eb-92c8-c827dd871a72.png)

En in mijn configuration.yaml heb ik het zo staan:
![image](https://user-images.githubusercontent.com/38853245/97425599-a0094580-1912-11eb-93f4-8e796cf7862b.png)

Nu wil het maar niet werken. Ik krijg deze foutmelding:
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:365
Integration: Hass.io (documentation, issues)
First occurred: 11:28:07 (1 occurrences)
Last logged: 11:28:07

Invalid config for [sensor.afvalwijzer]: [provider] is an invalid option for [sensor.afvalwijzer]. Check: sensor.afvalwijzer->provider. (See ?, line ?).

Meerdere herstarts gedaan, maar ben een beetje lost met welke richting ik op moet zoeken.

**Comment by xirixiz** [comment]
Ik check het vanavond even 👍

**Comment by rikmaris** [comment]
Het is opgelost door een herstart van NUC. De docker alleen was niet voldoende. Heel raar, maar het werkt nu wel.

**Comment by xirixiz** [comment]
Ehr, dat is idd heel bijzonder, maar mooi dat het is opgelost 👍 . Denk iets van caching...
