### ISSUE TITLE
next pickups are for each trash-type, not the true next pickups 

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#114]
Now we have todays pickup excluded for the next pickups (yeah!), there's one 'issue' left: Next pickups show a pickup for each trashtype, and this isn't necessarily the list of next pickups, possibly skipping a pickup and doubling another. Because they have alternate schemes, or simply because you scare 1 date for each? 
Have a look:

currently the next pickups are listed for 4, 10, 11 nov en dec 1
<img width="595" alt="Schermafbeelding 2020-11-03 om 17 37 52" src="https://user-images.githubusercontent.com/33354141/98014280-b8d69700-1dfb-11eb-9f61-e93e9ead74c7.png">

while in fact they are 4, 10, 11 ands 18 nov:

![20201103_073703000_iOS](https://user-images.githubusercontent.com/33354141/98014388-ddcb0a00-1dfb-11eb-951b-5de53b796235.jpg)

though I appreciate the view per type (good to see Restafval is still a long time away, so be sure not to skip it...) I feel having the true next 4 dates (or more) available is important.

Please have a look if this data is available in the scraper, and if you could return that in the integrations sensors?

thanks!

**Comment by xirixiz** [comment]
That's not possible as there may only be a single gft sensor. Besides that, for me personal, also the current setup is the most obvious, for each waste type the first pickup date.
