### ISSUE TITLE
next sensors show incorrect date

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#115]
All _next_ sensors showing an incorrect trash pickup moment:

<img width="523" alt="Schermafbeelding 2020-11-04 om 10 25 46" src="https://user-images.githubusercontent.com/33354141/98093371-2203ec00-1e88-11eb-9b44-b1a9401d9bff.png">

while at the same time gft, paper and plastic show correct dates:

<img width="531" alt="Schermafbeelding 2020-11-04 om 10 26 35" src="https://user-images.githubusercontent.com/33354141/98093488-4d86d680-1e88-11eb-9609-85fa5dabd92a.png">

**Comment by xirixiz** [comment]
Ik heb wel een vermoeden waar dat in de code zit. Ik geloof dat je mij al een keer jouw postcode en huisnummer gedeeld hebt, maar zou je dat nog eens willen delen? Op die manier kan ik het nabootsen en oplossen. Thanks!

...kan via een pm in de hass community uiteraard.

**Comment by Mariusthvdb** [comment]
gedaan ;-)

**Comment by Mariusthvdb** [comment]
yup. 5.1.2 fixed this, thanks for the quick response!

before:

<img width="502" alt="Schermafbeelding 2020-11-04 om 11 15 11" src="https://user-images.githubusercontent.com/33354141/98099576-07ce0c00-1e90-11eb-8a19-c2b6586596af.png">

after:

<img width="488" alt="Schermafbeelding 2020-11-04 om 11 22 15" src="https://user-images.githubusercontent.com/33354141/98099599-0ef51a00-1e90-11eb-8aa4-d6433cf7e494.png">

**Comment by xirixiz** [comment]
Yes, date calculatie prombleempje :)
