### ISSUE TITLE
Support more services...

### ISSUE THREAD

**Issue by iAmRenzo** [xirixiz/homeassistant-afvalwijzer#117]
I saw in the Homey app for the same purpose these services:
- Afvalwijzer Suez
- Afvalkalender ACV
- Afvalkalender Circulus-Berkel
- Afvalkalender Meerlanden
- Afvalkalender Venray
- Avalex
- Cure
- Cyclus
- Dar Afvalkalender
- De Afval App
- Den Bosch
- GAD Gooi en Vechtstreek
- Gemeente Hellendoorn
- Inzamelkalender HVC
- Mijn Afvalwijzer
- Mijn Blink
- RD4
- Recyle Manager
- RMN
- Rova
- Twentemilieu

Would be great to add them.

**Comment by xirixiz** [comment]
That's true indeed. However, this project started once when I needed mijnafvalwijzer in HASS. As I put it on GitHub, the interest in this component increased. That's nice, but my intention is not to add any more providers. There are already components like Afvalinfo (https://github.com/heyajohnny/afvalinfo) that support all those providers. The key differences are the meganism to collect data differs (you need to specify the trash types you'd like to see in hass), and it provides less sensors (no upcoming trash,  no upcoming trash date, and some more...).

Thanks for your input, I think it's always valuable to share your thoughts!

**Comment by xirixiz** [comment]
Currently there are 3 providers supported. 3 because they share the same backend/layout, so therefor they we're easy to implement :).

**Comment by bafplus** [comment]
Just a thaught here since i realy like you're way of displaying that while https://github.com/heyajohnny/afvalinfo onloy shows text based layouts/info.
As far as i can see/judge he has build 1 api that provides all data (+90% of NL).
Why not combine the 2? 
Youre plugin for the great look and feel and his api for the data?
