### ISSUE TITLE
accidentally updated it to version 5.2.0 (No ROVA??)

### ISSUE THREAD

**Issue by jeanbart82** [xirixiz/homeassistant-afvalwijzer#120]
accidentally update to version 5.2.0

How do I get back? to the previous version? What was going on with ROVA? :-(

**Comment by jeanbart82** [comment]
OK. just found out i could just copy the files with samba to the custom_component folder... from the older version... https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/5.1.3

But you say to many differences? Can anyone help to fix?

**Comment by xirixiz** [comment]
https://github.com/xirixiz/homeassistant-afvalwijzer/releases

Sorry, it's not possible to solve things properly now, it's a complete different way of retrieving data now. 
Due too lack of time I don't want to extend the code to be compatible with "all" providers.

There are other projects where Rova is supported, perhaps that will solve things for you:
- https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer
- https://github.com/heyajohnny/afvalinfo

**Comment by xirixiz** [comment]
Just to inform, Rova has been added again in release 5.3.0

**Comment by jeanbart82** [comment]
Nice. I have some automations still depending on it. Just left it on 5.2.0

thanks!

**Comment by xirixiz** [comment]
Great! Rova now has a simmilar api as mijnafvalwijzer, so it was easy to implement again!
