### ISSUE TITLE
Installatie hulp nodig

### ISSUE THREAD

**Issue by MichNLGithub** [xirixiz/homeassistant-afvalwijzer#129]
Beste,
Ik heb via HACS de plugin geïnstalleerd maar geen idee hoe nu verder te installeren.
Ik heb de wiki gelezen maar blijkbaar ben ik een leek : )

**Comment by xirixiz** [comment]
Belangrijkste is om de werking van HASS onder de knie te krijgen. Wanneer er geen errors in de logs staan wat betreft dit component, dan kan je het volgende doen.

Wanneer je naar developer tools gaat in de UI (hamertje links), dan zie je bovenaan het tabje states. Wanneer je vervolgens zoekt op sensor.afvalwijzer, dan moet je een aantal sensoren zien voor ieder afval item dat voor jouw adres van toepassing is. Wanneer je dat ziet kan je die sensoren intergreren/visueel maken op je HASS dashboard. Maar check voor nu eerst maar eens of de sensoren er uberhaupt zijn :).

Heb je de README gevolgd? https://github.com/xirixiz/homeassistant-afvalwijzer

Je kan het ook veel hulp/info vinden op de HASS community: https://community.home-assistant.io/t/garbage-pickup-date-mijnafvalwijzer-nl-custom-component/34631

**Comment by MichNLGithub** [comment]
Mogge Bram,

Bedankt voor je hulp, klopt ik kan de sensors vinden onder het tabblad States, ik zie de sensoren ook als ronde kleine bolletjes bovenin op de overzichtspagina.
Enkel krijg ik dit niet in een apart veld (zoals het plaatje op je Wiki als een mooi overzicht).

Ik weet niet waar ik de volgende tekst dien te plaatsen:

INPUT BOOLEAN (FOR AUTOMATION)
input_boolean:
  waste_moved:
    name: Waste has been moved
    initial: 'off'
    icon: mdi:delete-empty
  waste_reminder:
    name: Waste reminder enabled
    initial: 'on'
AUTOMATION
automation:
  - alias: Reset waste notification
    trigger:
      platform: state
      entity_id: input_boolean.waste_moved
      to: 'on'
      for:
        hours: 12
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.waste_moved
      - service: input_boolean.turn_on
        entity_id: input_boolean.waste_reminder

  - alias: Mark waste as moved from notification
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: MARK_WASTE_MOVED
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.waste_moved

  - alias: Waste has not been moved
    trigger:
      platform: time_pattern
      hours: "/1"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.waste_moved
          state: 'off'
        - condition: state
          entity_id: input_boolean.waste_reminder
          state: 'on'
        - condition: time
          after: '18:00:00'
          before: '23:00:00'
        - condition: template
          value_template: "{{ states('sensor.afvalwijzer_tomorrow') != 'Geen' }}"
    action:
      - service: notify.family
        data:
          title: "Afval"
          message: 'Het is vandaag - {{ now().strftime("%d-%m-%Y") }}. Afvaltype(n): {{ states.sensor.afvalwijzer_tomorrow.state }} wordt opgehaald op: {{ (as_timestamp(now()) + (24*3600)) | timestamp_custom("%d-%m-%Y", True) }}!'
          data:
            push:
              badge: 0
              category: 'afval'

Ik heb de mini graph card geïnstalleerd.
Met vriendelijke groet,
Michael

**Comment by xirixiz** [comment]
Hoi Michael, wanneer je code plaatst, dan kan je dat beter tussen quotes zetten. Gerbuik drie keer "```" om te beginnen met een code block, en gebruik 3 keer "```" aan het einde van een code block, dan ziet het er als volgt uit en maakt het leesbaar, en heeft nog andere voordelen (bijvoorbeeld dat er geen smilies in het code block komen)/

```
INPUT BOOLEAN (FOR AUTOMATION)
input_boolean:
waste_moved:
name: Waste has been moved
initial: 'off'
icon: mdi:delete-empty
waste_reminder:
name: Waste reminder enabled
initial: 'on'
AUTOMATION
automation:

alias: Reset waste notification
trigger:
platform: state
entity_id: input_boolean.waste_moved
to: 'on'
for:
hours: 12
action:

service: input_boolean.turn_off
entity_id: input_boolean.waste_moved
service: input_boolean.turn_on
entity_id: input_boolean.waste_reminder
alias: Mark waste as moved from notification
trigger:
platform: event
event_type: ios.notification_action_fired
event_data:
actionName: MARK_WASTE_MOVED
action:

service: input_boolean.turn_on
entity_id: input_boolean.waste_moved
alias: Waste has not been moved
trigger:
platform: time_pattern
hours: "/1"
condition:
condition: and
conditions:
- condition: state
entity_id: input_boolean.waste_moved
state: 'off'
- condition: state
entity_id: input_boolean.waste_reminder
state: 'on'
- condition: time
after: '18:00:00'
before: '23:00:00'
- condition: template
value_template: "{{ states('sensor.afvalwijzer_tomorrow') != 'Geen' }}"
action:

service: notify.family
data:
title: "Afval"
message: 'Het is vandaag - {{ now().strftime("%d-%m-%Y") }}. Afvaltype(n): {{ states.sensor.afvalwijzer_tomorrow.state }} wordt opgehaald op: {{ (as_timestamp(now()) + (24*3600)) | timestamp_custom("%d-%m-%Y", True) }}!'
data:
push:
badge: 0
category: 'afval'
```

https://github.com/xirixiz/my-hass-config
