### ISSUE TITLE
Home Assistant 2021.2.1: Not Starting

### ISSUE THREAD

**Issue by bjarnekrottje** [xirixiz/homeassistant-afvalwijzer#130]
## Version of the custom_component
Version: 5.3.0
Home Assistant Version: 2021.2.1

## Configuration

```yaml
# Afvalwijzer
sensor:
  - platform: afvalwijzer
    provider: mijnafvalwijzer        # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, afvalstoffendienstkalender or rova
    postal_code: !secret postal_code             # (required, default = '')
    street_number:  !secret street_number                # (required, default = '')
    suffix: ''                       # (optional, default = '')
    include_date_today: false        # (optional, default = false) to take or not to take Today into account in the next pickup.
    default_label: Geen              # (optional, default = Geen) label if no date found
    id: ''                           # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
```

## Describe the bug
Afvalwijzer is not booting, giving an error at boot of Home Assistant. (See below)

## Debug log

```text
2021-02-05 20:04:16 ERROR (SyncWorker_0) [custom_components.afvalwijzer.const.const] Other error occurred: 'ophaaldagen'
2021-02-05 20:04:16 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 65, in async_setup_platform
    afvalwijzer = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/provider/afvalwijzer.py", line 67, in __init__
    (
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by bjarnekrottje** [comment]
Wellicht te maken met het vervangen van de Python-versie?
Zie blog Home Assistant: [2021.2: Z-Wave... JS!](https://www.home-assistant.io/blog/2021/02/03/release-20212/)

**Comment by xirixiz** [comment]
It seems no data is available on your postal code and street number. Could you provide this information so I can verify? For me the component is working properly on the latest release of hass.

**Comment by bjarnekrottje** [comment]
Of course, my postal code is 6361TD with street_number 8

**Comment by bjarnekrottje** [comment]
The services indeed don't provide the waste information for my postal code, that's a pitty.
Maybe an idea to catch this situation and provide a description in the logs that this is the case ;)

**Comment by xirixiz** [comment]
Imho it's clear enough from the documentation this only supports a couple of waste providers in the Netherlands and the range of postal codes supported isn't very clear stated somewhere. Do you know which provider you need to look at?

**Comment by xirixiz** [comment]
https://rd4.syzygy.eu/6361TD/8

**Comment by bjarnekrottje** [comment]
Indeed Rd4, will look into that, thanks for the clarification ;)
