### ISSUE TITLE
Feature request: exclude waste type

### ISSUE THREAD

**Issue by bjkoekkoek** [xirixiz/homeassistant-afvalwijzer#131]
Hi,

It would be awesome to be able to exclude a type of wast for example “textiel” or “kerstbomen” for the entities like next_item and Tomorrow etc.

**Comment by xirixiz** [comment]
Yeah, I actually was thinking of implementing an exclude list, and I think this is really easy to implement.
I`ll get back on this later this week.

**Comment by xirixiz** [comment]
It's already done now, it was pretty easy 👍. The master branch has been updated, but there is no new release yet. Please test the component and share the outcome please. Maybe @Mariusthvdb like to test this as well 😃

**Comment by bjkoekkoek** [comment]
I would love to test that, but I don't know how  :). I see the changes in the files but the option is only available in test_sensor.py. I assume I need to modify somewhere which py script is beeing used?

**Comment by jghaanstra** [comment]
I came here looking exactly for this feature. Downloaded the zip file from master branch and update my custom component. Rebooted HA to load the new version of the afvalwijzer component and went to update my afvalwijzersensor. It looks like this:

```
- platform: afvalwijzer
  provider: mijnafvalwijzer
  postal_code: 97xxCx
  street_number: xx
  include_date_today: true
  exclude_list: 'kga, textiel'
```

But the error I'm getting when checking the config is:
`Invalid config for [sensor.afvalwijzer]: [exclude_list] is an invalid option for [sensor.afvalwijzer]. Check: sensor.afvalwijzer->exclude_list. (See ?, line ?).`

**Comment by bjkoekkoek** [comment]
Yes I have also tried that, same error here.

**Comment by xirixiz** [comment]
Fixed in 5.3.2... missed one variable in the code indeed.

**Comment by bjkoekkoek** [comment]
Works like a charm now! :)

**Comment by Mariusthvdb** [comment]
> It's already done now, it was pretty easy 👍. The master branch has been updated, but there is no new release yet. Please test the component and share the outcome please. Maybe @Mariusthvdb like to test this as well 😃. The readme has been updated.

Thanks @xirixiz , tested, and working as expected. Sorry for the delay in answering, been somewhat busy migrating to ZwaveJS here....
Don't know which trash-type to chose to exclude yet though, I want them al ;-)
