### ISSUE TITLE
update in HACS: No content available

### ISSUE THREAD

**Issue by canedje** [xirixiz/homeassistant-afvalwijzer#132]
HACS is saying there is an update available.
current is version is 5.3.0. Update is 5.3.2/
After hit the update button. Nothing happens. Log says "no content available"

Runnig Supervised HA in Unraid in a VM
HA version 2021.2.2

## Configuration

```yaml

Add your logs here.

```

## Debug log

```text

Add your logs here.

```

**Comment by xirixiz** [comment]
Hi, I just removed and reinstalled the component without any issues. Not sure what's happening on your side.
Maybe remove it and then reinstall it? Is HACS up-to-date? Restart HASS maybe?

Also the release is here:
https://github.com/xirixiz/homeassistant-afvalwijzer/releases

**Comment by canedje** [comment]
After 1 hour trying again: It is updated.
I think something was not ready yet in HACS centre or so.

Problem solved
