### ISSUE TITLE
Version property missing in manifest

### ISSUE THREAD

**Issue by LouisMT** [xirixiz/homeassistant-afvalwijzer#133]
## Version of the custom_component
5.3.2

## Configuration
_Not relevant_

## Describe the bug
Starting with Home Assistant 2021.3.0, a `version` property is required in the `manifest.json`. See: https://developers.home-assistant.io/docs/creating_integration_manifest/#version.

## Debug log

```text
WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'afvalwijzer'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'afvalwijzer'
```

**Comment by xirixiz** [comment]
5.3.3 has just been released! Thanks!
