### ISSUE TITLE
version conflict?

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#134]
## Version of the custom_component

Exactly the issue at hand, not sure, since the repo shows anther version than the resource in the download??

the new commit shows
<img width="760" alt="Schermafbeelding 2021-02-26 om 10 03 26" src="https://user-images.githubusercontent.com/33354141/109279518-2038ac80-781a-11eb-904c-3688b2539d51.png">

while the repo file shows:

<img width="694" alt="Schermafbeelding 2021-02-26 om 10 03 50" src="https://user-images.githubusercontent.com/33354141/109279557-30e92280-781a-11eb-9a48-cd53936a3092.png">

which is it?
thanks
## Configuration

```yaml

Add your logs here.

```

## Debug log

```text

Add your logs here.

```

**Comment by xirixiz** [comment]
Don't fool yourself. A release can always differ from the master branch ;)
