### ISSUE TITLE
update failed, afvalwijzer can't make sensors

### ISSUE THREAD

**Issue by schijven** [xirixiz/homeassistant-afvalwijzer#135]
## Version of the custom_component
Newest version updated
## Configuration
in sensors.yaml:

  - platform: afvalwijzer
    provider: mijnafvalwijzer        # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, afvalstoffendienstkalender or rova
    postal_code: !secret afvalwijzer_postcode             # (required, default = '')
    street_number: !secret afvalwijzer_postcode                # (required, default = '')
    suffix: ''                       # (optional, default = '')
    include_date_today: false        # (optional, default = false) to take or not to take Today into account in the next pickup.
    default_label: Geen              # (optional, default = Geen) label if no date found
    id: ''                           # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
    exclude_list: ''                 # (optional, default = '') comma separated list of wast types (case ignored). F.e. "papier, gft"
```yaml

Add your logs here.
Logger: homeassistant.components.sensor
Source: custom_components/afvalwijzer/provider/afvalwijzer.py:69
Integration: Sensor (documentation, issues)
First occurred: 19:12:07 (1 occurrences)
Last logged: 19:12:07

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 68, in async_setup_platform
    afvalwijzer = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/provider/afvalwijzer.py", line 69, in __init__
    (
TypeError: cannot unpack non-iterable NoneType object
--------------------------------------------------------------------------------------------------
Logger: custom_components.afvalwijzer.const.const
Source: custom_components/afvalwijzer/provider/afvalwijzer.py:148
Integration: afvalwijzer (documentation, issues)
First occurred: 19:12:07 (1 occurrences)
Last logged: 19:12:07

Other error occurred: 'ophaaldagen'
```

## Describe the bug

Sensors are not created
The previus version I functioned well. 
In previus version I had:     #zipcode: !secret afvalwijzer_postcode
    #housenumber: !secret afvalwijzer_huisnummer
I changed the items to postal_code and streetnumber 
## Debug log

```text

Add your logs here.

```

**Comment by xirixiz** [comment]
Can you share your postal code, a house number and your provider. It looks like no data is currently available in json at your provider. Happens sometimes, and sometimes it takes up to a week before they fix it. But I can verify if this is the case.

**Comment by schijven** [comment]
Dear Bram,

I have also the app installed, and there is data. In the picture you can
see my postal code and number. provider is Saver, but i use afvalwijzer
(see picture).
Strange is that it works with the older version, when I updated it, it
stopped working.

Greetings Tom Schijven

Op vr 5 mrt. 2021 om 07:45 schreef Bram van Dartel <notifications@github.com

**Comment by xirixiz** [comment]
Hi Tom, the app works slightly different so cannot be compared unfortunatly.
I just tried to find you postal code but couldn't find it in the screenshot...

It could ofcourse be a bug in this component, therefor I need to do some checks with your postal code to find out :).

**Comment by xirixiz** [comment]
You switched from a very old version I just noticed .... as you were still using zipcode and housenumber

**Comment by schijven** [comment]
Hi Bram, sorry, zip-code 4706HN

Op vr 5 mrt. 2021 om 08:05 schreef Bram van Dartel <notifications@github.com

**Comment by xirixiz** [comment]
Een test geeft netjes data terug, maar alleen met huisnummer 1.... ik heb ook 2, 4, 7 en 10 geprobeerd maar dan krijg ik dat er geen data beschikbaar is. Ik krijg alleen data terug op de oneven huisnummers.

-> python3 -m afvalwijzer.test_sensor

```
{'plastic': datetime.datetime(2021, 3, 5, 0, 0), 'gft': datetime.datetime(2021, 3, 9, 0, 0), 'restafval': datetime.datetime(2021, 3, 12, 0, 0), 'papier': datetime.datetime(2021, 3, 30, 0, 0)}
{'gft': datetime.datetime(2021, 3, 9, 0, 0), 'restafval': datetime.datetime(2021, 3, 12, 0, 0), 'plastic': datetime.datetime(2021, 3, 19, 0, 0), 'papier': datetime.datetime(2021, 3, 30, 0, 0)}
{'today': 'plastic', 'tomorrow': 'Geen', 'day_after_tomorrow': 'Geen', 'next_date': datetime.datetime(2021, 3, 9, 0, 0), 'next_in_days': 4, 'next_item': 'gft'}
['gft', 'restafval', 'plastic', 'papier']
['today', 'tomorrow', 'day_after_tomorrow', 'next_date', 'next_in_days', 'next_item']
```

Ik vermoed dus dat er een configuratiefout is. Heb je mijn laatste post gezien vwb street_number?

**Comment by schijven** [comment]
Is dat deze> https://github.com/xirixiz/homeassistant-afvalwijzer/issues/130
Anders nee. Heb trouwens geprobeert met nummer 1, maar dat maakt geen
verschil, zelfde fout

Op vr 5 mrt. 2021 om 08:23 schreef Bram van Dartel <notifications@github.com

**Comment by xirixiz** [comment]
Hi Tom, it's definatly a configuration error. I just tried it directly in hass in my environment and everything is working as expected:

![image](https://user-images.githubusercontent.com/11210639/110092042-74530c00-7d99-11eb-86d2-20333ffe491e.png)

Please verify all your settings again. It looks like a setting like (street_number) is misspelled or something.

**Comment by schijven** [comment]
Dear Bram,

Settings copy from site:

sensor:
    - platform: afvalwijzer
      provider: mijnafvalwijzer        # (required, default =
mijnafvalwijzer) either choose mijnafvalwijzer,
afvalstoffendienstkalender or rova
      postal_code: 1234AB              # (required, default = '')
      street_number:  5                # (required, default = '')
      suffix: ''                       # (optional, default = '')
      include_date_today: false        # (optional, default = false)
to take or not to take Today into account in the next pickup.
      default_label: Geen              # (optional, default = Geen)
label if no date found
      id: ''                           # (optional, default = '') use
if you'd like to have multiple waste pickup locations in HASS
      exclude_list: ''                 # (optional, default = '')
comma separated list of wast types (case ignored). F.e. "papier, gft"

I only changed postal_code (other settings are oké) but the result is the
same. So I disagree that it is a setting issue.
When i look at my sensos, i discoverd that the names are changed.
[image: afbeelding.png]



Op vr 5 mrt. 2021 om 10:00 schreef Bram van Dartel <notifications@github.com

**Comment by xirixiz** [comment]
Hi Tom, could you use formatting please 😄 
https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

Not to be disrespectful, but I`m 100% sure the issue isn't related to this component:
1: Nobody else faces this issue.
2: All source data has been verified and is correct.
3: Tested in the latest HASS with the latest version of this component, all correct.
4: Performed additional tests with tools part of this component, all correct.

Remove the whole bulk of code and try this and let's see what happens:
```
sensor:
  - platform: afvalwijzer
    provider: mijnafvalwijzer
    postal_code: 4706HN
    street_number: 5
```

Also you could enable debugging (configuration.yaml):
```
logger:
  default: info
  logs:
    custom_components.afvalwijzer: debug
```

**Comment by schijven** [comment]
Found the error. Type error in the secret.yaml


Op vr 5 mrt. 2021 om 10:48 schreef Bram van Dartel <notifications@github.com
