### ISSUE TITLE
API Call

### ISSUE THREAD

**Issue by GRX** [xirixiz/homeassistant-afvalwijzer#137]
Hi,

In principe is dit geen issue, maar enkel een vraag over de opbouw van `homeassistant-afvalwijzer`.

Ik probeer de data rechtstreeks te laden in node-red. Ik ben niet thuis in Python en wilde toch proberen te ontleden welk API eindpunt je aanroept. Nu ben ik een dergelijk eind, maar blijf ik 
```
{
   "response": "NOK", 
   "data": [],
  "error": "Not valid input"
}
```
terugkrijgen van de API.

---

Ik snap ook niet precies wat de constructor is hier.
`/?apikey=`: API Key 
`&method=postcodecheck`: Nodig voor type call?
`&postcode=`: 1234ab
`&street=`: janjanssenstraat
`&huisnummer=`: 123
`&app_name=`: afvalwijzer (Emuleren we hier nu gewoon de app? ;) )
`&platform=`: phone
`&afvaldata=`: [????]
`&langs=`: nl

bovenstaande data is natuurlijk de juiste data, op `afvaldata` na.
Ik denk dus dat ik `afvaldata` mis, deze kan ook niet in de GET ontbreken, maar wat zou op deze plek moeten komen?

Heb je een voorbeeld call die ik als referentie kan gebruiken?
Ontzettend bedankt!

**Comment by xirixiz** [comment]
Hoi, dit is de juiste url, en in feite is dat idd hetzelfde endpoint als de app(s) gebruiken.

```https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=<redacted>&method=postcodecheck&postcode=4706HN&street=&huisnummer=1&toevoeging=&app_name=afvalwijzer&platform=phone&afvaldata=2021-05-01&langs=nl&```

```afvaldata``` moet aanwezig zijn ander krijg je idd ```NOK```. De waarde is de datum van vandaag ```<YYYY-MM-DD>```.

**Comment by GRX** [comment]
Je bent een held! Ontzettend bedankt!
