### ISSUE TITLE
Add unique_id to sensors

### ISSUE THREAD

**Issue by mvdwetering** [xirixiz/homeassistant-afvalwijzer#138]
## Information

I think it would be nice if the sensors would have a `unique_id`
This would allow for example renaming sensors from within the HA UI.

The only disadvantage I see would be that the sensors have to be manually deleted though HA UI when the integration is removed from `configuration.yaml` (which could be avoided by also implementing config_flow but that is way more work).

I tried to add unique_ids locally and this code seems to work for me, but not sure if it covers all cases.
```
    @property
    def unique_id(self):
        """Return the uniqueid of the entity. Assumption is 1 instance per home, so type,postcode,huisnummer,suffix should be unique. Hashing it to avoid leaking data if a uniqueid ends up in logging or something """
        return hashlib.sha1(f"{self.waste_type}{self.config.get(CONF_POSTAL_CODE)}{self.config.get(CONF_STREET_NUMBER)}{self.config.get(CONF_SUFFIX,'')}".encode("utf-8")).hexdigest()
```
Note that the code above is not showing additional imports needed.

**Comment by xirixiz** [comment]
Yes, I like the idea, but I prefer to use the config_flow wow. I did spend some time on it in the past, but due to limited time I lost track :). However, there are a lot of good (reusable) examples nowadays, so my guess is it might be easy to implement. I`ll have a look.

**Comment by xirixiz** [comment]
It's been a while and would like to implement this request. Would it be possible for you to create a PR @mvdwetering? I`ll then review and test the code changes. Thanks!

**Comment by xirixiz** [comment]
Done! On the master branch it's available. Could be ending up in duplicate entities, in that case remove the enities which then show "Unavailble", then restart again and everything is working as expected. 

Will release this soon official, but would be nice if you could verify this upfront.

**Comment by mvdwetering** [comment]
Sorry for not getting back to you, been a challenge to get some time to spare recently.
Thanks for getting it in anyway 👍
