### ISSUE TITLE
Not entities shown when using a non dummy postal code

### ISSUE THREAD

**Issue by svleuken** [xirixiz/homeassistant-afvalwijzer#142]
Ls,

When adding below default code to the configuration.yaml, I'm able to see all the sensor.afvalwijzer** entities:

sensor:
- platform: afvalwijzer
  provider: mijnafvalwijzer  
      postal_code: 1234AB    
      street_number:  5         

When replacing the dummy postalcode with my own (and rebooting) no sensor.afvalwijzer** entities are shown anymore.
Any idea what can cause this issue?

**Comment by xirixiz** [comment]
Is mijnafvalwijzer supported by you commune?

You can verify via the website or using this url (replace postal_code and street_number):
https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=1234AB&street=&huisnummer=5&toevoeging=&app_name=afvalwijzer&platform=phone&afvaldata=2021-07-09&langs=nl&

**Comment by svleuken** [comment]
Sorry. Forgot to mention that my postcal code is NOT supported....but neither is the dummy postalcode of 1234AB
So I'm just wondering why I can see the afvalwijzer entities with the dummy postalcode, and not with my own postalcode....

**Comment by xirixiz** [comment]
The dummy postalcode is working. It's a dummy provided by mijnafvalwijzer.nl. When you click on that link you'll see dummy data. Your postal code cannot gather any data and therefor isn't showing up in home assistant :).

In which commune do you live? There most probably is another provider suitable for you and maybe your commune is supported as this component supports 3 waste providers.

**Comment by xirixiz** [comment]
Closed the issue as it's not an issue. You can still ask questions or you can ask questions at the hass community forum ofcourse

**Comment by svleuken** [comment]
Understood. 
The not showing up for the dummy postal code was when entering this directly on the website. When using the API it indeed DOES provide data. 
But thanks for clarifying. Aprreciated!
