### ISSUE TITLE
error in the log Other error occurred: 'ophaaldagen'

### ISSUE THREAD

**Issue by IIIdefconIII** [xirixiz/homeassistant-afvalwijzer#144]
Hi, im using the latest version from your github but my sensors wont be created:

When i look at the logfiles i see:

```
 Logger: custom_components.afvalwijzer.const.const
Source: custom_components/afvalwijzer/provider/afvalwijzer.py:148
Integration: afvalwijzer (documentation, issues)
First occurred: 10:49:19 (1 occurrences)
Last logged: 10:49:19
Other error occurred: 'ophaaldagen'
```

Maybe this is preventing to load the plugin any further.

Do you have any idea? Could this me a language issie?

Many thanks for this widget!

**Comment by xirixiz** [comment]
Hi, sorry for the late reply, but I think there was an issue on the side of afvalwijzer. Does this issue still appear?

**Comment by xirixiz** [comment]
Oke, it's clear that there's no data availble for the postal code / street number provided.
I assume you changed all the 99 stuff in the config with values that are applicable to your address?

If so, if you provide me your postal code and a random valid street number, I could verify some things for you.

**Comment by DutchDynamics** [comment]
Hi, Yes I was hiding the postalcode and number.
Changing it to another random code, it worked. After that test my own postcode. That also works.

So, looks like it's magical solved. Thanks anyway
