### ISSUE TITLE
Config flow kon niet geladen worden

### ISSUE THREAD

**Issue by Harrykoolen** [xirixiz/homeassistant-afvalwijzer#145]
## Configuration

```yaml

Add your logs here.

```

## Debug log

```text

Add your logs here.

```

**Comment by xirixiz** [comment]
Yes, the master branch isn't working.
I need to revert the master branch so it matches the latest release and start working from a development branch.
Anyway, download a release please: https://github.com/xirixiz/homeassistant-afvalwijzer/releases

Or use the hacs to install the component.

**Comment by Harrykoolen** [comment]
i used hacs but it stil not work or i do something wrong

**Comment by xirixiz** [comment]
That's odd, could you check the logfiles?
Can you share some screenshots of hacs where you select the version?

At least, never use the master branch. Maybe remove the component first and then reinstall using hacs ans release 2021.05.01

**Comment by xirixiz** [comment]
You can also hit the three vertical dots on the afvalwijzer component in hacs and click on Information. On the top left you should see the release

**Comment by Harrykoolen** [comment]
![image](https://user-images.githubusercontent.com/91058044/134027925-b27e808f-d06d-40d2-9501-05a8721a5cf7.png)

**Comment by Harrykoolen** [comment]
after reinstall i cant fint it by intergrations

**Comment by xirixiz** [comment]
The version you've selected is correct. It's strange you receive a config flow as I checked version 2021.05.01 and there's nothing related to the config flow in it. However, it might be HASS has changed something. 

Looking at your logs it's a common message for custom integrations, so you can ignore that message. I`ll try to simmulate the issue you're facing by installing, removing and reinstalling the component via hacs in my dev environment.

**Comment by xirixiz** [comment]
Tried it twice and found no issues, works like a charm with the latest version of HASS, HACS and Afvalwijzer release 2021.05.01. Did you restart hass after removal and before re-adding the component?

You could also ask for additional help at the community: https://community.home-assistant.io/t/garbage-pickup-date-mijnafvalwijzer-nl-custom-component/34631/629

**Comment by Harrykoolen** [comment]
i tried today again now can i select it by integrations. but the same error

Config flow kon niet geladen worden

**Comment by Harrykoolen** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:711
First occurred: 12:37:37 (1 occurrences)
Last logged: 12:37:37

Error occurred loading configuration flow for integration afvalwijzer: No module named 'custom_components.afvalwijzer.config_flow'

**Comment by xirixiz** [comment]
Hmm, maybe you didn't add the config manually?

https://github.com/xirixiz/homeassistant-afvalwijzer#example-configuration-my-config

**Comment by Harrykoolen** [comment]
dit is voor het eerst dat ik met hass bezig ben, hoef ik alleen .

  sensor:
    - platform: afvalwijzer
      provider: mijnafvalwijzer        # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, afvalstoffendienstkalender or rova
      postal_code: 1234AB              # (required, default = '')
      street_number:  5                # (required, default = '')
      suffix: ''                       # (optional, default = '')
      include_date_today: false        # (optional, default = false) to take or not to take Today into account in the next pickup.
      default_label: Geen              # (optional, default = Geen) label if no date found
      id: ''                           # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
      exclude_list: ''                 # (optional, default = '') comma separated list of wast types (case ignored). F.e. "papier, gft"
 

dit stuk in mijn configration yaml te plakken?

**Comment by xirixiz** [comment]
Klopt, alleen de required velden en de optionele wanneer je die nodig hebt.

Je kan trouwens met ```test``` drie quotes "```test```" code netter weergeven op GitHub

**Comment by Harrykoolen** [comment]
het werkt nog niet, hierbij mijn configuration .yaml


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
 server_port: 3011
   

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: xxxxxx
  password: xxxxxxx
  max_retries: 3
  default_measurement: state
  
 # Tasmoadmin panel
panel_iframe:
  tasmoadmin:
   title: Tasmoadmin
   icon: mdi:ligtbulb-on
   url: http://1xxx

sensor:
    - platform: afvalwijzer
      provider: mijnafvalwijzer        # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, afvalstoffendienstkalender or rova
      postal_code: 5126BJ              # (required, default = '')
      street_number:  21                # (required, default = '')

**Comment by Harrykoolen** [comment]
of het ik het mis dat dit niet bij intergraties bij komt te staan?

**Comment by Harrykoolen** [comment]
heb dit kunnen toevoegen dus er werkt iets gelukkig maar niet met plaatjes
wat doe ik verkeerd?

![image](https://user-images.githubusercontent.com/91058044/134213523-20a37a53-db43-4931-ab8e-f43573b17516.png)

**Comment by xirixiz** [comment]
Kijk dat ziet er goed uit. HASS maakt gebruik van lovelace, met lovelace is het mogelijk de data op verschillende manierenr weer te geven. Het voorbeeld dat ik bij het component heb geplaats is eenvoudig te implementeren. Kijk even bij de sectie waar over lovelace wat geschreven is in de readme. Voor de weergave zoals in het voorbeeld heb je overigen ook het component "auto-entities" nodig. Gelukkig voor jou hoef je het alleen maar te installeren en niet te configureren :).

Lovelace edit:
- Klik op de 3 verticale puntjes rechtsboven
- Klik nog een keer op de 3 puntjes rechtsboven en klik "raw configuration editor"
- Plak de code uit de readme, maar zorg ervoor dat de yaml wel in het corrrecte formaat blijft!

Mocht je nog vragen hebben, stel deze dan aub in de community (de link die ik eerder stuurde). Daar zitten genoeg personen die jou kunnen helpen met alle vragen. Succes!

**Comment by xirixiz** [comment]
Of na de eerste stap, linksonder "Add Card -> Entities -> Show Code Editor -> Code verwijderen en die uit de README plakken"

**Comment by Harrykoolen** [comment]
Ja ik kom al dichtbij met het werkend krijgen .

Ik zie alleen niet in de zip als ik doe download de plaatjes

met vriendelijke groet

Harry Koolen
________________________________
