### ISSUE TITLE
Error in Log - HA not setting up sensor

### ISSUE THREAD

**Issue by CrashyNL** [xirixiz/homeassistant-afvalwijzer#146]
## Version of the custom_component
I've setup the integration through HACS (version 2021.05.01)

## Configuration.yaml
sensor:
  - platform: afvalwijzer
    provider: mijnafvalwijzer        # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, afvalstoffendienstkalender or rova
    postal_code: 1234AB              # (required, default = '') - I've added my own zipcode
    street_number: 1                # (required, default = '') - I've added my own street number
    include_date_today: true        # (optional, default = false) to take or not to take Today into account in the next pickup.
    default_label: Geen              # (optional, default = Geen) label if no date found
    exclude_list: "papier, pmd"             # (optional, default = '') comma separated list of wast types (case ignored). F.e. "papier, gft"

## Describe the bug
I'm getting the following errors in de HA Log, and i'm not able to get the sensor in HA / Lovelace

## Debug log
This error originated from a custom integration.

Logger: custom_components.afvalwijzer.const.const
Source: custom_components/afvalwijzer/provider/afvalwijzer.py:148
Integration: afvalwijzer (documentation, issues)
First occurred: 13:12:08 (1 occurrences)
Last logged: 13:12:08

Other error occurred: 'ophaaldagen'
-------------------------------------------
Logger: homeassistant.components.sensor
Source: custom_components/afvalwijzer/provider/afvalwijzer.py:69
Integration: Sensor (documentation, issues)
First occurred: 13:12:08 (1 occurrences)
Last logged: 13:12:08

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 68, in async_setup_platform
    afvalwijzer = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/provider/afvalwijzer.py", line 69, in __init__
    (
TypeError: cannot unpack non-iterable NoneType object
-------------------------------------------

**Comment by CrashyNL** [comment]
If I try to add the afvalwijzer in the (regular) integrations part of HA, I'm also getting an error:

Error
Config flow could not be loaded

**Comment by xirixiz** [comment]
Please check: https://github.com/xirixiz/homeassistant-afvalwijzer/issues/145

**Comment by CrashyNL** [comment]
Sorry, I see no solution in the other thread. Also new to HA, but finding my way around. Just not getting where I fail with the setup

**Comment by xirixiz** [comment]
But the solution is there. You need to add at least the required information before adding the custom component.
In a future release I will implement the config flow part.

https://github.com/xirixiz/homeassistant-afvalwijzer#example-configuration-my-config
