### ISSUE TITLE
Afvalwijzer not working with latest HASS

### ISSUE THREAD

**Issue by Remko76** [xirixiz/homeassistant-afvalwijzer#148]
I tried to install Afvalwijzer in the latest 2021.10.2 version of HASS, but it is giving me errors in the log file:

"Error occurred loading configuration flow for integration afvalwijzer: No module named 'custom_components.afvalwijzer.config_flow'"

```
Logger: homeassistant.components.sensor
Source: custom_components/afvalwijzer/provider/afvalwijzer.py:69
Integration: Sensor (documentation, issues)
First occurred: 20:16:05 (1 occurrences)
Last logged: 20:16:05

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 68, in async_setup_platform
    afvalwijzer = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/provider/afvalwijzer.py", line 69, in __init__
    (
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by xirixiz** [comment]
Hoi Remco, please check here. I know what the issue is, so I`ll bring out a new release soon. In the meantime you can follow this:
https://github.com/xirixiz/homeassistant-afvalwijzer/issues/145

You need to add some configuration to you configuration.yaml manually upfront.

**Comment by Remko76** [comment]
Unfortunately it still does not work for me. I did create all the configuration.yaml entries, but keep getting the same error. Also tried the previous version, but still does not work for me.
