### ISSUE TITLE
The next collection day and waste type is incorrect when today is a collection day

### ISSUE THREAD

**Issue by bscheutjens** [xirixiz/homeassistant-afvalwijzer#149]
### Issue

Today is the collection day for PMD. I'd expect the next date (entity sensor.afvalwijzer_next_date) to be either today or the next date something is collected. In my case that is PMD again in two weeks. The next date for PMD (entity sensor.afvalwijzer_pmd) is correct and shows 10-11-2021.

However, the entity sensor.afvalwijzer_next_date shows the next date of Papier, which is three days later than the next PMD date. The entity sensor.afvalwijzer_next_item also shows Papier instead of PMD. These are incorrect and should show the next PMD date and type.

Please see the additional info for all entities I use and their current values. 

### Which version has the issue?

2021.10.01

### Additional information

Current date: 27-10-2021
The entity values:
- sensor.afvalwijzer_today: PMD (correct)
- sensor.afvalwijzer_tomorrow: Geen (correct)
- sensor.afvalwijzer_day_after_tomorrow: Geen (correct)
- sensor.afvalwijzer_pmd: 10-11-2021 (correct)
- sensor.afvalwijzer_papier: 13-11-2021 (correct)
- sensor.afvalwijzer_restafval: 22-11-2021 (correct)
- sensor.afvalwijzer_next_item: Papier (incorrect, should be PMD)
- sensor.afvalwijzer_next_date: 13-11-2021 (incorrect, should be 10-11-2021)
- sensor.afvalwijzer_next_in_days: 17 (incorrect, should be 14)

**Comment by xirixiz** [comment]
Closing this issue btw. If the issue still persists, then please re-open this issue.

**Comment by xirixiz** [comment]
Funny thing is that this bugfix has caused a new issue :)

Let me check it and create a new release this weekend.
#151

**Comment by xirixiz** [comment]
Released 2021.11.02.
