### ISSUE TITLE
mijnafvalwijzer.nl SSL Certificate expired 2021-11-09

### ISSUE THREAD

**Issue by RGlintmeijer** [xirixiz/homeassistant-afvalwijzer#150]
### Issue

Home Assistant Integration cannot fetch data from api.mijnafvalwijzer.nl because the SSL Certificate expired on 2021-11-09.

This is not a problem in this integration, but should be fixed by mijnafvalwijzer.

### Which version has the issue?

2021.11.01

### Anything in the logs that might be useful?

```txt
HTTPSConnectionPool(host='api.mijnafvalwijzer.nl', port=443): Max retries exceeded with url: /webservices/appsinput/?apikey=************ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
```

### Additional information

I’ve sent an email to info@mijnafvalwijzer.nl to notify them.

**Comment by xirixiz** [comment]
Thanks! I really like it that you're informing me and others about this, and also you took action towards mijnafvalwijzer!

**Comment by Qpernicus** [comment]
I noticed the same error.. Kinda N00b mistake.. then again, we can all forget something.

**Comment by daxy01** [comment]
FYI, it seems the certificate is now renewed as the integration works again and log message is gone after a restart of HA.
