### ISSUE TITLE
No module named 'custom_components.afvalwijzer.const'

### ISSUE THREAD

**Issue by aforch** [xirixiz/homeassistant-afvalwijzer#152]
### Issue

Starting HA version 2021.10.6, running in docker, receiving the following log error from afvalwijzer (in debug mode)   
```
 File "/config/custom_components/afvalwijzer/sensor.py", line 16, in <module>
    from .const.const import (
ModuleNotFoundError: No module named 'custom_components.afvalwijzer.const'
```
It appears the afvalwijzer module is not being loaded for whatever reason.

### Which version has the issue?

2021.11.02

### What was the last working version?

Prior to HA upgrade, previous HA version was at least 1 year old

**Comment by xirixiz** [comment]
I have the feeling it's related to your Docker config. Can you share your Docker run comand  or your Docker Compose content?

**Comment by aforch** [comment]
Here is my docker-compose. This was not changed when updating the HA version.
 
 HA_Prod:
    container_name: homeassistant
    restart: unless-stopped
    image: homeassistant/home-assistant:stable
    network_mode: host
    depends_on:
      - "influxdb"
    volumes:
      - /mnt/docker_data/homeassistant_PROD/config:/config
      - /etc/localtime:/etc/localtime:ro
    user: 1000:999
    command: '/config/run'
    environment:
      - UMASK=007

**Comment by xirixiz** [comment]
Thanks, it seems indeed to be looking fine. Can you try to reinstall the component via HACS?
You could also check whether ```/mnt/docker_data/homeassistant_PROD/config/custom_components/afvalwijzer/const/const.py ``` exists and has the correct security settings.

**Comment by aforch** [comment]
I don't use HACS, I do a manual install and I was missing a number of files, once you helped me to realize that I was missing /const/const.py I was able to fix it. Thanks for pointing me in the right direction.
