### ISSUE TITLE
Waardlanden afvalkalender integration

### ISSUE THREAD

**Issue by gijs007** [xirixiz/homeassistant-afvalwijzer#157]
### Request

Would it be possible to add an integration for the Waardlanden afvalkalender?
It can be found here: https://www.waardlanden.nl/particulieren/afvalinzameling/afvalkalender

**Comment by xirixiz** [comment]
Hi, could be :). Do you have an example postal code?

**Comment by gijs007** [comment]
Great! An example postal code is 4208AD

**Comment by xirixiz** [comment]
You could also consider to use https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer ;)

**Comment by gijs007** [comment]
Thanks, didn't know that existed. It works well :)

It would be helpful if each afvalkelender integration was referring to the other, so that users can easily find the one they need, or even merging the projects, to make one integration for the entire country. ;)
