### ISSUE TITLE
Update for next item fails

### ISSUE THREAD

**Issue by adekloet** [xirixiz/homeassistant-afvalwijzer#158]
### Issue

I believe there might be an issue with the roll over to the next your, does this resolves itself after the 31st of Dec?

Thanks,

--->

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/afvalwijzer/sensor_custom.py:88
Integration: afvalwijzer (documentation, issues)
First occurred: 1:10:52 AM (33 occurrences)
Last logged: 11:11:54 AM

Update for sensor.afvalwijzer_next_item fails
Update for sensor.afvalwijzer_next_date fails
Update for sensor.afvalwijzer_next_in_days fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/config/custom_components/afvalwijzer/sensor_custom.py", line 88, in async_update
    if isinstance(waste_data_custom[self.waste_type], datetime):
KeyError: 'next_item'

### Which version has the issue?

newest version

**Comment by yfands** [comment]
yup, the error is gone the next year is available on mijnafvalwijzer, so the 'program' is whole again till the end of next year ;-)

**Comment by xirixiz** [comment]
Yep, indeed, it's the problem of the provider not providing any data....yet... in some areas.
I`ll make a fix to not throw an error at least.

**Comment by adekloet** [comment]
Thanks @xirixiz, would be good to catch the "error", because of the missing data at the source. 

Happy 2022!
