### ISSUE TITLE
Support additional municipality (Lingewaard)

### ISSUE THREAD

**Issue by Crimby88** [xirixiz/homeassistant-afvalwijzer#163]
### Request

My municipality changed from the regular afvalwijzer to afvalwijzer.lingewaard.nl. Now the integration is not working anymore.
Would be great if this is supported aswell.

Example of data:
URL: [https://afvalwijzer.lingewaard.nl/](https://afvalwijzer.lingewaard.nl/)
Postal code: 6851NL
House number: 16

Much appreciated!

**Comment by xirixiz** [comment]
Hi. currently I`m working on implementing more municipalities:
https://github.com/xirixiz/homeassistant-afvalwijzer/issues/160
