### ISSUE TITLE
Collectors data is wrong since the latest update

### ISSUE THREAD

**Issue by asyscogithub** [xirixiz/homeassistant-afvalwijzer#168]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

I updated to the latest version and adjusted the changes configuration to:

platform: afvalwijzer
provider: mijnafvalwijzer
postal_code: 9404EV
street_number: 2
default_label: Geen
exclude_pickup_today: false  
exclude_list: 'textiel'  

Now sensor.afvalwijzer_today is saying gtp instead of papier. However sensor.afvalwijzer_papier has the correct date. sensor.afvalwijzer_next_item is unavailable.

### Expected behaviour

The correct values should be displayed.

### Actual behaviour

The wrong values are displayed.

### Version

* HASS version: Core-2021.12.10
* Component version: 2022.01.01
* Useful system info:

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml
I don't think it's needed as the component technically works.

**Comment by niekniek89** [comment]
i have the same issue, see #169

**Comment by xirixiz** [comment]
Hi, yes, stupid mistake of me. Fixed in the new release.
