### ISSUE TITLE
Sensoren werken niet meer bij

### ISSUE THREAD

**Issue by niekniek89** [xirixiz/homeassistant-afvalwijzer#169]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Sinds de laatste HACS update "lijkt" het alsof de sensoren zich niet meer bijwerken.
Voorbeeld:

sensor.afvalwijzer_plastic blijft hangen op 19-01-2022

Echter zijn we nu 2 dagen verder, en zou deze "normaal" de nieuwe datum aan moeten geven.

sensor.afvalwijzer_today blijft hangen op "plastic", terwijl vandaag (21-01) het oud papier wordt opgehaald
Gaat er bij mij iets niet goed
![Schermafbeelding 2022-01-21 om 10 07 36](https://user-images.githubusercontent.com/48858098/150498945-e37bc822-f17b-4d6e-a394-e5b60d4bdd33.png)
![Schermafbeelding 2022-01-21 om 10 07 21](https://user-images.githubusercontent.com/48858098/150498948-8386cc60-b49e-4642-94ea-d461e42d8355.png)
![Schermafbeelding 2022-01-21 om 10 06 16](https://user-images.githubusercontent.com/48858098/150498951-bd7c8ae0-435d-487c-9695-d9ba8e8354de.png)
?

### Expected behaviour

Na afhaaldag zou datum moeten worden bijgewerkt naar de volgende.

### Actual behaviour

Sensoren worden niet geupdated.

### Version

* HASS version: 1.19.3
* Component version: Afvalwijzer versie 2022.01.01
* Useful system info: HassOS 2021.12.10

### HASS logs

Deze heb ik nog niet, zie in HassOS logging geen vreemde zaken.

**Comment by xirixiz** [comment]
Hi, yes, stupid mistake of me. Fixed in the new release.

**Comment by niekniek89** [comment]
thnx voor de snelle fix. hiermee is het inderdaad opgelost.

**Comment by xirixiz** [comment]
Np! Had de datum als een constante opgegeven (komt eigenlijk dan neer op de datum wanneer hass herstart is). Nu wordt bij iedere update de datum opnieuw gezet.

**Comment by jjansen85** [comment]
Top, had er ook last van, na een restart was het weer goed, maar jouw uitleg verklaart waarom dat was ;-)
