### ISSUE TITLE
days unkown, no unique ID

### ISSUE THREAD

**Issue by FritsOV** [xirixiz/homeassistant-afvalwijzer#172]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Hello, i followed the installationsteps as provided at https://github.com/smarthomejunkie/Home-Assistant-Tutorials/tree/master/Afvalwijzer
I get an error on  entity: afvalwijzer_days_until_collection_date
it tells me that it doesn't have an unique ID
therefor i think the days  are unknown 

### Expected behaviour

![20220125_130129](https://user-images.githubusercontent.com/76515350/151020005-672dcd80-0b6e-4a83-b9b3-3cf339a0678a.jpg)

### Actual behaviour

not showing days 
not showing second row

### Version

* HASS version:
* Component version:
* Useful system info:

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

**Comment by xirixiz** [comment]
Hi, this is a bit odd to be honest, as ```afvalwijzer_days_until_collection_date``` doesn't exist anywhere for a long time anymore within the source code 😃.

I believe you should click on Developer Tools in the sidebar and then search for ```sensor.afvalwijzer_```. The sensor you're mentioning has been rebranded a long time ago to for example ```sensor.afvalwijzer_next_in_days```. Once found you can update the enities in your card and then it'll show the correct value(s).

**Comment by FritsOV** [comment]
could you check with rova, 7686CG 
because for example sensor.afvalwijzer_next_in_days  etc.  gives me no State output 

My config yaml is:

##########
# Make sure that customize.yaml is included          
##########
homeassistant:
  customize: !include customize.yaml

##########
# Custom sensors for afvalwijzer          
##########
sensor:
  - platform: afvalwijzer
    provider: rova    # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, rova or afvalstoffendienstkalender
    postal_code: 7686CG                     # (required, default = '')
    street_number:  75                      # (required, default = '')
#   suffix: A                               # (optional, default = '')
#    include_date_today: false               # (optional, default = false) to take or not to take Today into account in the next pickup.
    default_label: Geen
#    id: somestring                          # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS       

  - platform: template
    sensors:
      afvalwijzer_first_next_item_formatted:
        value_template: >-
          {% if is_state('sensor.afvalwijzer_first_next_item', 'gft') %}GFT
          {% elif is_state('sensor.afvalwijzer_first_next_item', 'papier') %}Papier
          {% elif is_state('sensor.afvalwijzer_first_next_item', 'restafval') %}Restafval
          {% endif %}
        friendly_name: 'Next pickup item'
      afvalwijzer_today_formatted:
        value_template: >-
          {% if is_state('sensor.afvalwijzer_today', 'gft') %}GFT
          {% elif is_state('sensor.afvalwijzer_today', 'papier') %}Papier
          {% elif is_state('sensor.afvalwijzer_today', 'restafval') %}Restafval
          {% else %}Geen
          {% endif %}
        friendly_name: 'Vandaag'
      afvalwijzer_tomorrow_formatted:
        value_template: >-
          {% if is_state('sensor.afvalwijzer_tomorrow', 'gft') %}GFT
          {% elif is_state('sensor.afvalwijzer_tomorrow', 'papier') %}Papier
          {% elif is_state('sensor.afvalwijzer_tomorrow', 'restafval') %}Restafval
          {% else %}Geen
          {% endif %}
        friendly_name: 'Morgen'
      today:
        value_template: >-
          {% set months = ["januari", "februari", "maart", "april", "mei", "juni", "juli", "augustus", "september", "oktober", "november", "december"] %}
          {% set month = months[now().strftime('%m') | int -1] %}
          {{ now().strftime('%d') + ' ' + month + ' '+ now().strftime('%Y') }}
     afvalwijzer_days_until_collection_date:
        value_template: >-
          {% set days_until_collection_date = 100 %}
          {% if (state_attr('sensor.afvalwijzer_gft', 'days_until_collection_date') | int < days_until_collection_date) %}
            {% set days_until_collection_date = state_attr('sensor.afvalwijzer_gft', 'days_until_collection_date') %}
          {% endif %}
          {% if (state_attr('sensor.afvalwijzer_papier', 'days_until_collection_date') | int < days_until_collection_date) %}
            {% set days_until_collection_date = state_attr('sensor.afvalwijzer_papier', 'days_until_collection_date') %}
          {% endif %}
          {% if (state_attr('sensor.afvalwijzer_restafval', 'days_until_collection_date') | int < days_until_collection_date) %}
            {% set days_until_collection_date = state_attr('sensor.afvalwijzer_restafval', 'days_until_collection_date') %}
          {% endif %}
          {{ days_until_collection_date }} 
      afvalwijzer_next_icon:
        friendly_name: Icon for next days to pickup
        value_template: >-
          {{ 'mdi:numeric-' + states('sensor.afvalwijzer_next_in_days') + '-box-multiple-outline' }}

**Comment by xirixiz** [comment]
Thanks! Will check!

**Comment by xirixiz** [comment]
The output of the sensor is fine:

```
rova 7686CG


{'pmd': datetime.datetime(2022, 1, 28, 0, 0), 'gft': datetime.datetime(2022, 2, 2, 0, 0), 'restafval': datetime.datetime(2022, 2, 22, 0, 0)}
{'pmd': datetime.datetime(2022, 1, 28, 0, 0), 'gft': datetime.datetime(2022, 2, 2, 0, 0), 'restafval': datetime.datetime(2022, 2, 22, 0, 0)}
{'next_date': datetime.datetime(2022, 1, 28, 0, 0), 'next_in_days': 2, 'next_type': 'pmd', 'today': 'Geen', 'tomorrow': 'Geen', 'day_after_tomorrow': 'pmd'}
['gft', 'pmd', 'restafval']
['day_after_tomorrow', 'next_date', 'next_in_days', 'next_type', 'today', 'tomorrow']
```

However, I`m seeing all sorts of old entries like ```sensor.afvalwijzer_first_next_item``` which don't exist for a long time anymore.
I would just start by adding this:

```
- platform: afvalwijzer
  provider: rova
  postal_code: 7686CG
  street_number: 7
```
and then check whether the default sensors are available matching the data from your provider. From that point you can create a new sensor template based on the names of the default sensors.

**Comment by FritsOV** [comment]
I asked someone else with a working version to test rova.    I think there is the problem. Hé also get unknown etc. But with his own provider there is no problem. Could you check?
  

  

  
  
 Groet en succes met al,  
  
Douwe Bouma
  
  
  
  
  
  
>

**Comment by xirixiz** [comment]
As shown above, the data retrieved from rova for your postal code is correct. I believe you're using an outdated version of this component or the configuration is invalid for use with the current version(s) of HASS and the afvalwijzer component.

**Comment by FritsOV** [comment]
Well i did try it again. 
Deleted all records in config.yaml and uninstalled with hacs afvalverwijdering start over after several refreshes. 

1. after installing with hacs afvalverwijdering 
    - no extra sensor is visibel if i look in configurations -> devises & services -> tab -> entities. 
 2. next step is adding in config,yaml the info like provider etc.  i only filled in my p.code and homenumber and let the provider as is -> mijnafvalwijzer
 result  after configuration check and restart -> no sensors in configuration ->  devises & services -> tab -> entities. 

3. changing the provider to rova in the config.yaml  and restart the PI gives me suddenly one sensor: 
    with name: afvalwijzer next_type, entity ID:  sensor.afvalwijzer_next_type  and  intergration: afvalwijzer.

What happens here?
why can't i get the sensors you mentioned?
