### ISSUE TITLE
sensor.afvalwijzer_next_item is unavailable

### ISSUE THREAD

**Issue by bjkoekkoek** [xirixiz/homeassistant-afvalwijzer#173]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Since the last update the sensor "sensor.afvalwijzer_next_item" is reporting unavailable. Did I miss something and is this removed?

### Expected behaviour

Sensor was always displaying the next item to be collected

### Actual behaviour

Showing unavailable

### Version

core-2021.12.10
supervisor-2022.01.1
Afvalwijzer 2022.01.02

**Comment by xirixiz** [comment]
Yes, this is correct, the sensor has been renamed last release.
```sensor.afvalwijzer_next_type```

**Comment by bjkoekkoek** [comment]
ah missed that, and also the exclude_pickup_today: true :)
