### ISSUE TITLE
Ophaaldata niet juist

### ISSUE THREAD

**Issue by gerbenf1** [xirixiz/homeassistant-afvalwijzer#174]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Bij het invullen haalt ie alle data op.
Maar slaat een heleboel ophaal dagen over.
wij zijn aangesloten bij twentemilieu
Postcode: 7642JH nr5

### Expected behaviour

Graag oplossing voor overslaan data

### Actual behaviour

Bij het invullen haalt ie alle data op.
Maar slaat een heleboel ophaal dagen over.
wij zijn aangesloten bij twentemilieu
Postcode: 7642JH nr5

### Version

* HASS version:
* Component version:
* Useful system info:

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

**Comment by xirixiz** [comment]
Zie het inderdaad. Wat vreemd. Ik ga er vanavond even naar kijken.

**Comment by xirixiz** [comment]
Heb al even gekeken :). Specifiek voor jouw postcode is de data niet gesorteerd. Nou ja, better safe then sorry, dus voor iedereen standaard de datums gesorteerd nu bij het ophalen van de ruwe data.

Nieuwe release is nu beschikbaar: 2022.02.02

**Comment by xirixiz** [comment]
Example output now:

```
-> python3 -m afvalwijzer.test.test_module
[{'type': 'gft', 'date': '2022-02-25'}]
[{'type': 'gft', 'date': '2022-02-25'}, {'type': 'restafval', 'date': '2022-03-11'}]
[{'type': 'gft', 'date': '2022-02-25'}, {'type': 'restafval', 'date': '2022-03-11'}, {'type': 'pmd', 'date': '2022-03-04'}]


{'gft': datetime.datetime(2022, 2, 25, 0, 0), 'restafval': datetime.datetime(2022, 3, 11, 0, 0), 'pmd': datetime.datetime(2022, 3, 4, 0, 0)}
{'gft': datetime.datetime(2022, 2, 25, 0, 0), 'restafval': datetime.datetime(2022, 3, 11, 0, 0), 'pmd': datetime.datetime(2022, 3, 4, 0, 0)}
{'next_date': datetime.datetime(2022, 2, 25, 0, 0), 'next_in_days': 2, 'next_type': 'gft', 'today': 'Geen', 'tomorrow': 'Geen', 'day_after_tomorrow': 'gft'}
['gft', 'pmd', 'restafval']
['day_after_tomorrow', 'next_date', 'next_in_days', 'next_type', 'today', 'tomorrow']

**Comment by gerbenf1** [comment]
Het werkt nu juist.

Bedankt 🙏 

M.v.g Gerben
