### ISSUE TITLE
ics input file instead of API or website scraping. 

### ISSUE THREAD

**Issue by Wolk9** [xirixiz/homeassistant-afvalwijzer#176]
### Request

My garbage collector Circulus-Berkel has no plans whatsoever to provide an API. The information needed is only made available in an iOS or Android App and via a downloadable .ics file. 

It would be nice if the service can be provided with a data file like the .ics file (i have attached an example) for the Circulus Berkel clients. 

Or there must be plans to scrape the information from the website, but that seems to me an uncertain sustainable solution.

### Additional information

[afvalkalender.ics.zip](https://github.com/xirixiz/homeassistant-afvalwijzer/files/8116061/afvalkalender.ics.zip)

**Comment by xirixiz** [comment]
Hi, I believe there are alternative solutions which fits better for your purpouse

For example: https://community.home-assistant.io/t/waste-collection-schedule-framework/186492/20

This component is purely API based and I have no plans to extend it with file support. Sorry :)
