### ISSUE TITLE
Data not available after new update

### ISSUE THREAD

**Issue by Crimby88** [xirixiz/homeassistant-afvalwijzer#179]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Updated the component to 2022.02.03 where Lingewaard should be available. However, all sensors are unavailable.

### Expected behaviour

Without additional configuration, the data should become available as my municipality became available.

### Actual behaviour

No data is available

### Version

* HASS version: 1.23.0
* Component version: 2022.02.03
* Useful system info: RPI4 with SSD

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml
2022-02-28 09:54:46 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration afvalwijzer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by xirixiz** [comment]
Can you please share you configuration. Also plase extend the ticket with some more log details.

**Comment by Crimby88** [comment]
> Can you please share you configuration. Also plase extend the ticket with some more log details.

Sorry, I found this:
Logger: homeassistant.components.sensor
Source: custom_components/afvalwijzer/collector/mijnafvalwijzer.py:80
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 10:09:09 (1 occurrences)
Last logged: 10:09:09

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 71, in async_setup_platform
    collector = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 47, in __init__
    ) = self.get_waste_data_provider()
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 80, in get_waste_data_provider
    json_response["ophaaldagen"]["data"]
KeyError: 'ophaaldagen'

My config:

logger:
  default: info
  logs:
    custom_components.afvalwijzer: debug

sensor:
  - platform: afvalwijzer
    provider: mijnafvalwijzer
    postal_code: !secret postalcode
    street_number: !secret housenumber
    default_label: Geen

**Comment by xirixiz** [comment]
Thanks! What is your postal code so I can verify some things.

**Comment by Crimby88** [comment]
> Thanks! What is your postal code so I can verify some things.

Example: 6681MR, Number 13

**Comment by xirixiz** [comment]
Ah, het adres hoort niet bij mijnafvalwijzer. Graag de juiste provider instellen (mits ondersteund door het custom component natuurlijk) :).

![image](https://user-images.githubusercontent.com/11210639/155960709-59da773d-8a04-4c44-8800-bacaf6c08e2d.png)

**Comment by xirixiz** [comment]
Volgens mij moet je deze collector hebben: lingewaard

**Comment by Crimby88** [comment]
> Volgens mij moet je deze collector hebben: lingewaard

aaah check! heb de provider op lingewaard gezet en het werkt perfect!
