### ISSUE TITLE
Calendar integration

### ISSUE THREAD

**Issue by TheFes** [xirixiz/homeassistant-afvalwijzer#180]
### Request

It would be nice if the integration would create calendar entities, so they will be displayed in the calendar tab.

There is PR created to add this to the Twente Milieu integration, which might be useful to have a look at, if you would also like to integrate this

https://github.com/home-assistant/core/pull/68190

**Comment by xirixiz** [comment]
Sorry, for me it's currenly due to lack of time I`m not able to implement this. I`ll keep it in my mind for the future :).
