### ISSUE TITLE
No module named 'custom_components.afvalwijzer.collector'

### ISSUE THREAD

**Issue by Wo0Zzz** [xirixiz/homeassistant-afvalwijzer#181]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

I added the files to my Custom_components folder, restarted HA. 
Added the config data to my configuration.yaml.
When checking the config with the Validator, it gives me an error:

> Platform error sensor.afvalwijzer - No module named 'custom_components.afvalwijzer.collector' 

So can't get it working

### Expected behaviour

It will pass the Config validator and I can get this thing working in my HA environment

### Actual behaviour

When using the config validator, i'm getting the error:
`Platform error sensor.afvalwijzer - No module named 'custom_components.afvalwijzer.collector'`

### Version

* HASS version: core-2022.3.5
* Component version: 2022.02.03
* Useful system info: HA OS 7.5

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml
Can't pass the validator, so can't add any logs

**Comment by xirixiz** [comment]
Hi, I've tried to replicate this, but I couldn't....

I believe this might be caused by the location of the custom_component. I'd rather advise to install the component via HACS. Could you try that?
