### ISSUE TITLE
afvalstoffendienstkalender gives SSL error

### ISSUE THREAD

**Issue by rdevino** [xirixiz/homeassistant-afvalwijzer#183]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

The integration gave no new data. After a reboot of HASS I found out that there is a SSL error at afvalstoffendienstkalender.nl

### Expected behaviour

Present fresh collection data

### Actual behaviour

collection data was not updated. After changing in const.py the https to http all worked well again

### Version

* HASS version: 2022.2.9
* Component version: 2022.02.3
* Useful system info: Hass core (docker)

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml
[custom_components.afvalwijzer.const.const] Check afvalwijzer platform settings (SSLError(MaxRetryError("HTTPSConnectionPool(host='api.afvalstoffendienstkalender.nl', port=443): Max retries exceeded with url: /webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=5236XR&street=&huisnummer=29&toevoeging=&app_name=afvalwijzer&platform=phone&afvaldata=2022-04-09&langs=nl& (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))")),)

2022-04-09 18:07:18 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 115, in async_setup_platform
    if collector == "":
UnboundLocalError: local variable 'collector' referenced before assignment

**Comment by xirixiz** [comment]
Duplicate: https://github.com/xirixiz/homeassistant-afvalwijzer/issues/182

Een probleem dat bij de provider ligt (SSL certificaat is verlopen).
https://api.afvalstoffendienstkalender.nl/

**Comment by joostvkempen** [comment]
het rare is: als je naar afvalstoffendienstkalender.nl gaat, dan is daar gewoon een geldig certificaat aanwezig (net vernieuwd) en dat is een wildcard-certificaat. Kan iemand mij uitleggen hoe het dan kan dat er met api ervoor toch een ongeldig certificaat wordt getoond? Die wildcard geldt toch ook voor api. ? Dat lost dit issue niet op, maar ben gewoon nieuwsgierig ;-)

![image](https://user-images.githubusercontent.com/37901988/162635101-698e1615-ef05-462a-8d25-e7ec8476d289.png)

**Comment by xirixiz** [comment]
Zoals je kan zien is het certificaat op tijd vervangen voor www.afvalstoffendienstkalender.nl. Het certificaat kan, en wordt helaas vaak, op verschillende plekken geinstalleerd. Bijvoorbeeld omdat iedere webapplicatie een eigen webservice heeft. Ondanks het certificaat gebruikt kan worden voor api.afvalstoffendienstkalender.nl, is er voor die specifieke service/applicate het certificaat niet vervangen, daar wordt nog steeds het verlopen wildcard certificaat gebruikt.

Voorbeeld. Zie het als twee huizen naast elkaar in een straat die afvalstoffendienstkalender.nl heet. Het ene huis heeft als "huisnummer" www en het andere huis api. Het "huisnummer" www heeft netjes een nieuw certificaat in de bus gekregen, maar het "huisnummer" met api heeft dat nog niet. Het huis api mag wel het certificaat van www gebruiken omdat de huizen immers in dezelfde straat staan, maar api moet in dit geval wel een eigen exemplaar in de bus krijgen.

Er zijn wat voor- en nadelen voor de verschillende implementaties die er mogelijk zijn vwb SSL certificaten. Van 1 van die nadelen is dit een goed voorbeeld van, dat men certificaten vergeet te vervangen of niet op alle plekken vervangt. Overigens is het wel bijzonder dat dit soort dingen anno 2022 nog voorkomen. 

Ik hoop dat je het een beetje meer duidelijkheid verschaft :).

**Comment by KrijnErmerins** [comment]
Heb dit probleem ook lokaal ('s-Hertogenbosch) gemeld. Hopelijk wordt het snel opgepakt!

**Comment by joostvkempen** [comment]
> Heb dit probleem ook lokaal ('s-Hertogenbosch) gemeld. Hopelijk wordt het snel opgepakt!

Ik werk daar zelfs (afdeling ICT gemeente 's-Hertogenbosch), maar deze site (en app en api) zijn volledig uitbesteed en worden ingekocht als een dienst (service) en 'branded' als Afvalstoffendienst (wat eigenlijk een afdeling is van gemeente 's-Hertogenbosch). Dus ik verwacht dat mijn collega's hem 1 op 1 doorsturen naar de leverancier ;-)

**Comment by KrijnErmerins** [comment]
Zo te zien is het opgelost!

**Comment by xirixiz** [comment]
Yes, idd opgelost!

**Comment by warptozero** [comment]
It's happening again, looks like they haven't fixed it permanently.
