### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by emile-bodin** [xirixiz/homeassistant-afvalwijzer#186]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Installed afvallwijzer via HACS, maar faalt bij installatie van de sensoren
Meerdere malen HASS geherstart, en afvalwijzer geherinstalleerd.

### Expected behaviour

correct install

### Actual behaviour

Install faalt

### Version

Home Assistant Core 2022.5.4
Home Assistant Supervisor 2022.05.3
afvalwijzer: 2022.05.01

- platform: afvalwijzer
  provider: meerlanden
  postal_code: 2121xt
  street_number: 40
  suffix: ""
  exclude_pickup_today: true
  default_label: Geen
  id: ""
  exclude_list: ""

### HASS logs

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 99, in async_setup_platform
    collector = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/collector/ximmio.py", line 49, in __init__
    ) = self.get_waste_data_provider()
  File "/config/custom_components/afvalwijzer/collector/ximmio.py", line 73, in get_waste_data_provider
    uniqueId = raw_response.json()["dataList"][0]["UniqueId"]
TypeError: 'NoneType' object is not subscriptable

**Comment by xirixiz** [comment]
Hi, I`ll be looking into this Tonight.

**Comment by xirixiz** [comment]
Het geeft inderdaad een probleem. Het vreemde is dat wanneer ik postcode 2201XZ gebruik met een willekeurig huisnummer, dat het dan wel gewoon naar behoren werkt. Het lijkt op een issue bij de provider, maar ik zoek het nog even verder uit.

**Comment by xirixiz** [comment]
Kan het zijn dat je misschien in een vrij nieuwe wijk woont?

```
-> curl -k -s -X POST https://wasteprod2api.ximmio.com/api/FetchAdress -H 'Content-Type: application/json' -d "{'postCode': '2201XZ', 'houseNumber': '40', 'companyCode': '800bf8d7-6dd1-4490-ba9d-b419d6dc8a45'}"

{"userMessage":{"type":null,"messageCode":0,"description":null},"ExtraOption":{"$type":"System.Dynamic.ExpandoObject, System.Core"},"dataList":[{"ID":0,"UniqueId":"3000194030","Street":"Strandloper","HouseNumber":"40","HouseLetter":"","HouseNumberIndication":"","HouseNumberAddition":"","ZipCode":"2201XZ","City":"Noordwijk","Community":"Noordwijk","AddressType":"","Floor":null,"AddressUniqueId":0,"AddressUnique":null,"CommercialNumber":null,"LocationName":null,"Latitude":null,"Longitude":null,"RelativeName":null,"AddressProp":null,"PostCode":null,"Plaatsnaam":null}],"intDataList":null,"data":null,"status":true,"messageCode":107,"pdfResponse":null,"token":null,"ID":null,"invalidParameters":null,"total":0,"messageToString":null}
```

```
-> curl -k -s -X POST https://wasteprod2api.ximmio.com/api/FetchAdress -H 'Content-Type: application/json' -d "{'postCode': '2201XT', 'houseNumber': '40', 'companyCode': '800bf8d7-6dd1-4490-ba9d-b419d6dc8a45'}"

{"userMessage":{"type":null,"messageCode":0,"description":null},"ExtraOption":{"$type":"System.Dynamic.ExpandoObject, System.Core"},"dataList":null,"intDataList":null,"data":null,"status":false,"messageCode":164,"pdfResponse":null,"token":null,"ID":null,"invalidParameters":null,"total":0,"messageToString":null}
```

**Comment by xirixiz** [comment]
Yes, het is duidelijk iets met jouw adres icm meerlanden:
https://inzamelkalender.meerlanden.nl/modules/800bf8d7-6dd1-4490-ba9d-b419d6dc8a45/kalender/

Daar krijg ik namelijk ook de melding dat het adres onbekend is.

**Comment by emile-bodin** [comment]
dat is vreemd, mij doet de kalender het wel
https://inzamelkalender.meerlanden.nl/modules/800bf8d7-6dd1-4490-ba9d-b419d6dc8a45/kalender/calendar.html?1000001313&Beatrixplein---40%20%20%20---2121XT---Bennebroek---Bloemendaal

![image](https://user-images.githubusercontent.com/2363359/170465661-0c55a788-d8f4-4ad0-ab2f-872291ff9986.png)

**Comment by emile-bodin** [comment]
Ik zie dat je de verkeerde postcode gebruikt in de CURL call.

De juiste postcode werkt;

--> curl -k -s -X POST https://wasteprod2api.ximmio.com/api/FetchAdress -H 'Content-Type: application/json' -d "{'postCode': '**2121XT**', 'houseNumber': '40', 'companyCode': '800bf8d7-6dd1-4490-ba9d-b419d6dc8a45'}"

{"userMessage":{"type":null,"messageCode":0,"description":null},"ExtraOption":{"$type":"System.Dynamic.ExpandoObject, System.Core"},"dataList":[{"ID":0,"UniqueId":"1000001313","Street":"Beatrixplein","HouseNumber":"40","HouseLetter":"","HouseNumberIndication":"","HouseNumberAddition":"","ZipCode":"2121XT","City":"Bennebroek","Community":"Bloemendaal","AddressType":"","Floor":null,"AddressUniqueId":0,"AddressUnique":null,"CommercialNumber":null,"LocationName":null,"Latitude":null,"Longitude":null,"RelativeName":null,"AddressProp":null,"PostCode":null,"Plaatsnaam":null}],"intDataList":null,"data":null,"status":true,"messageCode":107,"pdfResponse":null,"token":null,"ID":null,"invalidParameters":null,"total":0,"messageToString":null}

**Comment by emile-bodin** [comment]
Schijnbaar is de postcode case sensitive.
Op de website van meerlanden wordt dit automatisch verandered naar hoofdletters.
Als ik de curl call doe met kleine letters fallt de call.

curl -k -s -X POST https://wasteprod2api.ximmio.com/api/FetchAdress -H 'Content-Type: application/json' -d "{'postCode': '2201xt', 'houseNumber': '40', 'companyCode': '800bf8d7-6dd1-4490-ba9d-b419d6dc8a45'}"

{"userMessage":{"type":null,"messageCode":0,"description":null},"ExtraOption":{"$type":"System.Dynamic.ExpandoObject, System.Core"},"dataList":null,"intDataList":null,"data":null,"status":false,"messageCode":164,"pdfResponse":null,"token":null,"ID":null,"invalidParameters":null,"total":0,"messageToString":null}

Na de config te hebben aangepast naar hoodletters werkt het!

platform: afvalwijzer
provider: meerlanden
postal_code: 2121XT
street_number: 40
suffix: ""
exclude_pickup_today: true
default_label: Geen
id: ""
exclude_list: ""


2022-05-26 12:10:09 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Generating state via AfvalwijzerCustomSensor for = gft with value 2022-06-03
2022-05-26 12:10:09 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Generating state via AfvalwijzerCustomSensor for = papier with value 2022-06-04
2022-05-26 12:10:09 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Generating state via AfvalwijzerCustomSensor for = pmd with value 2022-05-31
2022-05-26 12:10:09 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Generating state via AfvalwijzerCustomSensor for = restafval with value 2022-06-08
2022-05-26 12:10:09 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Generating state via AfvalwijzerCustomSensor for = takken with value 2022-11-17
2022-05-26 12:10:09 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Generating state via AfvalwijzerCustomSensor for = day_after_tomorrow with value Geen
2022-05-26 12:10:09 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Generating state via AfvalwijzerCustomSensor for = next_date with value 2022-05-31
2022-05-26 12:10:09 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Generating state via AfvalwijzerCustomSensor for = next_in_days with value 5
2022-05-26 12:10:09 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Generating state via AfvalwijzerCustomSensor for = next_type with value pmd
2022-05-26 12:10:09 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Generating state via AfvalwijzerCustomSensor for = today with value Geen
2022-05-26 12:10:09 DEBUG (MainThread) [custom_components.afvalwijzer.const.const] Generating state via AfvalwijzerCustomSensor for = tomorrow with value Geen

**Comment by xirixiz** [comment]
Duidelijk! Dan pas ik de code aan dat de postcode altijd in uppercasre staat. Neem ik mee in de volgende release.

**Comment by xirixiz** [comment]
https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/2022.05.02

**Comment by barrymossel** [comment]
Deze update maakt voor mij de integratie kapot:

`Invalid config for [sensor.afvalwijzer]: [postal_code] is an invalid option for [sensor.afvalwijzer]. Check: sensor.afvalwijzer->postal_code. (See /config/configuration.yaml, line 379). Please check the docs at https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/README.md`

**Comment by Mariusthvdb** [comment]
right. and downloading the former version and restarting throws this:

```
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Invalid config for [sensor.afvalwijzer]: [postal_code] is an invalid option for [sensor.afvalwijzer]. Check: sensor.afvalwijzer->postal_code. (See ?, line ?). 
```

so, remove the integration config, restart and add it back again..

**Comment by Mariusthvdb** [comment]
pulling the plug is the worst thing you can do..... and shouldn't be in any integrations advise to update.

anyways, the fix is live and we can again see when the garbage is picked up.

**Comment by barrymossel** [comment]
> 

For me "pulling the plug" was rebooting through ProxMox...
