### ISSUE TITLE
Error "[postal_code] is an invalid option for [sensor.afvalwijzer]" after update to 2022.05.02

### ISSUE THREAD

**Issue by bscheutjens** [xirixiz/homeassistant-afvalwijzer#187]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

I've just updated this integration to version 2022.05.02 and after restarting HA I'm getting an error:

Logger: homeassistant.config
Source: config.py:454
First occurred: 14:13:27 (1 occurrences)
Last logged: 14:13:27

Invalid config for [sensor.afvalwijzer]: [postal_code] is an invalid option for [sensor.afvalwijzer]. Check: sensor.afvalwijzer->postal_code. (See /config/components/sensor/afvalwijzer.yaml, line 0). Please check the docs at https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/README.md

### Expected behaviour

That it works after updating 

### Actual behaviour

After updating and restaring HA I get an error

### Version

* Home Assistant Core 2022.5.5
* Home Assistant Supervisor 2022.05.3
* Home Assistant OS 8.1
* Component version: 2022.05.02

### HASS logs

Logger: homeassistant.config
Source: config.py:454
First occurred: 14:13:27 (1 occurrences)
Last logged: 14:13:27

Invalid config for [sensor.afvalwijzer]: [postal_code] is an invalid option for [sensor.afvalwijzer]. Check: sensor.afvalwijzer->postal_code. (See /config/components/sensor/afvalwijzer.yaml, line 0). Please check the docs at https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/README.md

**Comment by mvdwetering** [comment]
I think this change means that it now expects the option to be in uppercase (so `POSTAL_CODE` iso `postal_code`) instead of the value which was probably intended.

```
vol.Required(CONF_POSTAL_CODE.strip().upper(), default="1234AB"): cv.string,
```

**Comment by xirixiz** [comment]
Working on it.

**Comment by bscheutjens** [comment]
> Working on it. Happens when you quickly try to fix something 😄

Been there, done that ;)

**Comment by xirixiz** [comment]
Rollback done. It's a problem of numeric and string value mixed. Will check this later.
