### ISSUE TITLE
New types of garbage

### ISSUE THREAD

**Issue by Luitdesign** [xirixiz/homeassistant-afvalwijzer#188]
### Request

In our region we have two new types of garbage which aren't recognized yet.
1. Gft in emmers wordt ingezameld in compacte wijken van de stad. Op deze manier kunnen inwoners van deze wijken ook groente-, fruit- en tuinafval scheiden. 
2. Pmd in zakken

### Additional information

For example this adres
https://inzamelkalender.rova.nl/nl/8022PA/27/

**Comment by xirixiz** [comment]
Check ik even

**Comment by xirixiz** [comment]
The output is showing the dates just fine (well, the same as is provided by Rova). It seems Rova still needs to do some modifications as via the api they are using plastig as gft in emmers.

```
{'plastic': datetime.datetime(2022, 6, 9, 0, 0), 'gft': datetime.datetime(2022, 6, 10, 0, 0), 'md': datetime.datetime(2022, 6, 14, 0, 0), 'papier': datetime.datetime(2022, 6, 17, 0, 0)}
{'plastic': datetime.datetime(2022, 6, 9, 0, 0), 'gft': datetime.datetime(2022, 6, 10, 0, 0), 'md': datetime.datetime(2022, 6, 14, 0, 0), 'papier': datetime.datetime(2022, 6, 17, 0, 0)}
{'next_date': datetime.datetime(2022, 6, 9, 0, 0), 'next_in_days': 4, 'next_type': 'plastic', 'today': 'Geen', 'tomorrow': 'Geen', 'day_after_tomorrow': 'Geen'}
['gft', 'md', 'papier', 'plastic']
['day_after_tomorrow', 'next_date', 'next_in_days', 'next_type', 'today', 'tomorrow']
```

**Comment by Luitdesign** [comment]
I sent the issue to Rova hopefully they will fix it. 
Thanks for lookng into it

**Comment by xirixiz** [comment]
Hopefully, they are not the faster changing/replying company out there :)

**Comment by Luitdesign** [comment]
Is it possible to add those new data types ? Or is there still something wrong on the rova side ?

**Comment by xirixiz** [comment]
The data types are still incorrect at the api side. Best thing todo is to contact the provider. Closing this ticket as I cannot provide any support here. Sorry.

**Comment by Luitdesign** [comment]
Maybe I miss understand but there is a data type GFTE instead of GFT that's look like  a new one ?
