### ISSUE TITLE
Nijmegen / DAR no info since two days

### ISSUE THREAD

**Issue by markblokpoel** [xirixiz/homeassistant-afvalwijzer#192]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Since a day or two afvalinfo cannot get information from dar.nl. The website is still online: https://afvalkalender.dar.nl/

### Expected behaviour

Retrieve the afval information from dar.nl gemeente Nijmegen.

### Actual behaviour

No data is retrieved and the following error is present in the logs.

### Version

* HASS version: core-2022.6.0
* Component version: v1.0.7
* Useful system info: Running in docker.

### HASS logs

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.afvalinfo.const.const
Source: custom_components/afvalinfo/location/trashapi.py:75
Integration: afvalinfo (documentation, issues)
First occurred: 11:35:45 (1 occurrences)
Last logged: 11:35:45

Error occurred. Please check the address with postcode: '6536GK' and huisnummer: '3226''' on the website of your local waste collector in the gemeente: 'nijmegen'. It's probably a faulty address or the website of the waste collector is unreachable. If the address is working on the website of the local waste collector and this error still occured, please report the issue in the Github repository https://github.com/heyajohnny/afvalinfo with details of the location that isn't working
```

**Comment by xirixiz** [comment]
Het lijkt erop dat je een ander component gebruikt. Ik zie namelijk dit: https://github.com/heyajohnny/afvalinfo.
Graag daar even het issue aanmaken :).
