### ISSUE TITLE
request for DeAfvalapp

### ISSUE THREAD

**Issue by scannie67** [xirixiz/homeassistant-afvalwijzer#193]
### Request

I'm missing the DeAfvalapp. 
This is the information for Echt-Susteren and Helmond.
Is it possible to add it?

Many thanks in advance.
Peter.

**Comment by xirixiz** [comment]
Hi Peter, yeah should be possible :). I`ll have a look this week.

**Comment by xirixiz** [comment]
Do you have a postal code for me which is valid to use?

**Comment by xirixiz** [comment]
Maybe you could use https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer in the meantime, which already supports this provider.

**Comment by scannie67** [comment]
Hello Bram,

Do you have an update?

**Comment by scannie67** [comment]
Hi Bram,

That would be great!
Thanks. 

Peter.

**Comment by xirixiz** [comment]
Hi, yes, I've been working on it but didn't have much time the last couple of months. Will intergrate this soon (approx next month).

**Comment by xirixiz** [comment]
Hi, a bit sooner than expected, but the development branch contains support for deafvalapp!

Output example based on the sample postal code. If you don't understand this, don't worry, this is the input data to create the sensors in HASS and is valid data to create sensors with this custom component. 

Please validate if this is working properly. If so, I`ll commit it to the master branch and draft a new release.

```
{'restafval': datetime.datetime(2022, 11, 14, 0, 0), 'gft': datetime.datetime(2022, 10, 24, 0, 0), 'pmd': datetime.datetime(2022, 11, 1, 0, 0), 'snoeiafval': datetime.datetime(2022, 11, 1, 0, 0), 'kerstboom': 'Geen'}
{'restafval': datetime.datetime(2022, 11, 14, 0, 0), 'gft': datetime.datetime(2022, 10, 24, 0, 0), 'pmd': datetime.datetime(2022, 11, 1, 0, 0), 'snoeiafval': datetime.datetime(2022, 11, 1, 0, 0), 'kerstboom': 'Geen'}
{'next_date': datetime.datetime(2022, 10, 24, 0, 0), 'next_in_days': 1, 'next_type': 'gft', 'today': 'Geen', 'tomorrow': 'gft', 'day_after_tomorrow': 'Geen'}
['gft', 'kerstboom', 'pmd', 'restafval', 'snoeiafval']
['day_after_tomorrow', 'next_date', 'next_in_days', 'next_type', 'today', 'tomorrow']
```

**Comment by xirixiz** [comment]
Ik heb het zelf even getest en alles werkt naar behoren. Ik heb release 2022.10.06 aangemaakt met support voor deafvalapp.

**Comment by scannie67** [comment]
Hallo Bram,Dank je voor het support!!Ik ga het vanavond installeren en proberen. Gr. Peter. Op 23 okt. 2022 om 09:24 heeft Bram van Dartel ***@***.***> het volgende geschreven:﻿
Ik heb het zelf even getest en alles werkt naar behoren. Ik heb release 2022.10.06 aangemaakt met support voor deafvalapp.
