### ISSUE TITLE
Error when loading

### ISSUE THREAD

**Issue by joeblack2k** [xirixiz/homeassistant-afvalwijzer#194]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Hey! 

i'm getting this error:

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 75, in async_setup_platform
    collector = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 47, in __init__
    ) = self.get_waste_data_provider()
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 80, in get_waste_data_provider
    json_response["ophaaldagen"]["data"]
KeyError: 'ophaaldagen'

this is my config:

sensor:
    - platform: afvalwijzer
      provider: mijnafvalwijzer        # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, afvalstoffendienstkalender or rova
      postal_code: 2264JV              # (required, default = '')
      street_number: 72               # (required, default = '')
      suffix: ''                       # (optional, default = '')
      exclude_pickup_today: true       # (optional, default = true) to take or not to take Today into account in the next pickup.
      default_label: Geen              # (optional, default = Geen) label if no date found
      id: ''                           # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
      exclude_list: '' 

### Expected behaviour

Working

### Actual behaviour

Not Working

### Version

* HASS version: Latest 
* Component version: Latest
* Useful system info:

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

**Comment by xirixiz** [comment]
Hi, the address isn't supported by mijnafvalwijzer.nl. Most probably you need to define a different provider for your commune.

"Uw adres is niet bekend bij ons. Neem contact op met uw gemeente."

**Comment by xirixiz** [comment]
as provider set avalex and things will work (verified it ;))

**Comment by joeblack2k** [comment]
Nice! thanks!!!
