### ISSUE TITLE
Request for mijnafvalzaken.nl

### ISSUE THREAD

**Issue by edgarveersel** [xirixiz/homeassistant-afvalwijzer#196]
### Request

Per 1 Juli 2022, my municipality has switched to the MijnAfvalzaken app. This is for Castricum, Heiloo and Uitgeest.

Would it be possible to add that provider too? 
Thanks and kind regards,
Edgar

### Additional information

https://mijnafvalzaken.nl/

**Comment by xirixiz** [comment]
Do you have a postal code for me which is valid to use?

**Comment by sand3rk** [comment]
1906KD 1

**Comment by xirixiz** [comment]
They don't have an api afaik, but I've contacted the klantenservice. Let's wait for their reply.

**Comment by edgarveersel** [comment]
Thanks! Let's see if they have an API.


In case they indeed don't have an API: in the mean time I have found an alternative solution by using the 'add to calendar' (webcal) link and the ICS integration from HACS.

(Still I'd prefer the afvalwijzer integration, btw.  :-) )

**Comment by OdinMegan** [comment]
1704XB 9 is not working

**Comment by xirixiz** [comment]
Unfortunatly an API isn't available, and I didn't receive any respons. Sorry to tell, but I`m closing this issue...

**Comment by sand3rk** [comment]
[Other plugin](https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/issues/397) added mijnafvalzaken. Can you try again to add support for mijnafvalzaken?

**Comment by xirixiz** [comment]
Sure, the logic is easy to adopt. Maybe I`ll be able to add this Today or Tomorrow.

**Comment by sand3rk** [comment]
Did you manage to adopt mijnafvalzaken?
