### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by jayaarts** [xirixiz/homeassistant-afvalwijzer#197]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Hi,

I've added via HACS and placed the example configuration in sensor.py. Problem is; not entities/sensors are created.

### Expected behaviour

Creation of sensors.

### Actual behaviour

Nothing

### Version

* HASS version: Latest
* Component version: Latest
* Useful system info:

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

**Comment by rotilho** [comment]
Shouldn't you add it to configuration.yaml instead?

**Comment by xirixiz** [comment]
Correct. Please fpllow the instructions in the README.
