### ISSUE TITLE
Code to make the formatted sensors doesn't t work.

### ISSUE THREAD

**Issue by Tom-Bon92** [xirixiz/homeassistant-afvalwijzer#198]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Hi, I use for a example this code for the Next pickup item
`      afvalwijzer_next_item_formatted:
        value_template: >-
          {% if is_state('sensor.afvalwijzer_next_type', 'keukenafval,') %}keukenafval
          {% elif is_state('sensor.afvalwijzer_next_type', 'papier,') %}Papier
          {% elif is_state('sensor.afvalwijzer_next_type', 'pmd,') %}PMD
          {% elif is_state('sensor.afvalwijzer_next_type', 'restafval,') %}Restafval
          {% elif is_state('sensor.afvalwijzer_next_type', 'metaal,') %}Metaal
          {% else %}Geen
          {% endif %}
        friendly_name: "Next pickup item"`

I tried it on the home assistante help pages --> sjabloon and it's work fast.
To day would there "keukenafval, restafval, pmd" stay.
But the code doesn't search for individual words. Wenn I changed 'keukenafval' to 'keukenafval, restafval, pmd' then the sensor output from "Next pickup item". is "keukenafval".

### Expected behaviour

Sensor Output gives te right output

### Actual behaviour

Sensor doesn't search the word. So give output "geen" 

### Version

* HASS version: 2022.8.6
* Component version: 2022.06.02
* Useful system info:
* ## System Information

version | core-2022.8.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.32-v8
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4870
Installed Version | 1.25.5
Stage | running
Available Repositories | 1093
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.08.3
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 59.0 GB
disk_used | 14.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.0), File editor (5.3.3), Samba share (10.0.0), Check Home Assistant configuration (3.11.0), Home Assistant Google Drive Backup (0.108.3), WireGuard (0.7.0), Z-Wave JS to MQTT (0.45.0), Z-Wave JS (0.1.65)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 6
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 10 augustus 2022 om 18:11
-- | --
current_recorder_run | 20 augustus 2022 om 09:46
estimated_db_size | 1301.85 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

**Comment by xirixiz** [comment]
Hi, formatting is more related to personal preferences. It's best to post this on the hass forum.
https://community.home-assistant.io/
