### ISSUE TITLE
error in sensors after updating HAS

### ISSUE THREAD

**Issue by FritsOV** [xirixiz/homeassistant-afvalwijzer#200]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

After updating HAS i am getting two errors in the update for sensors and in the custom_components.afvalwijzer.const.const

### Expected behaviour

before the update all worked great. Now i am getting the mentioned errors

### Actual behaviour

despite the errors i cant see what exactly is changed in behaviour.  My guess is that the behaviourchange will ocour if the date of garbagecollection isn't in the future anymore. 

### Version

Home Assistant 2022.9.5
Supervisor 2022.09.1
Operating System 9.0
Frontend-versie: 20220907.2 - latest

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

LOG: 1
Logger: custom_components.afvalwijzer.const.const
Source: custom_components/afvalwijzer/sensor.py:237
Integration: afvalwijzer (documentation, issues)
First occurred: 24 september 2022 om 21:23:59 (135 occurrences)
Last logged: 11:28:01

Check afvalwijzer platform settings (SSLError(MaxRetryError("HTTPSConnectionPool(host='api.inzamelkalender.rova.nl', port=443): Max retries exceeded with url: /webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=XXXXXX&street=&huisnummer=XX&toevoeging=&app_name=afvalwijzer&platform=phone&afvaldata=2022-09-24&langs=nl& (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))")),)
Check afvalwijzer platform settings (SSLError(MaxRetryError("HTTPSConnectionPool(host='api.inzamelkalender.rova.nl', port=443): Max retries exceeded with url: /webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=7686CG&street=&huisnummer=75&toevoeging=&app_name=afvalwijzer&platform=phone&afvaldata=2022-09-25&langs=nl& (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))")),)

LOG 2:
Logger: homeassistant.helpers.entity
Source: custom_components/afvalwijzer/sensor.py:241
Integration: afvalwijzer (documentation, issues)
First occurred: 24 september 2022 om 21:23:59 (135 occurrences)
Last logged: 11:28:01

Update for sensor.afvalwijzer_next_date fails
Update for sensor.afvalwijzer_next_in_days fails
Update for sensor.afvalwijzer_next_type fails
Update for sensor.afvalwijzer_today fails
Update for sensor.afvalwijzer_tomorrow fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_device_update
    raise exc
  File "/config/custom_components/afvalwijzer/sensor_provider.py", line 86, in async_update
    await self.hass.async_add_executor_job(self.fetch_data.update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/afvalwijzer/sensor.py", line 241, in update
    self.waste_data_with_today = collector.waste_data_with_today
UnboundLocalError: local variable 'collector' referenced before assignment

**Comment by xirixiz** [comment]
Hi, it seems to be an error at the provider. 

Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired 

The certificate seems to be expired for the https api connection.

**Comment by Constant-Vathorst** [comment]
Same issue as of today or yesterday.
Tried to switch provider (from Rova to mijnafvalwijzer) but made no difference.

**Comment by vincentnk** [comment]
Same issue with Rova collector here.




@FritsOV fyi, je adres staat in je logs, misschien even er uit editen..

**Comment by skipper79** [comment]
See here

**Comment by scorpinus** [comment]
Same issue here, seems the SSL certificate of the domain has expired.

**Comment by xirixiz** [comment]
@scorpinus yes, this is what I've posted as well indeed. The SSL certificate is expired. The only thing left is waiting for the remote party to update their SSL cert.

**Comment by xirixiz** [comment]
The issue is definatly the SSL certifacte:
![image](https://user-images.githubusercontent.com/11210639/192209719-4ee80941-8e66-4af8-a968-8fc68c64054f.png)

Expiration date for URL: api.inzamelkalender.rova.nl 

However, @Constant-Vathorst, in this case inzamelkalender.rova.nl is using the same certificate, only it has been replaced by a new one. The forgot to update another webserver with this new certificate so it seems :).

![image](https://user-images.githubusercontent.com/11210639/192210039-1eeeaa37-9e3b-4f96-b6a4-94e0d7754ff6.png)

**Comment by FritsOV** [comment]
> Same issue with Rova collector here.
> 
> @FritsOV fyi, je adres staat in je logs, misschien even er uit editen..

Dank je! gecorrigeerd...
