### ISSUE TITLE
Afvalwijzer stopped updating, error in log: `KeyError: 'ophaaldagen'`

### ISSUE THREAD

**Issue by hapklaar** [xirixiz/homeassistant-afvalwijzer#201]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Afvalwijzer stopped updating in HA

### Expected behaviour

Sensor being updated

### Actual behaviour

sensor is unavailable, getting below error in log

### Version

* HASS version: latest
* Component version: 2022.06
* Useful system info:
Removed, then reinstalled the add-on, made no difference.

My configuration.yaml part:

```
  - platform: afvalwijzer
    provider: mijnafvalwijzer        # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, afvalstoffendienstkalender or rova
    postal_code: 0000AA              # (required, default = '') == redacted
    street_number: 43                # (required, default = '')
    suffix: ''                       # (optional, default = '')
    default_label: Geen              # (optional, default = Geen) label if no date found
    id: ''                           # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
    exclude_list: ''                 # (optional, default = '') comma separated list of wast types (case ignored). F.e. "papier, gft"
```

### HASS logs

```
2022-10-17 21:13:36.244 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 75, in async_setup_platform
    collector = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 47, in __init__
    ) = self.get_waste_data_provider()
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 80, in get_waste_data_provider
    json_response["ophaaldagen"]["data"]
KeyError: 'ophaaldagen'
```

**Comment by hapklaar** [comment]
PS just saw in previous issue reports that this error has been present for years, so it might not be indicative for the cause...

**Comment by xirixiz** [comment]
It looks like data is unavailable from the provider currently. Do you have a dummy address (postal code + street number) for me to do some testing?

**Comment by hapklaar** [comment]
Sure, for example https://www.mijnafvalwijzer.nl/nl/9726BA/11/

My postcode+number also still shows normal data on the mijnafvalwijzer website.

**Comment by DanielsWrath** [comment]
I've got the same problem, so it seems. Also in Groningen

**Comment by Caros2017** [comment]
Same issue here

**Comment by xirixiz** [comment]
Wasn't able to check it yet, but will do so Today

**Comment by xirixiz** [comment]
Het zit inderdaad aan de kant van de provider. Er is geen data beschikbaar.

https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=9726BA&street=&huisnummer=11&toevoeging=&app_name=afvalwijzer&platform=phone&afvaldata=2022-10-19&langs=nl&

**Comment by DanielsWrath** [comment]
Hoe kom je uberhaubt bij een api key bij de afvalwijzer? Ik kan geen woord vinden over deze service op hun website of google. Behalve als het gerelateerd is aan HA

**Comment by xirixiz** [comment]
Een beetje reverse engineering 😉. Het wordt gedoogd momenteel...

**Comment by hapklaar** [comment]
Let me guess... de api key van de afvalwijzer app? ;-)

**Comment by xirixiz** [comment]
...en een beetje hulp van iemand :)

**Comment by DanielsWrath** [comment]
@xirixiz Volgens mij werkt het wel als je `platform=phone` verandert naar `platform=web`

[phone](https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=9726BA&street=&huisnummer=11&toevoeging=&app_name=afvalwijzer&platform=phone&afvaldata=2022-10-19&langs=nl&)

[web](https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=9726BA&street=&huisnummer=11&toevoeging=&app_name=afvalwijzer&platform=web&afvaldata=2022-10-19&langs=nl&)

**Comment by xirixiz** [comment]
Versie nog even bijgewerkt en nu een nieuwe uitgebracht. Updaten en testen maar! Goed gevonden, maar wel slecht aan de kant van de provider....

**Comment by hapklaar** [comment]
Na updaten werkt ie hier ook weer. Thanks @xirixiz !

**Comment by xirixiz** [comment]
In this case I will also look into better (more clear) error handling. As the "phone" entry is not working it's good to do some testing with that url, saves me some time creating dummy data :)
