### ISSUE TITLE
Afvalwijzer all sensor unavailable 

### ISSUE THREAD

**Issue by GesturV** [xirixiz/homeassistant-afvalwijzer#205]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Afvalwijzer integration does not seem to load, and all sensors show "unavailable". Integration does show up in HACS and can update. Updated several times in the last month, but still nothing helps. Removing all files from the custom_components/afvalwijzer and copying in the new files does also not help.

### Expected behaviour

Sensors show a state, but they don't

### Actual behaviour

Everything was working just fine, but all afvalwijzer sensors now report "unavailable"  and info states "This entity is no longer being provided by the afvalwijzer integration." 

### Version

 Home Assistant 2022.10.5 Supervisor 2022.10.0 Operating System 9.3 Frontend 20221010.0 - latest 

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml
[home-assistant.log](https://github.com/xirixiz/homeassistant-afvalwijzer/files/9909672/home-assistant.log)

**Comment by xirixiz** [comment]
Hi, did you upgrade to the latest release of afvalwijzer? In the logfiles I don't see anything about afvalwijzer besides HASS recognizes the component.

Are you using the latest release: 2022.11.02?

What does you configuration look lijk (postal_code, provider)?

**Comment by GesturV** [comment]
Thanks Xirixiz,

Yes I agree that it is strange. I am on 11.02. Config did not changes since it is working (should not have) and looks like (house number blurred) (provider is I think suez but worked through afvalwijzer, at leat Afvalwijzer app on android/iOS gives me info)

logger:
  default: info
  logs:
    custom_components.afvalwijzer: debug

sensor:
  - platform: afvalwijzer
    provider: mijnafvalwijzer        # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, afvalstoffendienstkalender or rova
    postal_code: 3721AL              # (required, default = '')
    street_number:  xx                # (required, default = '')
    suffix: ''                       # (optional, default = '')
    exclude_pickup_today: true       # (optional, default = true) to take or not to take Today into account in the next pickup.
    default_label: Geen              # (optional, default = Geen) label if no date found
    id: ''                           # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
    exclude_list: ''                 # (optional, default = '') comma separated list of wast types (case ignored). F.e. "papier, gft"

**Comment by GesturV** [comment]
eh.. formatting from the configuration suffers from automated formatting error. It is 

logger:
  default: info
  logs:
    custom_components.afvalwijzer: debug

sensor:
  - platform: afvalwijzer
    provider.... etc

**Comment by GesturV** [comment]
Yep I had checked that and came to the same conclusion. Any suggestion
beside building everything from scratch??  Not looking forward to that as I
have a maze

**Comment by xirixiz** [comment]
Yeah. Remove the integration, remove the config, restart hass. Reinstall the integration, add the config again (type manually, don't copy/paste), restart hass...

Could it be you have new sensors perhaps? Can you check that in the states section in developer?

**Comment by pluim003** [comment]
I have the same issue. On my dashboard it shows:

![afbeelding](https://user-images.githubusercontent.com/67138922/200104862-88c3c7ee-3414-4ca3-b508-e3d5ee528a3b.png)

I know it was working last weekend. Upgraded Afvalwijzer from 10.2 to the latest, but also HASS to 2022.11.01. 

The weird thing is that it doesn't show up under 'Integraties' but according to HACS it should be installed. The only mention in the log is the well-known one:

2022-11-05 03:05:43.966 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration afvalwijzer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by xirixiz** [comment]
That is weird indeed. Maybe it's an issue with HASS itself...

What if you disable debugging and try again, what happens then? 
What is your postal code? Maybe I can simulate the issue.

**Comment by xirixiz** [comment]
2022.11.1 has been released. I've been testing it with the postal code provided earlier. Both with or without debugging the component is working fine for me.

**Comment by pluim003** [comment]
> That is weird indeed. Maybe it's an issue with hass itself... as data is normally showing up when running the afvalwijzer component outside hass, especially since the component doesn't load or doesn't throw an error. The warning is normal and is always showing btw.
> 
> What if you disable debugging and try again, what happens then? What is your postal code? Maybe I can simulate the issue.

I disabled debug and it's still working fine. Guess Hass must have messed up some things. I run Hass in a Docker-container on a RPi4. Well, seems problems solved, but after noticing this earlier this morning (well actually yesterday-evening) I searched and stumbled upon this thread.

**Comment by GesturV** [comment]
I have removed the integration, removed the config, restarted, reinstalled
(restarted, it loads but all sensors are unavailabed ) added the config
again. Still all afvalwijzer sensors are unavailable.
[image: image.png]
I updated to the 11.1 - also that did not make a difference. Not sure if I
have new sensors. But looking at my sensors overall, I have some weird
sensors also unavailable not familiar to me. That is suspicious. They seem
all related to alexa media player integration.

**Comment by GesturV** [comment]
Solved it - @xirixiz , your hunch was correct - additional sensor definition in the configuration.yaml (as opposed as one sensor definition with separate categories underneath was the culprit. Thus not
sensor
  - xxxxx
sensor
  - yyyy

but 
sensor
  - xxxx
  - yyyy

simple stupid mistake.

Thanks for you help

**Comment by xirixiz** [comment]
Great! Nice that the issue has been resolved!
