### ISSUE TITLE
The card not updating 

### ISSUE THREAD

**Issue by rdebrock91** [xirixiz/homeassistant-afvalwijzer#206]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

My card with the days left:  wednesday, the day after tomorrow (2 days) is not updating, i use fully kiosk single app. It works when i close kiosk and open the normal HA app. What can i do about this?

### Expected behaviour

Updating the days left when time 0:00.

### Actual behaviour

Not updating

### Version

* HASS version: latest
* Component version: latest
* Useful system info: 

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

**Comment by xirixiz** [comment]
Hi, is this still an issue? I wasn't able to look into it :)

**Comment by rdebrock91** [comment]
Well, sometimes it takes a little time to update but im ok with it.
