### ISSUE TITLE
Avri does not work

### ISSUE THREAD

**Issue by Dj538** [xirixiz/homeassistant-afvalwijzer#207]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Avri does not work i will get errors everywhere

### Expected behaviour

can you fix it 

### Actual behaviour

can you fix it 

### Version

* HASS version:
* Component version:
* Useful system info:

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

**Comment by xirixiz** [comment]
To ask for support in this way is rude from my point of view. Community projects are done for free to share and help others. This request rather feels like an order. Please rephrase and please provide proper details.
