### ISSUE TITLE
Add Ouder Amstel Waste Times

### ISSUE THREAD

**Issue by alinalihassan** [xirixiz/homeassistant-afvalwijzer#209]
### Request

Would it be possible to add waste collection times for municipalities without APIs? There's Ouder Amstel I know but they just send pdfs every year with the schedule, and it's usually Thursday every year.

Here's the information they provide: https://www.ouder-amstel.nl/Home/Afval/Afvalkalender

**Comment by xirixiz** [comment]
Hi, I've checked but unfortunatly it's too much work to support this. I know there are some PDF parsers out there for HASS, but I don't have any details. Maybe you can ask it at the HASS community forum. Good luck!
