### ISSUE TITLE
Some states aren’t capitalized

### ISSUE THREAD

**Issue by rvdp** [xirixiz/homeassistant-afvalwijzer#210]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Hi, 

I’m using the entities for mijnafvalwijzer a lot. When there is no specific pick up, the state is returned as  ‘Geen’ (Capitalized). But when there is a specific pick up, the returned state is not capitalized, e.g. ‘restafval’. See photo:
![272B3FD4-C009-484E-911C-ACC48E5521A7](https://user-images.githubusercontent.com/7079293/209724873-ccade43e-3aeb-49e7-9e6f-deb6c2928171.jpeg)

### Expected behaviour

Is it possible to capitalize every state that is returned by the integration?

‘restafval’ becoming ‘Restafval’
‘papier’ becoming ‘Papier’
‘gft’ becoming ‘Gft’ (or ‘GFT’, preferably)

### Actual behaviour

States currently returned are: 
- Geen
- restafval
- papier
- gft

### Version

* HASS version: 2022.12.8
* Component version: 2022.11.02
* Useful system info: I’m using the ‘mijnafvalwijzer’ as collector parameter for the integration. 

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

**Comment by xirixiz** [comment]
Ooh, this is a doorn in my eyes :). I`ll have a look the upcoming days.

**Comment by rvdp** [comment]
Thanks, I appreciate it! It’s not really a bug, just a minor beauty tweak  😉

**Comment by rvdp** [comment]
Thanks, I appreciate it! It’s not really a bug, just a minor beauty tweak  😉

**Comment by svanrossem** [comment]
You can use a template like https://github.com/xirixiz/my-hass-config/blob/master/packages/waste.yaml#L80-L88 and customize it to your needs.

I think changing this behavior can break current templates and automations?

**Comment by rvdp** [comment]
I agree if everything was lowercase. But some output having capitals and some that don’t creates unexpected behavior. A standard would really help 😊

**Comment by mvdwetering** [comment]
With HA 2023.1 there will be support for translations on entity states. That should allow for having translations with capitalization while keeping the internal state names the same.

See https://developers.home-assistant.io/blog/2022/12/01/entity_translations

**Comment by xirixiz** [comment]
> I agree if everything was lowercase. But some output having capitals and some that don’t creates unexpected behavior. A standard would really help 😊

Yeah, I agree, but this was the case. By default it was always converted to lowercase, except for "Geen" indeed. I did this because Geen will never be a seperate sensor and the provider itself will not return none data.

But what I mentioned, I guess this can be taken care of in a slighlty better way, so I`ll have a look soon.

Besides that, I really like you all trying to contribute to this issue! Thanks!

**Comment by svanrossem** [comment]
Maybe we can do best of all worlds? Lowercase "Geen" and keep other output untouched (so automations keep working). To correct the translation try @mvdwetering suggest, 2023.1's release party is on it's way tonight :partying_face: .

Get well soon @xirixiz !

**Comment by xirixiz** [comment]
New release available: https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/2023.01.01
