### ISSUE TITLE
Error using RMN as provider

### ISSUE THREAD

**Issue by wtrdk** [xirixiz/homeassistant-afvalwijzer#212]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

I have a problem, using RMN as provider. The RMN app on my iPhone still works, but the integration gives this error:

`Other error occurred _get_next_waste_in_days: unsupported operand type(s) for -: 'datetime.datetime' and 'str'`

It used to work, up until a few days ago...

### Expected behaviour

Show right pickup days

### Actual behaviour

Gives an error, see message

### Version

* HASS version: 2023.1.0
* Component version:
* Useful system info:

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

**Comment by mrksmts** [comment]
I have the same error, I am new to HASS so wasn't 100% sure if I was doing something wrong or not. Provider here is `gad` 

`Other error occurred _get_next_waste_in_days: unsupported operand type(s) for -: 'datetime.datetime' and 'str'
20:57:31 – (FOUT) afvalwijzer (aangepaste integratie)
Other error occurred _get_next_waste_date: list index out of range
20:57:31 – (FOUT) afvalwijzer (aangepaste integratie)`

**Version**
HASS version: 2023.1.0
Component version:
Useful system info: Home Assistant Yellow

**Comment by wtrdk** [comment]
Great, thanks! My postal code is 3701XK (Zeist, NL)


Op vr 6 jan. 2023 om 09:44 schreef Bram van Dartel ***@***.***

**Comment by xirixiz** [comment]
What is the housenumber you are using? When I use 46, I get the following data:

**Comment by wtrdk** [comment]
Hi, my full config:

```sensor:
  - platform: afvalwijzer
    provider: rmn 
    postal_code: 3701XK 
    street_number: 24 
    suffix: "B" 
    exclude_pickup_today: true 
    default_label: Geen 
    id: "" 
    exclude_list: "" 
```

**Comment by xirixiz** [comment]
Thanks! I just found out the suffix is the issue... I`ll have a look why this is.

**Comment by wtrdk** [comment]
> Thanks! I just found out the suffix is the issue... I`ll have a look why this is.

Strange thing is that upon a few days ago it worked with exactly the same config. Thanks for looking into it!

**Comment by xirixiz** [comment]
Yeah, sometimes providers implement changes at the beginning of the year. Should be an easy fix :)

**Comment by xirixiz** [comment]
New release available: https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/2023.01.01

**Comment by wtrdk** [comment]
Hi, something is still wrong. I removed the integration, reinstalled it (the latest version: 2023.01.01), and added my configuration in the yaml file, and I still get the following:
![image](https://user-images.githubusercontent.com/4569244/211100691-8f7c5067-e8ee-46ec-8324-03b573403122.png)
Am I doing something wrong?

**Comment by xirixiz** [comment]
This seems to be an issue with an "old" entity still in the list of sensors. You can remove old/outdated entites yourself.
Remove all entites of afvalwijzer and restart, then the name will be as it was again. Most probably you have something like 👍 

```
sensor.afvalwijzer_today
sensor.afvalwijzer_today_2
sensor.afvalwijzer_today_3
```

Of which only 1 is active, and the one you posted isn't active currently.

You can check it at this page:
```
http(s)://<your_hass_url:8123/config/entities
```

**Comment by wtrdk** [comment]
Works like a charm, thanks a lot!
