### ISSUE TITLE
Lingewaard

### ISSUE THREAD

**Issue by euroman2007** [xirixiz/homeassistant-afvalwijzer#213]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Lingewaard is not included anymore.

### Expected behaviour

Lingewaard is not included anymore.

### Actual behaviour

Lingewaard is not included anymore.

### Version

* HASS version:
* Component version:
* Useful system info:

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

**Comment by xirixiz** [comment]
As you may understand, this description is useless. Please provide a proper description of what the exact problem is you're facing.

**Comment by euroman2007** [comment]
Lingewaard isnt under afvalwijzer anymore.
This means that the integration you have made, wont work with Lingewaard. 
You can test it at the afvalwijzer.nl website.

Lingewaard changed the garbage pickup Company. Thats why it isnt in 
afvalwijzer anymore.

Hope you have a better discription now 😄

If you want to test at afvalwijzer.nl you can test my zip
6691xx 24

Greetings Fernando
Op 6 januari 2023 11:01:48 schreef Bram van Dartel ***@***.***>:

**Comment by xirixiz** [comment]
Thank you 😄! 

However, when I use your details, it's still working with this integration:

```

{'plastic verpakkingen, blik en drinkpakken (pbd)': datetime.datetime(2023, 1, 6, 0, 0), 'oud papier en karton': datetime.datetime(2023, 1, 27, 0, 0), 'groente-, fruit- en tuinafval (gft)': datetime.datetime(2023, 1, 9, 0, 0), 'restafval': datetime.datetime(2023, 1, 12, 0, 0), 'kerstbomen': datetime.datetime(2023, 1, 10, 0, 0)}
{'oud papier en karton': datetime.datetime(2023, 1, 27, 0, 0), 'groente-, fruit- en tuinafval (gft)': datetime.datetime(2023, 1, 9, 0, 0), 'restafval': datetime.datetime(2023, 1, 12, 0, 0), 'kerstbomen': datetime.datetime(2023, 1, 10, 0, 0), 'plastic verpakkingen, blik en drinkpakken (pbd)': 'geen'}
{'next_date': datetime.datetime(2023, 1, 9, 0, 0), 'next_in_days': 3, 'next_type': 'groente-, fruit- en tuinafval (gft)', 'today': 'plastic verpakkingen, blik en drinkpakken (pbd)', 'tomorrow': 'geen', 'day_after_tomorrow': 'geen'}
['groente-, fruit- en tuinafval (gft)', 'kerstbomen', 'oud papier en karton', 'plastic verpakkingen, blik en drinkpakken (pbd)', 'restafval']
['day_after_tomorrow', 'next_date', 'next_in_days', 'next_type', 'today', 'tomorrow']
```

**Comment by euroman2007** [comment]
Thanks for your reply.
Thats Strange 🫢
Specially because it wont work at the website.
Then i am gonna give it a try in HA.
And i am Sorry for my mis understanding.
I am very happy youve checked it out and tested it.
Greetings Fernando



Op 6 januari 2023 11:33:26 schreef Bram van Dartel ***@***.***>:
