### ISSUE TITLE
KeyError: 'ophaaldagen'

### ISSUE THREAD

**Issue by indexample** [xirixiz/homeassistant-afvalwijzer#215]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

our muncipality (Teylingen) changed from provider to prezero as per 2023. Prezero is supported by this Afvalwijzer, but the integration does not work anymore.

the api call returns: 

{"response":"NOK","data":[],"error":"No Afvaldata"}

### Expected behaviour

api should return data and no errors.

### Actual behaviour

{"response":"NOK","data":[],"error":"No Afvaldata"}

### Version

* HASS version: 1.29.1
* Component version: 2023.01.01
* Useful system info: supervisor

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

PI information redacted with [XX]

Logger: homeassistant.components.sensor
Source: custom_components/afvalwijzer/collector/mijnafvalwijzer.py:52
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 2:15:03 PM (1 occurrences)
Last logged: 2:15:03 PM

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 49, in get_waste_data_raw
    response["ophaaldagen"]["data"] + response["ophaaldagenNext"]["data"]
KeyError: 'ophaaldagen'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 65, in async_setup_platform
    collector = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 39, in __init__
    waste_data_raw = mijnafvalwijzer.get_waste_data_raw(
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 52, in get_waste_data_raw
    raise KeyError(f"Invalid and/or no data received from {url}") from exc
KeyError: 'Invalid and/or no data received from https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=[XX]&method=postcodecheck&postcode=[XX]&street=&huisnummer=[XX]&toevoeging=&app_name=afvalwijzer&platform=web&afvaldata=2023-01-10&langs=nl&'

**Comment by xirixiz** [comment]
It seems an error in your config as it's still looking at the api of mijnafvalwijzer.nl. Can you update and or share your config?

**Comment by Istria1704** [comment]
I just had the exact same error. But it seems like mijnafvalwijzer does not support my address. When I enter my postcode and houseno on their website, it says "Uw adres is niet bekend bij ons. Neem contact op met uw gemeente".

When I changed the "provider" to another one, it did work.

**Comment by xirixiz** [comment]
Yes, correct. That's exactly the idea 😀👍🏻
