### ISSUE TITLE
Error while setting up afvalwijzer platform for sensor

### ISSUE THREAD

**Issue by arnolddej** [xirixiz/homeassistant-afvalwijzer#217]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

I loaded the afvalwijzer integration and have set up my conf.yaml as suggested. Unfortunaltely it won't load and the log shows some errors. 

Maybe the api key is overloaded or do I have to get one myself?

### Expected behaviour

No errors and get the sensors 

### Actual behaviour

Error, see logs.

### Version

* HASS version: Home Assistant 2022.12.8
* Component version: 2023.01.01 (tested also one earlier release)
* Useful system info: docker

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

Logger: homeassistant.components.sensor
Source: custom_components/afvalwijzer/collector/mijnafvalwijzer.py:52
Integration: Sensor (documentation, issues)
First occurred: January 25, 2023, 23:59:27 (1 occurrences)
Last logged: January 25, 2023, 23:59:27

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 49, in get_waste_data_raw
    response["ophaaldagen"]["data"] + response["ophaaldagenNext"]["data"]
KeyError: 'ophaaldagen'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 65, in async_setup_platform
    collector = await hass.async_add_executor_job(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 39, in __init__
    waste_data_raw = mijnafvalwijzer.get_waste_data_raw(
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 52, in get_waste_data_raw
    raise KeyError(f"Invalid and/or no data received from {url}") from exc
KeyError: 'Invalid and/or no data received from https://api.afvalstoffendienstkalender.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=1234AB&street=&huisnummer=123&toevoeging=&app_name=afvalwijzer&platform=web&afvaldata=2023-01-25&langs=nl&'

I have replaced my real zipcode here.

**Comment by arnolddej** [comment]
I just updated my docker image to "Home Assistant 2023.1.7" and got the same result.

**Comment by tabnul** [comment]
same here. response api;

`{"response":"NOK","data":[],"error":"No Afvaldata"}`

the website itself also is unable to find my adress. i guess they have general issues. maybe related to the azure issues of yesterday?



`Uw adres is niet bekend bij ons. Neem contact op met uw gemeente`

**Comment by xirixiz** [comment]
Yeah, same issue here. Seems to be an issue at their side indeed....

**Comment by arnolddej** [comment]
Thanks for your replies. Then we have to wait and cross our 🤞

**Comment by xirixiz** [comment]
Issue fixed? It is for me

**Comment by tabnul** [comment]
For me it isnt 5388cz / 6

**Comment by arnolddej** [comment]
For me neither. 

To be sure, mijnafvalwijzer.nl supports almost all gemeentes, correct?
Because the website itself keeps saying my address is unknown. My gemeente is Molenlanden.

**Comment by tabnul** [comment]
> For me neither.
> 
> To be sure, mijnafvalwijzer.nl supports almost all gemeentes, correct? Because the website itself keeps saying my address is unknown. My gemeente is Molenlanden.

It used to support my county. Maybe it changed?

**Comment by tabnul** [comment]
I think since 01-01 things changed. My county needs another app/api now.
https://www.bernheze.org/nieuws/2022/12/15/andere-afvalapp-en-telefoonnummer-voor-afvalinformatie-in-bernheze

**Comment by xirixiz** [comment]
> 5388cz

https://bernheze.afvalstoffendienstkalender.nl/nl/5388cz/6/

**Comment by xirixiz** [comment]
- platform: afvalwijzer
  provider: bar
  postal_code: 3171PT
  street_number:  <my house number, pick any odd number between 1 and 45 to test>
  suffix: ''
  exclude_pickup_today: false
  default_label: Geen
  id: ''
  exclude_list: ''

> For me neither.
> 
> To be sure, mijnafvalwijzer.nl supports almost all gemeentes, correct? Because the website itself keeps saying my address is unknown. My gemeente is Molenlanden.

This is incorrect. There are about 20 providers :). Some communities switch overtime, which happened in your situation.

> For me neither.
> 
> To be sure, mijnafvalwijzer.nl supports almost all gemeentes, correct? Because the website itself keeps saying my address is unknown. My gemeente is Molenlanden.

Nee, er zijn iets van 20 afval aanbieders. Gemeentes hebben nogal eens de neiging te wisselen, wat in jouw geval dus is gebeurd. Jouw gemteente zit nu bij https://www.afvalinfo.nl/afvalkalender/gemeente/1978/molenlanden

**Comment by tabnul** [comment]
> > 5388cz
> 
> This is working properly: https://bernheze.afvalstoffendienstkalender.nl/nl/5388cz/6/
> 
> https://api.afvalstoffendienstkalender.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=5388cz&street=&huisnummer=4&toevoeging=&app_name=afvalwijzer&platform=web&afvaldata=2023-02-02&langs=nl&
> 
> ```yaml
> - platform: afvalwijzer
>   provider: afvalstoffendienstkalender
>   postal_code: 5388CZ
>   street_number:  6
> ```
> 
> Output. Working like a charm:
> 
> ```
> {'gft': datetime.datetime(2023, 2, 7, 0, 0), 'pmd': datetime.datetime(2023, 2, 13, 0, 0), 'papier': datetime.datetime(2023, 2, 13, 0, 0), 'restafval': datetime.datetime(2023, 2, 23, 0, 0)}
> {'gft': datetime.datetime(2023, 2, 7, 0, 0), 'pmd': datetime.datetime(2023, 2, 13, 0, 0), 'papier': datetime.datetime(2023, 2, 13, 0, 0), 'restafval': datetime.datetime(2023, 2, 23, 0, 0)}
> {'next_date': datetime.datetime(2023, 2, 7, 0, 0), 'next_in_days': 4, 'next_type': 'gft', 'today': 'geen', 'tomorrow': 'geen', 'day_after_tomorrow': 'geen'}
> ['gft', 'papier', 'pmd', 'restafval']
> ['day_after_tomorrow', 'next_date', 'next_in_days', 'next_type', 'today', 'tomorrow']
> ```

Confirmed , this works indeed ! Thank you!

**Comment by arnolddej** [comment]
> > For me neither.
> > 
> > To be sure, mijnafvalwijzer.nl supports almost all gemeentes, correct? Because the website itself keeps saying my address is unknown. My gemeente is Molenlanden.
> 
> Nee, er zijn iets van 20 afval aanbieders. Gemeentes hebben nogal eens de neiging te wisselen, wat in jouw geval dus is gebeurd. Jouw gemteente zit nu bij https://www.afvalinfo.nl/afvalkalender/gemeente/1978/molenlanden
> 
> Ik vrees dat je pecht hebt en dat ik het niet kan oplossen voor je: https://data.overheid.nl/en/community/datarequest/1023
> 
> Afvalinfo stelt simpelweg de data niet openbaar beschikbaar, en het scrapen van data wil ik niet implementeren (te gevoelig).
> 
> Dit component support het wel geloof ik, dus daar zou je naar kunnen kijken als alternatief: https://github.com/heyajohnny/afvalinfo

Waardlanden wordt ondersteund door afvalwijzer of werkt deze niet meer?

**Comment by xirixiz** [comment]
Waardlanden werkt niet meer inderdaad. Er is maar 1 component dat er wel mee werkt en dat is die van heyajohnny.
Zoals gezegd wil ik mij niet meer wagen aan een "scraper" oplossing. Het is onbetrouwbaar en vergt veel onderhoud.
