### ISSUE TITLE
Wrong naming in Rova

### ISSUE THREAD

**Issue by Hoite** [xirixiz/homeassistant-afvalwijzer#218]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

The name fetched from inzamelkalender.rova is the class name, ROVA did some funny renaming in their afvalkalender in which plastic is now -> "Gft in emmers".

Is it possible to add this to the renaming file?

![SCR-20230127-azz](https://user-images.githubusercontent.com/17611735/215029015-e1e13874-6d2b-4248-b8d7-09df8058eca4.jpeg)

### Expected behaviour

sensor names in HA for plastic reference to "Gft in emmers" instead of "plastic".

### Actual behaviour

sensor names in HA reference to "plastic" instead of "Gft in emmers".

### Version

* HASS version:
* Component version:
* Useful system info:

> Not version specific

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

n/a

**Comment by xirixiz** [comment]
I`ll have a look! Thanks.

**Comment by xirixiz** [comment]
Can you share your postal code, so I can perform some checks?

**Comment by Hoite** [comment]
8021CC

**Comment by xirixiz** [comment]
Oke, with your postal code I`m getting:

```yaml
{'md': datetime.datetime(2023, 1, 31, 0, 0), 'plastic': datetime.datetime(2023, 2, 2, 0, 0), 'gft': datetime.datetime(2023, 2, 3, 0, 0), 'papier': datetime.datetime(2023, 2, 6, 0, 0)}
{'md': datetime.datetime(2023, 1, 31, 0, 0), 'plastic': datetime.datetime(2023, 2, 2, 0, 0), 'gft': datetime.datetime(2023, 2, 3, 0, 0), 'papier': datetime.datetime(2023, 2, 6, 0, 0)}
{'next_date': datetime.datetime(2023, 1, 31, 0, 0), 'next_in_days': 4, 'next_type': 'md', 'today': 'geen', 'tomorrow': 'geen', 'day_after_tomorrow': 'geen'}
['gft', 'md', 'papier', 'plastic']
['day_after_tomorrow', 'next_date', 'next_in_days', 'next_type', 'today', 'tomorrow']
```

This makes it odd that HASS shows "GFT in emmers"....

This is what I get back from an API call:
```
{"nameType":"gft in emmers","type":"plastic","date":"2023-05-04"}
```

The nameType indeed shows the "gft in emmers" value, but I`m only using type in all of the sourcecode...

**Comment by xirixiz** [comment]
> ut the integration should rename it t

Ahhh, I misunderstood this. They use a wrong "type" for "GFT in emmers", as GFT obviously has nothing todo with plastic. However, I cannot just change this as it will break stuff for many people as each community uses their own weird naming convention. Maybe I can come up with a workaround. I`ll get back to it later.

**Comment by xirixiz** [comment]
Another option would be to contact ROVA and mention that there is something off currently:
```
https://api.inzamelkalender.rova.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=8021CC&street=&huisnummer=31&toevoeging=&app_name=afvalwijzer&platform=web&afvaldata=2023-01-27&langs=nl
```

**Comment by Luitdesign** [comment]
I am not completly into this. But there seems to be two different api's ?
Whem you use this one 
https://www.rova.nl/api/waste-calendar/upcoming?postalcode=8021CC&houseNumber=31
it shows GFTE as type
