### ISSUE TITLE
is_collection_date_today always false 

### ISSUE THREAD

**Issue by cowbalt** [xirixiz/homeassistant-afvalwijzer#220]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

hi, 

if I look at the sensors, I noticed that the "is_collection_date_today" attribute always returns false on the collection day itself. This is probably why the state of the sensor always returns to "geen" on the collection day itself? 

last_update: 03-02-2023 11:02
days_until_collection_date: null
is_collection_date_today: false
is_collection_date_tomorrow: false
is_collection_date_day_after_tomorrow: false
year_month_day_date: null
icon: mdi:recycle
friendly_name: PMD
entity_picture: /local/trash_icons/PMD.png

### Expected behaviour

when attribute is_collection_date_today, returns "true", it would change the state into "vandaag'

### Actual behaviour

is_collection_date_today: false probably changes state into "geen" on collection dates. 

### Version

Home Assistant 2023.2.1
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

### HASS logs

N/A

**Comment by xirixiz** [comment]
You've got a point here. I`ll have a look soon 😄

**Comment by xirixiz** [comment]
Sorry, I have been quiet busy. I wlll respond asap!

**Comment by cowbalt** [comment]
no rush ;)
