### ISSUE TITLE
Integrate with HASS Local Calendar

### ISSUE THREAD

**Issue by baltena** [xirixiz/homeassistant-afvalwijzer#221]
### Request

Hi there,

I have been happily using the Afvalwijzer for a while now. Great work so far! 
As a side note: This is my very first feature request. So be gentle. ;)

In the 2023.1 release of HomeAssistant the[ 'Local Calendars' integration](https://www.home-assistant.io/integrations/local_calendar/) was introduced. With the first (minimal) functionality made available via the UI.
Now with 2023.2 support is added to also add events with a service ['calendar.create_event'](https://www.home-assistant.io/integrations/local_calendar/).

Would it be an idea to also integrate the afvalwijzer dates into a local calendar?

This creates the possibility to: 
- **Calendar view:** View the upcoming garbage collections in the Calendar view
- **Notifications:** Use the calendar events for generic notification automations
- **Easy representation:** I can imagine there will also be other cards/views made available for the Local calendars. By integrating Afvalwijzer those events can also tag along.

Very curious to know how others feel about this. 
From a technical point of view, I am not very sure how big the impact would be to make this happen. So any replies on the complexity would be more than welcome.

Cheers!
Bart

**Comment by xirixiz** [comment]
Sorry, I have been quiet busy. I wlll respond asap!
