### ISSUE TITLE
request for add RWM (RWM afval en reiniging)

### ISSUE THREAD

**Issue by scannie67** [xirixiz/homeassistant-afvalwijzer#222]
### Request

Is it possible to add RWM in afvalwijzer for zipcode 6105 CL?

Many thanks in advance.
Peter.

**Comment by xirixiz** [comment]
Sorry, I have been quiet busy. I wlll respond asap!

**Comment by xirixiz** [comment]
Hi, sorry to tell you, but there is no possibility to access an api to retrieve the data from. Multiple providers migrated to "https://21burgerportaal.mendixcloud.com/" ... which sucks for now :)
