### ISSUE TITLE
Request to add RMN to afvalwijzer

### ISSUE THREAD

**Issue by epjjansen** [xirixiz/homeassistant-afvalwijzer#223]
### Request

Please add RMN to Afvalwijzer (Reiningingsdienst Midden Nederland)
as of 1 March https://inzamelschema.rmn.nl/ will change to a new portal
https://21burgerportaal.mendixcloud.com/

example
3404ES 1

**Comment by xirixiz** [comment]
Sorry, I have been quiet busy. I wlll respond asap!

**Comment by xirixiz** [comment]
Hi, sorry to tell you, but there is no possibility to access an api to retrieve the data from. Multiple providers migrated to "https://21burgerportaal.mendixcloud.com/" ... which sucks for now :)

**Comment by imdos** [comment]
I've found the new RMN app and did some certificate unpinning with frida and http toolkit. The new URL is for and adress in IJsselstein for example:
3402ta 17

https://europe-west3-burgerportaal-production.cloudfunctions.net/exposed/organisations/138204213564933597/address/206321157929710806/calendar

Please let me know if you require some others which reside within the same region to check if the scripts can be rewritten.

P.S. I'm fluent in Dutch; but don't know which language is preferred.

**Comment by epjjansen** [comment]
Is fixed in: [https://github.com/xirixiz/homeassistant-afvalwijzer/issues/232]

great job
