### ISSUE TITLE
Support for Veldhoven

### ISSUE THREAD

**Issue by remcopoulus** [xirixiz/homeassistant-afvalwijzer#225]
### Request

Hello, is it possible to add support for Veldhoven?
Information is available at [veldhoven.nl/afvalkalender/](https://www.veldhoven.nl/afvalkalender/)

### Additional information

Voorbeeld adres:
Postcode: 5502DD
Huisnummer: 1

**Comment by xirixiz** [comment]
Sorry, I have been quiet busy. I wlll respond asap!

**Comment by xirixiz** [comment]
Unfortunatly it's not possible to add Veldhoven currently. They don't provide a proper datasource.
