### ISSUE TITLE
Unique IDs. 

### ISSUE THREAD

**Issue by ywscoaching** [xirixiz/homeassistant-afvalwijzer#226]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Platform afvalwijzer does not generate unique IDs. 

### Expected behaviour

Generate unique IDs

### Actual behaviour

Platform afvalwijzer does not generate unique IDs. 

### Version

* HASS version: 2023.3.1
* Component version: 2023.01.01
* Useful system info:

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:540
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 14:39:29 (9 occurrences)
Last logged: 14:39:29

Platform afvalwijzer does not generate unique IDs. ID d61f5cf5bb025264309fa536e4008acc3a91f998 already exists - ignoring sensor.afvalwijzer_next_date
Platform afvalwijzer does not generate unique IDs. ID 8527134b8ef240249af1ddf87816b126deeb87ac already exists - ignoring sensor.afvalwijzer_next_in_days
Platform afvalwijzer does not generate unique IDs. ID 32f229ae9b9d2188f511fd58076185ef708fe350 already exists - ignoring sensor.afvalwijzer_next_type
Platform afvalwijzer does not generate unique IDs. ID 7ca0bac48134bb59723cb24bc89cbeda267de512 already exists - ignoring sensor.afvalwijzer_today
Platform afvalwijzer does not generate unique IDs. ID 32af8e45c299be12b7559928436b9dfe985ebf2f already exists - ignoring sensor.afvalwijzer_tomorrow

**Comment by xirixiz** [comment]
Hi, thanks for sharing. However, the component creates unique ID's actually.

https://github.com/xirixiz/homeassistant-afvalwijzer/blob/b53fbaeaf74987a037c145bb2b2002a8c6196b73/custom_components/afvalwijzer/sensor_custom.py#L41

and:
https://github.com/xirixiz/homeassistant-afvalwijzer/blob/b53fbaeaf74987a037c145bb2b2002a8c6196b73/custom_components/afvalwijzer/sensor_provider.py#L52

As it's about the "custom" defined sensors, it should be coming from the sensor_cusom.py file.
Did you stop and restart HASS to try again? If so, I`ll investigate it further.

**Comment by ywscoaching** [comment]
hi,

Yes, i did. I moved from HA on vm on NAS to HA on Proxmox. After restore backup, the same error occured.

**Comment by xirixiz** [comment]
Can you validate again with the latest release?

**Comment by xirixiz** [comment]
> hi,
> 
> Yes, i did. I moved from HA on vm on NAS to HA on Proxmox. After restore backup, the same error occured.

But this seems to be related to another error (backup restore procedure). If it already has a unique ID from a backup, it doesn't recreate an ID.

**Comment by ywscoaching** [comment]
How can i delete the "old" unique numbers in the database?

**Comment by xirixiz** [comment]
Hi, the unique IDs are stored in a file in you HASS config directory (.storage folder I believe). What you could do is ask how to do this at the HASS community as I`m not updating config in HASS very often anymore (so I lack of knowledge here :))
