### ISSUE TITLE
Support for Etten-Leur

### ISSUE THREAD

**Issue by st3fannldev** [xirixiz/homeassistant-afvalwijzer#231]
### Request

Requesting support for https://www.afval3xbeter.nl/
My city has stopped using mijnafvalwijzer, maybe the cause of my reported issue too? (Which is weird cause my father in law can use it just fine in the same city)

**Comment by xirixiz** [comment]
Hmm, voor zover ik kan zien heeft afval3xbeter geen api waar de data vanaf gehaald kan worden.
Heb je een postcode voor mij? Dan kan ik voor de zekerheid nog even verder kijken.

**Comment by st3fannldev** [comment]
> Hmm, voor zover ik kan zien heeft afval3xbeter geen api waar de data vanaf gehaald kan worden. Heb je een postcode voor mij? Dan kan ik voor de zekerheid nog even verder kijken.

Niet mijn postcode maar: 4872SC nmr 11

Mijn schoonvader gebruikt ook deze integratie en daarbij werken de sensors wel, dus ik weet niet of het aan mijn systeem ligt, of de API. Refererende naar de issue die ik gemaakt had.

**Comment by xirixiz** [comment]
Dan kan het zijn dat de data nog steeds in mijnafvalwijzer staat voor de postcode van jouw schoonvader. Voor de postcode opgegeven is er iig geen data meer beschikbaar. Misschien kan je aan jouw schoonvader vragen wat hij als provider heeft ingesteld voor deze integratie.

**Comment by st3fannldev** [comment]
Ah.. hij gebruikt Afvalinfo. Vandaar dat het bij hem wel werkt.
