### ISSUE TITLE
Renaming pruning to takken incorrect for RD4

### ISSUE THREAD

**Issue by Cyclone47** [xirixiz/homeassistant-afvalwijzer#236]
Created a [pull request](https://github.com/xirixiz/homeassistant-afvalwijzer/pull/237) for the below issue
### Support guidelines
- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description
At [line 50 of main_functions.py](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/f78500dd51a0fe0dfa977561b0afec432c229e1c/custom_components/afvalwijzer/common/main_functions.py#L50)

- There is an incorrect catch to rename pruning to takken.
- pruning should be **pruning_waste**. This will then succesfully rename it to takken.

### Expected behaviour
- pruning should be shown as takken. 

- Additionally; I think **snoeiafval** would be a better translation :)

### Actual behaviour
pruning does not get translated.

**Comment by xirixiz** [comment]
Sorry, was a bit away due to health issues. This modification was already published in a pre-release.
I will release a fixed version Today!
