### ISSUE TITLE
ROVA Zwolle changed waste categories

### ISSUE THREAD

**Issue by hogend** [xirixiz/homeassistant-afvalwijzer#239]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

ROVA Zwolle now collects GFT in containers, GFT in mini-bins, PMD in bags and paper in containers.
The corresponding waste categories (in the API) are, "gft", "plastic", "md" and "papier". So, "plastic" and "md" do not match.

### Expected behaviour

Translate "plastic" to, e.g. GFT(mini) and "md" to "PMD" when reporting.

### Actual behaviour

GFT mini-bin dates are reported as "plastic" and PMD is reported as "md"

### Version

* HASS version: 2023.05.02
* Component version: 2023.04.03
* Useful system info: hass in a virtualenv on debian sid

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

**Comment by xirixiz** [comment]
Hi, thanks for the clear comments. I will update the sourcecode and publish a new release.

**Comment by hogend** [comment]
Any changes in the pipeline for this (given the recent "stale" marking)?

**Comment by xirixiz** [comment]
Morning! Sorry, was a bit away due to health issues. I will have a look Today but need some more details.

**Comment by xirixiz** [comment]
Hi @hogend, did the last change work as expected?
