### ISSUE TITLE
Circulus (-berkel) as Collector

### ISSUE THREAD

**Issue by Axalian215** [xirixiz/homeassistant-afvalwijzer#242]
### Request

Would it be possible to add Circulus (-berkel) as collector? https://mijn.circulus.nl/afvalkalender/

**Comment by xirixiz** [comment]
Hi @Axalian215, that would be possible as far as I could see. Do you still want it, or did you find another solution in the meantime?

**Comment by Axalian215** [comment]
No, please do. I really like this plugin but atm i cant use it.

**Comment by xirixiz** [comment]
Should be easy to implement, so expect it somewhere this weekend or after the weekend.

**Comment by xirixiz** [comment]
Correction, maintenance weekend @ work.... should be able to fix it somewhere upcoming week.

**Comment by Axalian215** [comment]
Did you have time to add this feature?🙂

**Comment by Axalian215** [comment]
Hi @xirixiz,

Could you give me an update about adding the new code?🙂 Would like to use this component within my HA.

Thanks

**Comment by Dualdriven** [comment]
Already thought why I couldnt get it to function... this explains it. I will wait for the update as well 👍
