### ISSUE TITLE
list with dates and types to import in calendar

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#243]
### Request

Hi Bram,

Been a long time user, and still very happy with the options your CC offers, it's the main alerter in my HA config ;-)

yet, we now have the native calendar integration, and given the new script options in HA 2023.7 will offer us returning data, and the release party showed Frenck displaying his calendar events for his waste management, I tried to create a calendar in HA with Afvalwijzer dates.

Only to find we can not do that, if only because we just have 2 entities (next_type and next_date) and a few sensors for the specific waste types.

In the old days of this CC, we still had an option for the full year list, or at least that was used to create the other entities.

Couldnt this somehow be returned, into a form so that we could use it for creating calendar events, or maybe even automate that using some import?

Please have a look if you didn't already,
anyways, cheers,
Marius

### Additional information

I did see we can dl a pdf with all dates. I tried to manually import those into the Mac calendar app, but as the PDF holds many formatting issues (not all have a hot popup, and many have wrong ones setting an activity in the wrong month) that PDF isnt super useful in itself....

maybe there still is a hidden date list in that website somewhere

**Comment by Mariusthvdb** [comment]
Keep

**Comment by xirixiz** [comment]
Currently I'm working on a new release supporting all Dutch waste providers. I'll take this into account as well.
