### ISSUE TITLE
I see that ximmio (Meerlanden) is probably ratelimiting the rerquests to it's api, can I suggest ratelimiting the request made to the api

### ISSUE THREAD

**Issue by adekloet** [xirixiz/homeassistant-afvalwijzer#244]
### Request

Hi,

To avoid the below, to many requests to the ximmio API, could the amount of requests be rate limited? Maybe have a default of once a day and have a configurable setting if you want to check more then once a day? If a connection cannot be made, the integration could go into a slow retry function (Maybe once an hour) until it connected once.

Observed in logging:

Check afvalwijzer platform settings (ConnectionError(MaxRetryError("HTTPSConnectionPool(host='wasteprod2api.ximmio.com', port=443): Max retries exceeded with url: /api/FetchAdress (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f67fb5cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))")),)

**Comment by IGNWoudenberg** [comment]
I’ve got the same, but then with Rova
 
 (ConnectionError(MaxRetryError("HTTPSConnectionPool(host='api.inzamelkalender.rova.nl', port=443): Max retries exceeded with url: /webservices/appsinput/?

**Comment by xirixiz** [comment]
Currently I`m working on a new release supporting all Dutch waste providers. I`ll take this into account as well.
