### ISSUE TITLE
Capital letter

### ISSUE THREAD

**Issue by aroe0546** [xirixiz/homeassistant-afvalwijzer#245]
### Request

in home assistant all sensors start with a capital letter only yours don't.

example:
Sensor is next type: =**r**estafval 
but how do I get **R**estafval is

This is a simple thing but it triggers my brain

**Comment by xirixiz** [comment]
Hehehe, I thought I've implemented an option for this. I'll get back to this in a couple of days 👍🏻

**Comment by xirixiz** [comment]
Currently I`m working on a new release supporting all Dutch waste providers. I`ll take this into account as well.
