### ISSUE TITLE
Add afvalkalender Veldhoven

### ISSUE THREAD

**Issue by mauricevanderlee** [xirixiz/homeassistant-afvalwijzer#249]
### Request

In veldhoven the calendar can be downloaded as iCal using the following url: https://www.veldhoven.nl/afvalkalender/{%Y}/{postal_code}-{street_number}{suffix}.ics

In the additional information I added examples for every pick-up item in the iCal data.

### Additional information

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//CARE Internet Services//Sitebox CMS
METHOD:PUBLISH

BEGIN:VEVENT
UID:d6c6c747ce63a12ca686929af2bd9c19@www.veldhoven.nl
DTSTAMP:20231018T093925Z
DTSTART;VALUE=DATE:20230104
SUMMARY:Grijze container
DESCRIPTION:De grijze container wordt op woensdag 1 keer in de 4 weken geleegd.
TRANSP:TRANSPARENT
END:VEVENT

BEGIN:VEVENT
UID:4b488b63b1c0389b15354d26a5c90490@www.veldhoven.nl
DTSTAMP:20231018T093925Z
DTSTART;VALUE=DATE:20230222
SUMMARY:Groene container
DESCRIPTION:De groene container wordt elke woensdag geleegd.
TRANSP:TRANSPARENT
END:VEVENT

BEGIN:VEVENT
UID:76a476862d249dd84b8ac95355ec4ad7@www.veldhoven.nl
DTSTAMP:20231018T093925Z
DTSTART;VALUE=DATE:20230107
SUMMARY:Papierinzameling
DESCRIPTION:Ophaaldag: zaterdag
TRANSP:TRANSPARENT
END:VEVENT

BEGIN:VEVENT
UID:40603491e236a4e2b975a7dba1a6e1bb@www.veldhoven.nl
DTSTAMP:20231018T093925Z
DTSTART;VALUE=DATE:20230315
SUMMARY:PMD-zak
DESCRIPTION:PMD wordt elke woensdag ingezameld.
TRANSP:TRANSPARENT
END:VEVENT

BEGIN:VEVENT
UID:e77c733a7f0eca566a2eda64ac0fc827@www.veldhoven.nl
DTSTAMP:20231018T093925Z
DTSTART:20230916T070000Z
DTEND:20230916T093000Z
SUMMARY:Chemokar
DESCRIPTION:Locatie - parkeerterrein Mira (Zonderwijk)
LOCATION:parkeerterrein Mira (Zonderwijk)
TRANSP:TRANSPARENT
END:VEVENT

END:VCALENDAR

**Comment by mauricevanderlee** [comment]
I changed some lines myself to make it work. See bolt lines in parts of files:
In const.py:
SENSOR_COLLECTORS_ICALENDAR = {
    "eemsdelta": "https://www.eemsdelta.nl/trash-calendar/download/{1}/{2}",
    **"veldhoven": "https://www.veldhoven.nl/afvalkalender/{5}/{1}-{2}.ics",**
}

in icalendar.py:
    DATE_PATTERN = re.compile(r"^\d{8}")
    **TODAY = datetime.now()
    YEAR_CURRENT = TODAY.year**

    try:
        url = SENSOR_COLLECTORS_ICALENDAR[provider].format(
            provider,
            postal_code,
            street_number,
            suffix,
            datetime.now().strftime("%Y-%m-%d"),
            **YEAR_CURRENT,**
        )
        raw_response = requests.get(url, timeout=60, verify=False)
    except requests.exceptions.RequestException as err:
        raise ValueError(err) from err

I had to change the line with key, value = line.split(":", 2) to key, value = line.split(":", 1). This had to do with ;-sign in text.

in main_functions.py (Not sure what this does...):
    **if item_name == "grijze container":
        item_name = "restafval"
    if item_name == "groene container":
        item_name = "gft"
    if item_name == "pmd-zak":
        item_name = "plastic"
    if item_name == "papierinzameling":
        item_name = "papier"
    if item_name == "chemokar":
        item_name = "chemisch"**

Hope you can put this in the latest version.

**Comment by mauricevanderlee** [comment]
I changed some lines myself to make it work. See bolt lines in parts of files:
Add url for Veldhoven in const.py:
```
SENSOR_COLLECTORS_ICALENDAR = {
"eemsdelta": "[https://www.eemsdelta.nl/trash-calendar/download/{1}/{2}](https://www.eemsdelta.nl/trash-calendar/download/%7B1%7D/%7B2%7D)",
"veldhoven": "[https://www.veldhoven.nl/afvalkalender/{5}/{1}-{2}.ics](https://www.veldhoven.nl/afvalkalender/%7B5%7D/%7B1%7D-%7B2%7D.ics)",
}
```

Add current year in icalendar.py:
```
TODAY = datetime.now()
YEAR_CURRENT = TODAY.year
try:
    url = SENSOR_COLLECTORS_ICALENDAR[provider].format(
        provider,
        postal_code,
        street_number,
        suffix,
        datetime.now().strftime("%Y-%m-%d"),
        YEAR_CURRENT,
    )
```
I had to change the line in icalendar.py with
`key, value = line.split(":", 2)`
to
`key, value = line.split(":", 1)`
This had to do with ;-sign in text for paper: Ophaaldag: zaterdag.

in main_functions.py (Not sure what this does...):
```
if item_name == "grijze container":
item_name = "restafval"
if item_name == "groene container":
item_name = "gft"
if item_name == "pmd-zak":
item_name = "plastic"
if item_name == "papierinzameling":
item_name = "papier"
if item_name == "chemokar":
item_name = "chemisch"
```

At least it works now on my side. Hope you can put this in the latest version.

**Comment by mauricevanderlee** [comment]
I changed some lines myself to make it work. See bolt lines in parts of files:
Add url for Veldhoven in const.py:
```
SENSOR_COLLECTORS_ICALENDAR = {
"eemsdelta": "[https://www.eemsdelta.nl/trash-calendar/download/{1}/{2}]",
"veldhoven": "[https://www.veldhoven.nl/afvalkalender/{5}/{1}-{2}.ics]",
}
```
Add current year in icalendar.py:
```
TODAY = datetime.now()
YEAR_CURRENT = TODAY.year
try:
    url = SENSOR_COLLECTORS_ICALENDAR[provider].format(
        provider,
        postal_code,
        street_number,
        suffix,
        datetime.now().strftime("%Y-%m-%d"),
        YEAR_CURRENT,
    )

```
I had to change the line in icalendar.py with
`key, value = line.split(":", 2)`
to
`key, value = line.split(":", 1)`
This had to do with ;-sign in text for paper: Ophaaldag: zaterdag.

in main_functions.py (Not sure what this does...):
```
if item_name == "grijze container":
item_name = "restafval"
if item_name == "groene container":
item_name = "gft"
if item_name == "pmd-zak":
item_name = "plastic"
if item_name == "papierinzameling":
item_name = "papier"
if item_name == "chemokar":
item_name = "chemisch"
```
At least it works now on my side. Hope you can put this in the latest version.

**Comment by xirixiz** [comment]
Added this to the latest release.

**Comment by xirixiz** [comment]
The main_functions.py part wasn't used for icanlendar. It renames weirdly named trash types. I've added it now for icalandar as well, so it could have impact on the names of your current sensors.

**Comment by diractions** [comment]
This latest version now throws an exception:

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 41, in get_waste_data_raw
    if not response["ophaaldagen"]:
           ~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'ophaaldagen'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 65, in async_setup_platform
    collector = await hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 41, in __init__
    waste_data_raw = mijnafvalwijzer.get_waste_data_raw(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 45, in get_waste_data_raw
    raise KeyError(f"Invalid and/or no data received from {url}") from err
KeyError: 'Invalid and/or no data received from https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=5508SB&street=&huisnummer=51&toevoeging=&app_name=afvalwijzer&platform=web&afvaldata=2024-01-10&langs=nl&'

Afvalwijzer.nl also states "Uw adres is niet bekend bij ons. Neem contact op met uw gemeente".

**Comment by diractions** [comment]
I have set veldhoven now as provider in the configuration.yaml file. Now it throws another exception: Check afvalwijzer platform settings (InvalidSchema("No connection adapters were found for '[https://www.veldhoven.nl/afvalkalender/2024/5508SB-51.ics]'"),)

And: 2024-01-11 16:59:37.015 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 65, in async_setup_platform
    collector = await hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 107, in __init__
    waste_data_raw,
    ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'waste_data_raw' where it is not associated with a value

Is there something I'm doing wrong which is not documented by you?

**Comment by xirixiz** [comment]
No, it's looking good actually. Also, when using the link I retrieve the correct data. Maybe @mauricevanderlee has more details.

**Comment by diractions** [comment]
I just have found the bug. In the const.py you have two brackets [] around the URL. In the meantime, I have the sensor working by just removing the brackets and configuring the provider as veldhoven.

Dank je wel voor de snelle feedback!

**Comment by xirixiz** [comment]
Hahaha, I just noticed as well.... will push it and release a new version directly.

**Comment by xirixiz** [comment]
Done [2024.01.04](https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/2024.01.04)!

En graag gedaan!

**Comment by xirixiz** [comment]
Heb de code meteen even een update gegeven zodat er geen specifieke zaken meer inzitten voor Veldhoven. Getest en werkt.
Release 2024.01.05 komt er dus ook aan 😄

**Comment by mauricevanderlee** [comment]
Thanks!
Sorry for my late reply, I do not have notifications on github...
I indeed had to change the sensors to the new naming and it works!
Groeten uit Veldhoven!
