### ISSUE TITLE
Add afvalkalender Circulus

### ISSUE THREAD

**Issue by mgdijkerman** [xirixiz/homeassistant-afvalwijzer#250]
### Request

Add afvalkalender based on https://mijn.circulus.nl/afvalkalender/

**Comment by mgdijkerman** [comment]
Bump to reactivate

**Comment by Axalian215** [comment]
Is there any update about this one?

**Comment by xirixiz** [comment]
Sorry, didn't work for quiet some time on any updates for this component.
The last weeks I've been active again, so I plan to pick this up in the upcoming weeks.

**Comment by xirixiz** [comment]
I've added circulus but I need a postal code and housenumber to do some validation. Could someone provide a working postal code and housenumber?

**Comment by mgdijkerman** [comment]
Is there an option to this you this privately?

**Comment by xirixiz** [comment]
Sure, send me an email: https://www.yunta.nl/

**Comment by xirixiz** [comment]
Received! Thanks

**Comment by xirixiz** [comment]
2024.01.01 released with support of circulus 🎉

**Comment by xirixiz** [comment]
Just release 2024.01.02. Updated some renaming which also impact circulus (pap = papier now)
