### ISSUE TITLE
Afvalwijzer stoppés working after upgrade to 2023.12.0

### ISSUE THREAD

**Issue by rdevino** [xirixiz/homeassistant-afvalwijzer#255]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Sinds de update naar 2023.12.0 van home assistant zijn de statussen weer unknown 

### Expected behaviour

Data uit de afvalstoffendienstkalender

### Actual behaviour

Lege input, waardoor alle entiteiten unavailable aangeven

### Version

* HASS version:
* Component version:
* Useful system info:

### HASS logs

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
Integration: Sensor (documentation, issues)
First occurred: December 7, 2023 at 21:11:26 (1 occurrences)
Last logged: December 7, 2023 at 21:11:26

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 65, in async_setup_platform
    collector = await hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 99, in __init__
    waste_data_raw,
    ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'waste_data_raw' where it is not associated with a value

**Comment by markieo1** [comment]
Is duplicated by #254

**Comment by xirixiz** [comment]
Drafted release: 2023.12.01

Sorry for the delay. Forgot about it due to the holidays :)
