### ISSUE TITLE
AVRI pmd is pdb now

### ISSUE THREAD

**Issue by FreddyX078** [xirixiz/homeassistant-afvalwijzer#256]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

AVRI plastic (pmd) is not loading. After some investigation I saw it is now pdb. So after adding:
    if item_name == "pdb":
        item_name = "pmd"
to #XIMMIO main_functions.py, Plastic is working again :-)

### Expected behaviour

Load Plastic data

### Actual behaviour

Don't load Plastic data

### Version

* HASS version: 2023.12.3
* Component version: 2023.09.1
* Useful system info:

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

**Comment by xirixiz** [comment]
Fixed in release: https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/2023.12.02
