### ISSUE TITLE
first upcomming date is incorrect near the end of the year.

### ISSUE THREAD

**Issue by bkbartk** [xirixiz/homeassistant-afvalwijzer#257]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

my sensor show the next garbage pickup on january 4th, while actually it is tomorrow
![image](https://github.com/xirixiz/homeassistant-afvalwijzer/assets/17070805/de1a13dd-7a82-4c52-8109-968f320e1803)
next date is tomorrow
![image](https://github.com/xirixiz/homeassistant-afvalwijzer/assets/17070805/f1840a15-d64a-42b4-a8ca-20666def9ac9)
![image](https://github.com/xirixiz/homeassistant-afvalwijzer/assets/17070805/13590d78-7f5c-4395-befc-9fd52bf9c501)
![image](https://github.com/xirixiz/homeassistant-afvalwijzer/assets/17070805/efbd9e71-b309-4e81-a151-6ace3bc7bdfc)
while plastic and gft show 04-01-2024(dd-MM-yyyy)
probably some order by misses the year

### Expected behaviour

date 21-12-2023 are shown for (plastic,gft) and 
28-12-2023 for rest

### Actual behaviour

date 04-01-2024 are shown for (plastic,gft) and 
25-01-2024 for rest

### Version

 Core 2023.12.3
Supervisor 2023.12.0
Operating System 11.2
Frontend 20231208.2
component2023.09.01

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

**Comment by bkbartk** [comment]
created a fix for you,
https://github.com/xirixiz/homeassistant-afvalwijzer/pull/258
please check it out,

**Comment by xirixiz** [comment]
Drafted release: 2023.12.01

Sorry for the delay. Forgot about it due to the holidays :)
