### ISSUE TITLE
Gemeente Assen no longer uses Afvalwijzer after 01-01-2024

### ISSUE THREAD

**Issue by wimb0** [xirixiz/homeassistant-afvalwijzer#259]
### Request

Gemeente Assen stops using Afvalwijzer after 01-01-2024.
Seems like they will start using Burgerportaal, like BAR and RMN.
See: https://play.google.com/store/apps/details?id=nl.qubz21.burgerportaal.assen.prod

Maybe Assen can be implemented like this as well?
Want to help if need, but do have necessary coding skills myself.

**Comment by markvdlaan** [comment]
I added new version for Gemeente Assen
#260

**Comment by wimb0** [comment]
Thanks, that was fast.

**Comment by xirixiz** [comment]
Drafted release: 2023.12.01

Sorry for the delay. Forgot about it due to the holidays :)

**Comment by ceedebee70** [comment]
Same issue overhere, fixed it with your update. Thanks a lot!

**Comment by Janthenman67** [comment]
> I added new version for Gemeente Assen #260

HI, first of all, thanx for the fast fix.  However I am struggeling to change myconfiguration.yaml file. What exactely has to be changed to retreive te right dates again? I changed the provider but it only gave me faults in return

**Comment by wimb0** [comment]
You need to change the provider from "mijnafvalwijzer" to "assen" in your yaml config file:
![image](https://github.com/xirixiz/homeassistant-afvalwijzer/assets/11030068/5d025d25-816d-42fc-a045-aaa403bd7b77)

**Comment by Janthenman67** [comment]
Ues, i did just that, but it didn't seem to work. But I will retry now I am certain that it how it is done, thanks.

**Comment by vincentkoevoets** [comment]
Thanks for this, works like a charm. I'm curious about the mechanics of it all, so will dive into the source just for fun. 
I lost hope when they switched apps in Assen, but then I found out my fellow Home Assistant users in Assen already asked the question here! :smile:

**Comment by ethemcemozkan** [comment]
Can someone guide us to do the same for Nijkerk? We have no clue how to find the id. See the issue https://github.com/xirixiz/homeassistant-afvalwijzer/issues/278
