### ISSUE TITLE
error occurred _get_next_waste_date: list index out of range and unsupported operand type(s) for -: 'datetime.datetime' and 'str'

### ISSUE THREAD

**Issue by Jeroennl** [xirixiz/homeassistant-afvalwijzer#263]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Two exceptions are thrown when using the integration in "next_sensor_data.py". Both are in the get_next_waste_date section

### Expected behaviour

No exceptions.

### Actual behaviour

The following exceptions are thrown:

`Logger: custom_components.afvalwijzer.const.const
Source: custom_components/afvalwijzer/common/next_sensor_data.py:45
Integration: afvalwijzer ([documentation](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/README.md), [issues](https://github.com/xirixiz/homeassistant-afvalwijzer/issues))
First occurred: 13:30:46 (2 occurrences)
Last logged: 13:31:16

Other error occurred _get_next_waste_in_days: unsupported operand type(s) for -: 'datetime.datetime' and 'str'`

`Logger: custom_components.afvalwijzer.const.const
Source: custom_components/afvalwijzer/common/next_sensor_data.py:36
Integration: afvalwijzer ([documentation](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/README.md), [issues](https://github.com/xirixiz/homeassistant-afvalwijzer/issues))
First occurred: 13:30:46 (2 occurrences)
Last logged: 13:31:16

Other error occurred _get_next_waste_date: list index out of range`

### Version

* HASS version: 2023.12.3
* Component version: 2023.12.02
* Useful system info:

### HASS logs

The following exceptions are thrown:

`Logger: custom_components.afvalwijzer.const.const
Source: custom_components/afvalwijzer/common/next_sensor_data.py:45
Integration: afvalwijzer ([documentation](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/README.md), [issues](https://github.com/xirixiz/homeassistant-afvalwijzer/issues))
First occurred: 13:30:46 (2 occurrences)
Last logged: 13:31:16

Other error occurred _get_next_waste_in_days: unsupported operand type(s) for -: 'datetime.datetime' and 'str'`

`Logger: custom_components.afvalwijzer.const.const
Source: custom_components/afvalwijzer/common/next_sensor_data.py:36
Integration: afvalwijzer ([documentation](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/README.md), [issues](https://github.com/xirixiz/homeassistant-afvalwijzer/issues))
First occurred: 13:30:46 (2 occurrences)
Last logged: 13:31:16

Other error occurred _get_next_waste_date: list index out of range`

**Comment by xirixiz** [comment]
Hi, could you please share your postal code and some random house number in the area so I can perform some tests?

**Comment by Jeroennl** [comment]
Hi, my postal code 6245RJ and a random number 11.

Op zo 31 dec 2023 15:25 schreef Bram van Dartel ***@***.***>:

**Comment by Jeroennl** [comment]
For some reason the problem is solved.

**Comment by xirixiz** [comment]
It's probably because the waste provider started providing new waste data since the 1st of Jan for this year... if there is no data, these kind of issues will appear. Closing the ticket.
