### ISSUE TITLE
Failed to initialize the sensor

### ISSUE THREAD

**Issue by yannick1203** [xirixiz/homeassistant-afvalwijzer#265]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

Something is going wrong at setting up.

### Expected behaviour

Give me entities to work with

### Actual behaviour

Error message is given.
`2024-01-06 15:08:42.224 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 41, in get_waste_data_raw
    if not response["ophaaldagen"]:
           ~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'ophaaldagen'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/afvalwijzer/sensor.py", line 65, in async_setup_platform
    collector = await hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 40, in __init__
    waste_data_raw = mijnafvalwijzer.get_waste_data_raw(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 45, in get_waste_data_raw
    raise KeyError(f"Invalid and/or no data received from {url}") from err
KeyError: 'Invalid and/or no data received from https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca&method=postcodecheck&postcode=GEHEIM&street=&huisnummer=GEHEIM&toevoeging=&app_name=afvalwijzer&platform=web&afvaldata=2024-01-06&langs=nl&'
`

### Version

* HASS version: 11.3
* Component version: 2023.12.02
* Useful system info: RPI

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

**Comment by xirixiz** [comment]
Hoi @yannick1203, is your waste provider "mijnafvalwijzer"? If not, please check if your waste provider is supported.
If mijnafvalwijzer should be correct, please share your postal code (DM or mail or something), so I can perform some checks.

**Comment by yannick1203** [comment]
@xirixiz i sent a mail :)

**Comment by xirixiz** [comment]
Thanks! Ik vermoed toch dat je geen mijnafvalwijzer hebt als provider. Ik krijg namelijk dit:

![image](https://github.com/xirixiz/homeassistant-afvalwijzer/assets/11210639/9407c7ff-f26b-4d57-a81e-f1383149ed0a)

**Comment by xirixiz** [comment]
Hi Yannick, I just send you an email. The housenumber of your neighbours is recognized. It seems to be an issue between the data from your local authority and mijnafvalwijzer.nl. I would contact the authorities to have this checked out, but in the meantime you can use a housenumber of your neighbours ofcourse.

**Comment by yannick1203** [comment]
Opgelost (:
