### ISSUE TITLE
Woerden-Oudewater in Ximmio platform

### ISSUE THREAD

**Issue by phnpost** [xirixiz/homeassistant-afvalwijzer#269]
### Request

Hallo. Woerden-Oudewater maakt sinds kort gebruik van het Ximmio platform. Zou dit aangepast kunnen worden in de tool?

**Comment by phnpost** [comment]
Overigens een diepe buiging voor je werk en veel dank!

**Comment by xirixiz** [comment]
Thanks!! 🙏. 

Woerden kan al gebruikt worden 😉. Zie de readme.

**Comment by phnpost** [comment]
Hallo, Sorry. Sinds de een na laatste update zijn al mijn sensors Unavailable geworden. ik dacht dat het aan woerden-oudewater zou liggen. Moet ik dan in de configuration een andere provider invullen? Sorry

**Comment by xirixiz** [comment]
Correct.

```
provider: woerden
```

**Comment by phnpost** [comment]
Je bent geweldig! dank je wel
