### ISSUE TITLE
PMD sensor no longer available

### ISSUE THREAD

**Issue by P-Verbrugge** [xirixiz/homeassistant-afvalwijzer#273]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

After the last update, I noticed that the pmd sensor is no longer available.

### Expected behaviour

Expected all sensors to be available for all types of trash. Only PMD is nog longer available.

### Actual behaviour

PMD sensor for Mijn Afvalwijzer (https://www.mijnafvalwijzer.nl/) is no longer loading.

### Version

* HASS version: 2024.2.5
* Component version: 2024.2.1
* Useful system info: 

### HASS logs

* logger -> logs -> custom_components.afvalwijzer: debug in you configuration.yaml

**Comment by xirixiz** [comment]
Does the PMD entity exist on myafvalwijzer itself?
If you can share (DM) your postcal code and your house number with me, I can have a look.
What does the logging tell you in debug mode?

**Comment by KentuckyMC** [comment]
Got the same issue lately. Weird thing is, that I can't see the PMD either on afvalwijzer itself. Any idea why that is?

**Comment by KentuckyMC** [comment]
![Screenshot_20240408_221316_Chrome](https://github.com/xirixiz/homeassistant-afvalwijzer/assets/36470908/a804bfff-bc84-484a-8ba7-08b5c8675a67)
Pmd gone

**Comment by xirixiz** [comment]
When PMD is not available on mijnafvalwijzer itself, then also this component cannot retrieve the data. 
Ofcourse it's impossible to fetch non existing data :).

When this is the case, I advice you to reach out to mijnafvalwijzer to have this fixed. Once it's fixed, the issue will aslo be fixed for this component.

**Comment by KentuckyMC** [comment]
I see, at afvalwijzer they changed it from PMD to PBD seems like (Plastic, Blik, Drinkpakken). Will this integration pick up the new format automatic?
