### ISSUE TITLE
Nijkerk naar Burgerportaal

### ISSUE THREAD

**Issue by Sthroos** [xirixiz/homeassistant-afvalwijzer#278]
### Request

Gemeente Nijkerk stopt met afvalwijzer en gaat over naar Burgerportaal.

Als iemand mij kan helpen waar ik de data vandaan kan halen, kan ik een commit doen (lijkt erop alsof er enkel iets gewijzigd moet worden cf Assen https://github.com/xirixiz/homeassistant-afvalwijzer/pull/260/commits/474184bedc0f152298514ff0304dd6c1d24d3e03)

**Comment by xirixiz** [comment]
Hi @Sthroos dat moet wel lukken. Kom ik vandaag even op terug.

**Comment by ethemcemozkan** [comment]
@xirixiz https://postcodebijadres.nl/nijkerk Volgens mij kun je hier alle postcode vinden.

**Comment by Sthroos** [comment]
@xirixiz  Inderdaad wat @ethemcemozkan al zegt; dit zijn de postcodes van Nijkerk. 3860 3861 3862 en 3863.

**Comment by markvdlaan** [comment]
gemeente nijkerk heb ik kunnen toevoegen: https://github.com/xirixiz/homeassistant-afvalwijzer/pull/279

**Comment by xirixiz** [comment]
Release! Thanks @markvdlaan!

https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/2024.06.01

**Comment by Eraser127** [comment]
Moet ik nog iets aanpassen? Mijn sensors staan nog op 'niet beschikbaar'.

**Comment by ethemcemozkan** [comment]
> Moet ik nog iets aanpassen bij platform ofzo? Al mijn afvalwijzer sensors zijn 'niet beschikbaar'.
> 
> 

I think the provider must be nijkerk.

**Comment by Eraser127** [comment]
@ethemcemozkan Check, ik heb idd nu bij provider 'nijkerk' gezet en nu werkt het gewoon. @xirixiz Moet dit misschien niet ook los op de infopagina komen te staan van afvalwijzer?
