### ISSUE TITLE
Need help with Doorn

### ISSUE THREAD

**Issue by MrAredhone** [xirixiz/homeassistant-afvalwijzer#280]
### Request

Hay There im still quite new to homeassistant and i was trying to add doorn i lookt at your configuration.yaml
but dident get any wiser i got 
`
sensor:
  - platform: afvalwijzer
    provider: mijnafvalwijzer # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, afvalstoffendienstkalender or rova
    postal_code: DoorPostal # (required, default = '')
    street_number: 1 # (required, default = '')
    suffix: "" # (optional, default = '')
    exclude_pickup_today: true # (optional, default = true) to take or not to take Today into account in the next pickup.
    default_label: geen # (optional, default = geen) label if no date found
    id: "" # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
    exclude_list: "" # (optional, default = '') comma separated list of waste types (case ignored). F.e. "papier, gft"

`

**Comment by xirixiz** [comment]
Hi @MrAredhone nice that you are exploring HASS and this addon as well. With 3 backticks (these ` ), you can add some code which is better readable for the audience ;).

```
sensor:
  - platform: afvalwijzer
    provider: mijnafvalwijzer
    postal_code: 3941NB
    default_label: "Geen"
    street_number: 74
```

This should work (used a postal code an street number I randomly found). Be aware that sensor only may be specified once in the ```configuration.yaml``` file. 

Please share your logfiles as well if it's not working properly so I can guide you better.

**Comment by MrAredhone** [comment]
Thank You it works and looks great (now i only need a way to get data from google sheets into homeassistant .... askt here since you never know somone might know how)

**Comment by xirixiz** [comment]
Ouch, that I don't know. However, there is a big community where knowledgable ppl are able to help out with these kind of topics. https://community.home-assistant.io/

Happy HASSing :)
