### ISSUE TITLE
Integrate 2024.12.12Beta3 feature easy_time.jinja into main

### ISSUE THREAD

**Issue by mhoogenbosch** [xirixiz/homeassistant-afvalwijzer#281]
### Request

In beta3 of 2024.12.12 a feature to change the dates to Dutch (and possibly other as well) has been introduced with the integration of easy_time. In the last two versions however this feature isn't available so it seems. I would love to see this being integrated into main.

The feature allows me to create this dashboard item:

![image](https://github.com/xirixiz/homeassistant-afvalwijzer/assets/36899598/60f91110-00bf-4c8b-b1f2-0a8f4af29bd2)

**Comment by xirixiz** [comment]
Yeah, I`m planning to migrate this to the main release. It needed some testing and rework.
Also the branch containing this feature is out of sync with the main branch.
Will spend some time on this the upcoming week.

**Comment by xirixiz** [comment]
Oke, I expected more issues, but it seems to workout fine after some minor updates:
https://github.com/xirixiz/homeassistant-afvalwijzer/pull/282
