### ISSUE TITLE
address not found or no data available

### ISSUE THREAD

**Issue by 1mfaasj** [xirixiz/homeassistant-afvalwijzer#294]
### The problem

Hi, sindskort zijn de afval sensors unknown met als error: `Address not found or no data available!`
enig idee waar dit mee te maken heeft?
ik heb meerdere adressen geprobeerd met postcode "6129".

### Version of afvalwijzer integration having the issue?

2024.06.02

### Version of Home Assistant Core having the issue?

2024.07

### Anything in the logs that might be useful for us?

```txt
Logger: custom_components.afvalwijzer.const.const
Bron: custom_components/afvalwijzer/collector/mijnafvalwijzer.py:36
integratie: afvalwijzer (documentatie, problemen)
Eerst voorgekomen: 08:51:58 (1 gebeurtenissen)
Laatst gelogd: 08:51:58

Address not found or no data available!


& deze fout (heb de api key, postcode en huisnummer even eruit gehaald)


Logboek Details (FOUT)
Logger: homeassistant.components.sensor
Bron: helpers/entity_platform.py:364
integratie: Sensor (documentatie, problemen)
Eerst voorgekomen: 08:51:58 (1 gebeurtenissen)
Laatst gelogd: 08:51:58

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 37, in get_waste_data_raw
    raise KeyError
KeyError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/afvalwijzer/sensor.py", line 68, in async_setup_platform
    collector = await hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 43, in __init__
    waste_data_raw = mijnafvalwijzer.get_waste_data_raw(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/collector/mijnafvalwijzer.py", line 39, in get_waste_data_raw
    raise KeyError(f"Invalid and/or no data received from {url}") from err
KeyError: 'Invalid and/or no data received from https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=XXX&method=postcodecheck&postcode=XXX&street=&huisnummer=XXX&toevoeging=&app_name=afvalwijzer&platform=web&afvaldata=2024-07-09&langs=nl&'
```

**Comment by SMOKEz8z8** [comment]
I had the same error, tried a few things. Came to the conclusion the mijnafvalwijzer.nl does no longer report on my postal code, think their link with rwm.nl is no longer working.

**Comment by 1mfaasj** [comment]
update: also afvalstoffendienstkalender doesn't work anymore.

**Comment by Edwin-Dijk-Innovatech** [comment]
Seeing the same behaviour here for 6137, was working before I updated my afvalwijzer integration. (not saying this update caused it, might just be a new parse because of the update)

**Comment by Edwin-Dijk** [comment]
Seeing the same behaviour here for 6137, was working before I updated my afvalwijzer integration. (not saying this update caused it, might just be a new parse because of the update)

**Comment by M1sterGlass** [comment]
Also here at 6137! My zipcode stopped working on https://www.mijnafvalwijzer.nl, I used to be able to lookup my zipcode here.

My trash is collected by RWM and I can go to https://rwm.nl/wanneer and click on "Add to calendar" and get the url to the webcal
webcal://rwm.nl/ical/<random number>

Is there a way to add a webcal to afvalwijzer?

**Comment by Eraser127** [comment]
Same as above with zipcode 3861, sensors in home assistant are unavailable.

**Comment by DynaSpan** [comment]
I just called RWM, they said there is an issue with reporting the dates to mijnafvalwijzer and they're working on it. Couldn't give an ETA on when it's fixed though.

**Comment by 1mfaasj** [comment]
I just switched to afvalinfo (hacs), this one works.

**Comment by jayjayvm** [comment]
Same her error: 

2024-07-13 23:23:08.463 ERROR (SyncWorker_4) [custom_components.afvalwijzer.const.const] Address not found or no data available!

Hope it gets solved.

**Comment by jayjayvm** [comment]
I have no afvalinfo in hacs????

**Comment by 1mfaasj** [comment]
> Same her error:
> 
> 2024-07-13 23:23:08.463 ERROR (SyncWorker_4) [custom_components.afvalwijzer.const.const] Address not found or no data available!
> 
> Hope it gets solved.

https://github.com/heyajohnny/afvalinfo

**Comment by Wiley99** [comment]
> I just called RWM, they said there is an issue with reporting the dates to mijnafvalwijzer and they're working on it. Couldn't give an ETA on when it's fixed though.

I've sent them an e-mail but their contact center person doesn't seem to understand what's wrong. They just say 'we don't support afvalwijzer anymore.' (the website)

**Comment by Edwin-Dijk** [comment]
> > I just called RWM, they said there is an issue with reporting the dates to mijnafvalwijzer and they're working on it. Couldn't give an ETA on when it's fixed though.
> 
> I've sent them an e-mail but their contact center person doesn't seem to understand what's wrong. They just say 'we don't support afvalwijzer anymore.' (the website)

This might be crucial as RWM directly is not supported so we (I in this case) always used mijnafvalwijzer as provider. If RWM is planning on never supporting mijnafvalwijzer (the site) anymore we also can't use this addon anymore in our postal region

**Comment by DynaSpan** [comment]
So in light of the recent comments I called again with RWM, and they also confirmed that mijnafvalwijzer **will not** be supported anymore, because of some issues...

So I guess I will try to create a PR to re-add RWM support via their own API, if possible.

**Comment by DynaSpan** [comment]
Update: I've created a PR to re-add RWM support: #298

**Comment by 1mfaasj** [comment]
I will close the ticket because there is a PR to fix the issue
otherwise, this other integration I mentioned before is already using the RWM rest api:
https://github.com/heyajohnny/afvalinfo
and that one works.
good luck everyone
