### ISSUE TITLE
Sensor date format changed from local HA format (DD-MM-YYYY) to YYYY-MM-DD

### ISSUE THREAD

**Issue by canedje** [xirixiz/homeassistant-afvalwijzer#295]
### The problem

At the last update the date format for waste sensors chenged.
It is not using the HA User settings anymore see title
![image](https://github.com/user-attachments/assets/f6a4ed01-accb-48f9-bf20-70aca815f985)

### Version of afvalwijzer integration having the issue?

Afvalwijzer 2024.06.02

### Version of Home Assistant Core having the issue?

core- 2024.7.2

### Additional information

Because of this my automations suddenly didn't work anymore

**Comment by Rinaldo-lsw** [comment]
I have the same problem. it's returning me 'unavailable' now on all sensors.
I noticed the code is in python so I might be able to fix it when I have some free time, or we need to wait a bit.

**Comment by Rinaldo-lsw** [comment]
NVM, for me it was the fact that I had to change provider.
For somer 'mijnafvalwijzer' didn't supply info anymore for Nijkerk, so I had to change it to Nijkerk provider :D

**Comment by Anonymoesje** [comment]
This changed because Nijkerk switched to Burgerportaal. 
Fixed in https://github.com/xirixiz/homeassistant-afvalwijzer/pull/279

**Comment by xirixiz** [comment]
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!
