### ISSUE TITLE
Meppel nu op afvalwijzer 

### ISSUE THREAD

**Issue by EWK1** [xirixiz/homeassistant-afvalwijzer#308]
### The problem

Meppel moet nu de data uit afvalwijzer halen, andere database is leeg

### Version of afvalwijzer integration having the issue?

5.3.7

### Version of Home Assistant Core having the issue?

2024.8

**Comment by gielk** [comment]
Meppel doet het inderdaad niet meer.

**Comment by xirixiz** [comment]
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!

**Comment by gielk** [comment]
Deze kan worden gesloten. Meppel kan weg uit de lijst van providers. Misschien is het een optie om tijdens het instellen in de UI een lijst met providers te tonen ipv deze zelf in te vullen?

**Comment by xirixiz** [comment]
Ja, dat kan misschien ook wel inderdaad. Goed idee. Neem ik mee in de volgende release.

**Comment by EWK1** [comment]
> Deze kan worden gesloten. Meppel kan weg uit de lijst van providers. Misschien is het een optie om tijdens het instellen in de UI een lijst met providers te tonen ipv deze zelf in te vullen?

Waarom kan meppel weg uit de lijst van providers?
