### ISSUE TITLE
Double sensor name for gft

### ISSUE THREAD

**Issue by Eraser127** [xirixiz/homeassistant-afvalwijzer#309]
### The problem

When GFT is next for pickup, it shows 'gft, gft' on the status at 'afvalwijzer tomorrow'. Does this come from within the afvalwijzer code?
<img width="539" alt="Knipsel" src="https://github.com/user-attachments/assets/b04ed0cb-2417-4475-a496-a6807420ce40">

I found the code below, could that be the issue?:

<img width="448" alt="Knipsel1" src="https://github.com/user-attachments/assets/e6d62bd8-4454-4c77-84d6-d70f113a33c0">

### Version of afvalwijzer integration having the issue?

2024.06.02

### Version of Home Assistant Core having the issue?

2024.8.2

**Comment by DynaSpan** [comment]
What provider do you use? It might be different types of waste collection that gets renamed to the same new entity. For example: normal `gft` and things like tree branches etc.

**Comment by Eraser127** [comment]
I use Nijkerk as provider. With 'array with waste types' you mean the mapping of wastetypes as in the screenshot?

**Comment by DynaSpan** [comment]
Well, e.g. say your provider has a collection date for normal gft and things like branches from trees etc. The naming of those items might get renamed to the same gft if they're in `waste_mapping` array and point to the same name.

To prevent duplicates, there are 2 options:

1. Make some edits to make sure it doesn't duplicate the value but keeps the original naming (so `gft` and `takken` or something like that)
2. Or add some extra code which checks the waste types that will be retrieved tomorrow, and remove any duplicates from that array

Could you provide the raw response from your waste provider? Maybe we can see what's the issue there.

**Comment by Eraser127** [comment]
1. So that would best be done in the exclude-list of Afvalwijzer?
2. Dont know how, but have to look into that.

The regular afval app only mentions 'Groeten- Fruit- en Tuinafval', so no others.

**Comment by Eraser127** [comment]
Today was another pickup date, but now it says just `gft`.

<img width="560" alt="Knipsel" src="https://github.com/user-attachments/assets/fed24145-aeb7-4185-885c-00d2ae7ec6ee">

If it'll happen again I'll look into the array.
