### ISSUE TITLE
FYI: ROVA is no longer on Afvalwijzer

### ISSUE THREAD

**Issue by pippyn** [xirixiz/homeassistant-afvalwijzer#311]
### Feature request

Hi @xirixiz,

As an FYI: ROVA is no longer on Afvalwijzer. It uses a custom API from now on.
You can look at my integration if you need help with the new API:
https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/blob/b9898ade57533136f63a0a7c37e1f36c77625968/custom_components/afvalbeheer/API.py#L1062

Kind regards,
Pippijn

### What version of the integration are you using?

N.A.

**Comment by xirixiz** [comment]
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!

**Comment by xirixiz** [comment]
Added to a new release. Thanks pippyn, very much apreciated!

**Comment by jdschuitemaker** [comment]
ROVA is still not updating for me.:
![image](https://github.com/user-attachments/assets/5144e1fa-2feb-4562-aacd-b541c63c1017)

Do I need to change anything in my config?
![image](https://github.com/user-attachments/assets/1d890289-0b84-49f8-92e7-e0795bc44808)
