### ISSUE TITLE
Cyclus no longer available

### ISSUE THREAD

**Issue by jowel81** [xirixiz/homeassistant-afvalwijzer#316]
### The problem

The (previously working) provider Cyclus shows as not available. I suspect the website/API has changed, at least the URL did to https://cyclusnv.nl/afvalkalender.

### Version of afvalwijzer integration having the issue?

2024.06.02

### Version of Home Assistant Core having the issue?

2024.9.1

**Comment by xirixiz** [comment]
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!

**Comment by xirixiz** [comment]
Fixed. Next release available (end of this week)
