### ISSUE TITLE
One icon is not showing

### ISSUE THREAD

**Issue by m3tc0n** [xirixiz/homeassistant-afvalwijzer#318]
### The problem

Hi, I have a issue with one of the icons (rest-afval) for a long time now. See this image:

![IMG_20240808_122154](https://github.com/user-attachments/assets/1b20e7ec-c186-4771-a9a2-32206c8af338)

I have the icons stored in the /www/ folder in home assistant, see the image:

![IMG_20240808_122259](https://github.com/user-attachments/assets/c9dd7e74-8eed-4d67-84d1-bcd6f815539c)

This is how my customize.yaml file looks like:

![IMG_20240808_122236](https://github.com/user-attachments/assets/37175a80-339e-4a05-91c7-246cb94c37b1)

I have already tried to upload the rest.png again and change the name, but that didnt work. How to fix this issue? TIA!

### Version of afvalwijzer integration having the issue?

2024.06.02

### Version of Home Assistant Core having the issue?

2024.9.2

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

-

**Comment by Eraser127** [comment]
Have you tried replacing rest.png with a completely diferent picture?

**Comment by m3tc0n** [comment]
I had something wrong in my entity naming. It is all fixed now.
