### ISSUE TITLE
Restafval not available

### ISSUE THREAD

**Issue by AlexBedeker-1** [xirixiz/homeassistant-afvalwijzer#324]
### The problem

Since november 2024 gemeente Almere changed their Restafval into Rest+pmd by the looks of https://almeremodules.ximmio.com.
Could this be the reason why Restafval doesn't have any value anymore?

### Version of afvalwijzer integration having the issue?

afvalwijzer - 2024.06.02

### Version of Home Assistant Core having the issue?

2024.10.04

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.sensor
Bron: runner.py:189
integratie: Sensor (documentatie, problemen)
Eerst voorgekomen: 11:36:26 (1 gebeurtenissen)
Laatst gelogd: 11:36:26

Setup of sensor platform afvalwijzer is taking over 10 seconds.
```

**Comment by Wtje** [comment]
AlexBedeker-1 have you found the solution? I have the same problem with the Restafval sensor since they've changed it to Rest+pmd.

**Comment by AlexBedeker-1** [comment]
Updated to the latest version.
With the new config I saw the sensor is called bulkyrestwaste.

With the new version everything is working again!
