### ISSUE TITLE
Organic waste pickup selection

### ISSUE THREAD

**Issue by tieskuh** [xirixiz/homeassistant-afvalwijzer#325]
### Feature request

Within the Afvalwijzer app, I have to select if we want to have our organic waste picked up a few days before the pickup date. It would be great to be able to do that within HA. There is no authentication needed within the app. 

Screenshot of the app:
![7F8BBCE7-9113-48E0-B619-BB432D152BA8](https://github.com/user-attachments/assets/1616be55-4e55-4ff1-9cd2-558ddff42d71)

### What version of the integration are you using?

2024.06.02

**Comment by xirixiz** [comment]
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!

**Comment by xirixiz** [comment]
Can you perhaps share a valid postal code and street number in your area so I can have a look at the API data?

**Comment by tieskuh** [comment]
Thanks for looking into it!
You can use 5482ZX27

**Comment by xirixiz** [comment]
Helaas! In de API data staat niets over optionele pickups. Daar staat alleen alles in van wat er aan geplande ophaaldagen is. Jammer, want ik zag het zojuist bij ons eigen adres ook voorbij komen.

**Comment by tieskuh** [comment]
Even voor de duidelijkheid: Het zijn wel geplande pickups maar of ze daadwerkelijk langskomen kun je met de switch aangeven. Ik denk dus dat het niet zozeer een apart bericht is dat je uit de API krijgt, maar juist een bericht dat je naar de API stuurt. Als je deze postcode in de Afvalwijzer app invoert, zie je hoe de interface eruitziet. Of die switch getoond wordt, lijkt me toch iets dat uit de API terug moet komen. Of zou het hardcoded zijn?
