### ISSUE TITLE
Rucphen and possibly Roosendaal to saver

### ISSUE THREAD

**Issue by AgreedBog** [xirixiz/homeassistant-afvalwijzer#326]
### The problem

Gemeenten die afval dienst saver gebruiken schakelen over naar hun eigen app "saver" per 1 1 25 is er iemand handig genoeg om saver als provider toe te voegen 

### Version of afvalwijzer integration having the issue?

Latest 

### Version of Home Assistant Core having the issue?

2024.11

**Comment by bkbartk** [comment]
I don't have time to build this, (I still can't work with python)
But a get based on zipcode number `https://saver.nl/adressen/4651WZ:2`
returns: `bagid`
`[{"bagid":"0851200000010511","postcode":"4651WZ","huisnummer":2,"huisletter":"","toevoeging":"","description":"Oost-Havendijk 2, 4651WZ Steenbergen","straat":"Oost-Havendijk","woonplaats":"Steenbergen","woonplaatsId":1405,"gemeenteId":851,"latitude":51.590284,"longitude":4.312886}]`
bagid you can use here
`https://saver.nl/rest/adressen/0851200000010511/afvalstromen`
or
`https://saver.nl/rest/adressen/0851200000010511/kalender/2024`
and you'll find a valid response.
holidays you can find this way
`https://saver.nl/rest/feestdagen/2023-12-26/2025-01-06`

for analyzing the api i just checked this page
`https://saver.nl/afvalkalender`

**Comment by Mariusthvdb** [comment]
As a long time user of this integration (and just installed the new Config flow version (btw thank you @xirixiz Bram!) I do hope we can get the new provider into Afvalwijzer......

please check if Saver can be incorporated?
there already are type no longer available, I had figured them to be the regular "next year schedule issue", but now realize this might be because of the change??

<img width="515" alt="Scherm­afbeelding 2024-12-05 om 16 11 54" src="https://github.com/user-attachments/assets/9c9c37c5-5a01-46f2-9065-58e9215b07e4">

**Comment by niekniek89** [comment]
Same problem for me.
I am currently still with "mijnafvalwijzer", but have to use "Saver" as of 1-1-2025.
For 1 single sensor (which has a date from 2025), it no longer retrieves information.
For me, all sensors will no longer work from now on.
Hopefully someone can add Saver to this nice integration.

**Comment by Mariusthvdb** [comment]
Bram (xirixiz ) is aware  and checking this issue, see his [response](https://community.home-assistant.io/t/garbage-pickup-date-mijnafvalwijzer-nl-custom-component/34631/964?u=mariusthvdb) in the community

**Comment by xirixiz** [comment]
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!

**Comment by bkbartk** [comment]
> Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!

Don’t blame your laptop. It’s probably related to a bug in GitHub not showing the full feed.
