### ISSUE TITLE
Rd4  (Simpelveld) doesnt work after update 2024.12.01

### ISSUE THREAD

**Issue by hermanf72** [xirixiz/homeassistant-afvalwijzer#329]
### The problem

Complete app doesn't work anymore. All entities are broke/non existent. 

### Version of afvalwijzer integration having the issue?

2024.12.01

### Version of Home Assistant Core having the issue?

1224.12.0

**Comment by AussiSG** [comment]
Experiencing the same... 

The error seems to be : 

`2024-12-06 18:57:25.032 ERROR (MainThread) [custom_components.afvalwijzer.const.const] No discovery information provided; sensors cannot be created.`

**Comment by vincentkoevoets** [comment]
I missed the release note saying that you have to delete your current configuration of Afvalwijzer, and re-add it via Add integration flow. Info is here https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/2024.12.01. Maybe you have missed it too?
Working for me again now.

**Comment by hermanf72** [comment]
> I missed the release note saying that you have to delete your current configuration of Afvalwijzer, and re-add it via Add integration flow. Info is here https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/2024.12.01. Maybe you have missed it too? Working for me again now.

Yes, that’s correct! Everything is working fine now. Make sure to delete any non-functioning entities before reconfiguring. Otherwise, you might end up with duplicate entity names ending in "_2," which can disrupt your scripts.

**Comment by vincentkoevoets** [comment]
Yes that happened to me too. I removed them, and reconfigured the Afvalwijzer again and then all sensors were back with their original name. Don't forget to close the issue!
