### ISSUE TITLE
afvalwijzer doesnt work after update 2024.12.01 (provider Mijnafvalwijzer)

### ISSUE THREAD

**Issue by defisit** [xirixiz/homeassistant-afvalwijzer#330]
### The problem

After the update, no sensor are created. Have rebooted HA several times.

### Version of afvalwijzer integration having the issue?

2024.12.01

### Version of Home Assistant Core having the issue?

2024.12.0

### Anything in the logs that might be useful for us?

```txt
This error originated from a custom integration.

Logger: custom_components.afvalwijzer.const.const
Source: custom_components/afvalwijzer/sensor.py:48
integration: Afvalwijzer (documentation, issues)
First occurred: 10:41:06 (1 occurrences)
Last logged: 10:41:06

No discovery information provided; sensors cannot be created.
```

### Additional information

![image](https://github.com/user-attachments/assets/9fd460f2-268b-4009-a7f2-90f09bdeca2f)

**Comment by willem-wismans** [comment]
Same here! I reloaded/redownloaded the old version 2024.06.02 and everything is working again. So don't update (yet) :)
Redownloading is done through HACS integration > Search Afvalwijzer > ... dots on the right side > redownload. You can select a different version after that

**Comment by Calimerorulez** [comment]
In my installation, the complete integration disappeared, so I redownloaded and it started working again for PreZero :)

**Comment by canedje** [comment]
For me it is working, except I can not change the standard configuration.
See my bug in this topic

**Comment by vincentkoevoets** [comment]
I missed the release note saying that you have to delete your current configuration of Afvalwijzer, and re-add it via Add integration flow. Info is here https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/2024.12.01. Maybe you have missed it too?
Working for me again now.

**Comment by defisit** [comment]
> I missed the release note saying that you have to delete your current configuration of Afvalwijzer, and re-add it via Add integration flow. Info is here https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/2024.12.01. Maybe you have missed it too? Working for me again now.

I completely missed that. It's now working for me again for version 2024.12.01.

**Comment by vincentkoevoets** [comment]
Great! Then this one can be closed, right?

**Comment by defisit** [comment]
Resolved after having followed procedure as per release notes for 2024.12.01
