### ISSUE TITLE
Afvalwijzer 2024.12.01 - Error doing job: Future exception was never retrieved (None)

### ISSUE THREAD

**Issue by casakampa** [xirixiz/homeassistant-afvalwijzer#331]
### The problem

I updated this custom component to the newest release and added the afvalwijzer via the config flow. This went as expected, but every 4 hours  this error appears in the logs.

This error appears on two different instances of Home Assistant, in two different households.

### Version of afvalwijzer integration having the issue?

afvalwijzer-2024.12.01

### Version of Home Assistant Core having the issue?

core-2024.12.1

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant
Bron: core.py:891
Eerst voorgekomen: 13:41:58 (2 gebeurtenissen)
Laatst gelogd: 17:41:58

Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/sensor.py", line 82, in <lambda>
    hass, lambda _: hass.async_add_executor_job(data.update), update_interval)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 891, in async_add_executor_job
    tracked = asyncio.current_task() in self._tasks
              ~~~~~~~~~~~~~~~~~~~~^^
RuntimeError: no running event loop
```

## System Information

version | core-2024.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.63-haos
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 30.8 GB
disk_used | 6.3 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.1), Terminal & SSH (9.15.0), Studio Code Server (5.17.3), Piper (1.5.2)

</details>

**Comment by Braakie** [comment]
I have the same error

`Core: 2024.12.3
Supervisor: 2024.11.4
Operating: System 14.0
Frontend: 20241127.8
Afvalwijzer: 2024.12.01`

**Comment by Xavier82** [comment]
Same issue here also.
Core: 2024.12.3
Supervisor: 2024.12.0
Home Assistant OS 14.0
Frontend: 20241127.8
Afvalwijzer: 2024.12.01

**Comment by xirixiz** [comment]
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!

**Comment by xirixiz** [comment]
Fixed. New release available later this week.
