### ISSUE TITLE
Item in 2025 are not shown

### ISSUE THREAD

**Issue by Houdoe** [xirixiz/homeassistant-afvalwijzer#332]
### The problem

On rova.nl is stated that the paper collection is on jan-3rd. HA reports: 'geen' (unknown)

### Version of afvalwijzer integration having the issue?

2024-12-01

### Version of Home Assistant Core having the issue?

2024-12-1

### Anything in the logs that might be useful for us?

```txt
none
```

### Additional information

I removed the integration, and checked that the afvalwijzer* enteties were removed. Reinstalled the integration. No change.
I ticked the 'use ISO dateformat' : no change.

![afvalwijzer](https://github.com/user-attachments/assets/871095af-3a72-4f1e-af23-1e8868b6b572)

**Comment by xirixiz** [comment]
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!

**Comment by xirixiz** [comment]
Hi, I already have a fix ready for this. Rova will be different for 2025. New release of this component will be available somewhere later this week.
