### ISSUE TITLE
Entities unavailable since last update

### ISSUE THREAD

**Issue by Martijnsx** [xirixiz/homeassistant-afvalwijzer#333]
### The problem

Since last update all the entities are unavailable. I have set Doetinchem as gemeente.

### Version of afvalwijzer integration having the issue?

Afvalwijzer 2024.12.01

### Version of Home Assistant Core having the issue?

2024.12.0

**Comment by Martijnsx** [comment]
No i do not think so. 

Has there been a change to this HACS addon? I added this integration via the normal integration page from HA but i could not get entities with data.

**Comment by steffex** [comment]
I have the same issue. Also Doetinchem set as municipality

**Comment by MonkNL** [comment]
The same issue occurred; I rolled back to the previous version (2024.06.02), and the sensors are working again.

**Comment by 5kms** [comment]
I have to second this. I just noticed that since 2024.12.01, installed on December 9th, all Afvalwijzer entities are unavailable and show the (dutch) message "**Deze entiteit is niet meer beschikbaar vanuit de afvalwijzer integratie. Wanneer de entiteit niet meer in gebruik is, kan deze vanuit de instellingen verwijderd worden.**"
There has been no change to the Configuration.yaml for about 2 years now, and the recent change in days in Tilburg, was picked up without any issue. It is only now it refuses to function. I installed the HA 2024.12.2 update this morning, with a reboot of the system. No change in behaviour.

**Comment by aveenema** [comment]
same here. no data (unavailable) since last upgrade to 2024.12.01.
Log shows: no discovery information provided; sensors cannot be created.
no changes in configuration.yaml
locationprovider: mijnafvalwijzer and zipcode.

**Comment by eleutscher** [comment]
Yep, same

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/afvalwijzer/sensor.py", line 57, in async_setup_entry
    await _setup_sensors(hass, entry.data, async_add_entities)
  File "/config/custom_components/afvalwijzer/sensor.py", line 77, in _setup_sensors
    await hass.async_add_executor_job(data.update)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/sensor.py", line 130, in update
    collector = MainCollector(
        provider,
    ...<6 lines>...
        default_label,
    )
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 98, in __init__
    waste_data_raw = ximmio.get_waste_data_raw(
        self.provider,
    ...<2 lines>...
        self.suffix,
    )
  File "/config/custom_components/afvalwijzer/collector/ximmio.py", line 36, in get_waste_data_raw
    uniqueId = response["dataList"][0]["UniqueId"]
               ~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by jeroen-klaver** [comment]
Same here. The version from june works again.

**Comment by tuupos** [comment]
New version does works here....

as by instructions mentioned by author @ latest commit : **remove old configuration, restart, then follow the config flow by adding the integration**

I had the integration set up primarily as follows:

- platform: afvalwijzer
    provider: mijnafvalwijzer        # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer or afvalstoffendienstkalender
    postal_code: !secret postcode    # (required, default = '')
    street_number: !secret nummer    # (required, default = '')
    suffix: ''                       # (optional, default = '')
    #include_date_today: false       # (optional, default = false) to take or not to take Today into account in the next pickup.
    exclude_pickup_today: false     # (optional, default = true) to take or not to take Today into account in the next pickup.
    default_label: Geen              # (optional, default = Geen) label if no date found
    id: ''                           # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS      
    
    

1.   I deleted all these lines.  (removed the entire platform sensor afvalwijzer)
2.   Had to manually remove the older entities attached to the afvalwijzer (before I added the integration and got a lot of duplicates with ending _2). So normally this is not necessary.
3. reboot/restart home assistant
4. install the afvalwijzer integration. and follow the config flow.
5. voila.... I live also in Doetinchem and works like a charm.

**Comment by vincentkoevoets** [comment]
> New version does works here....
> 
> as by instructions mentioned by author @ latest commit : **remove old configuration, restart, then follow the config flow by adding the integration**
> 
> I had the integration set up primarily as follows:
> 
> * platform: afvalwijzer
>   provider: mijnafvalwijzer        # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer or afvalstoffendienstkalender
>   postal_code: !secret postcode    # (required, default = '')
>   street_number: !secret nummer    # (required, default = '')
>   suffix: ''                       # (optional, default = '')
>   #include_date_today: false       # (optional, default = false) to take or not to take Today into account in the next pickup.
>   exclude_pickup_today: false     # (optional, default = true) to take or not to take Today into account in the next pickup.
>   default_label: Geen              # (optional, default = Geen) label if no date found
>   id: ''                           # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
> 
> 1. I deleted all these lines.  (removed the entire platform sensor afvalwijzer)
> 2. Had to manually remove the older entities attached to the afvalwijzer (before I added the integration and got a lot of duplicates with ending _2). So normally this is not necessary.
> 3. reboot/restart home assistant
> 4. install the afvalwijzer integration. and follow the config flow.
> 5. voila.... I live also in Doetinchem and works like a charm.

This is the way

**Comment by 5kms** [comment]
Well, it is not actually "as by instructions"

The change log mentions:
**Added config flow configuration (remove old configuration, restart, then follow the config flow by adding the integration)**
A) it is ADDED, so in addition to existing functionality. Therefore there is no change needed when I do not intent to use this new 'config flow configuration (whatever that is)
B) the actions between the brackets, are not stated as instructions. It appears to be more like the actions the author has taken to create this new option.
C) nowhere there is a mention of a breaking change. That is the only thing that somebody needs to scan for, when updating. So when a non breaking change, breaks the software, it is a major bug.

**Comment by tuupos** [comment]
@5kms you are right.

**Comment by vincentkoevoets** [comment]
I also think @5kms is right, but we should move this to discussions then? And this one can be closed.

**Comment by Martijnsx** [comment]
I am a little bit lost. What are the steps such that we can solve it ourselfs now?

**Comment by vincentkoevoets** [comment]
The steps that @tuupos did worked for me to get things running again.

**Comment by ricoroodenburg** [comment]
> New version does works here....
> 
> as by instructions mentioned by author @ latest commit : **remove old configuration, restart, then follow the config flow by adding the integration**
> 
> I had the integration set up primarily as follows:
> 
> * platform: afvalwijzer
>   provider: mijnafvalwijzer        # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer or afvalstoffendienstkalender
>   postal_code: !secret postcode    # (required, default = '')
>   street_number: !secret nummer    # (required, default = '')
>   suffix: ''                       # (optional, default = '')
>   #include_date_today: false       # (optional, default = false) to take or not to take Today into account in the next pickup.
>   exclude_pickup_today: false     # (optional, default = true) to take or not to take Today into account in the next pickup.
>   default_label: Geen              # (optional, default = Geen) label if no date found
>   id: ''                           # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
> 
> 1. I deleted all these lines.  (removed the entire platform sensor afvalwijzer)
> 2. Had to manually remove the older entities attached to the afvalwijzer (before I added the integration and got a lot of duplicates with ending _2). So normally this is not necessary.
> 3. reboot/restart home assistant
> 4. install the afvalwijzer integration. and follow the config flow.
> 5. voila.... I live also in Doetinchem and works like a charm.

Thanks! Only steps 1 and 4 were enough for me.

**Comment by 5kms** [comment]
I agree that this bug should be closed.

I also like to emphasise that, even though I found the release notes lacking, i still very much appreciate all the effort the developer has put into this integration, for which I like to express my thanks.

As a minor note, but on the same line, the examples in the documentation still show the old configuration.yaml requirement.

**Comment by xirixiz** [comment]
Thanks @5kms. Next time I`ll try to improve the release notes. Thanks for the help all. Somehow I missed this open issue.
