### ISSUE TITLE
sensor.afvalwijzer_today does not show correct value (Areareiniging)

### ISSUE THREAD

**Issue by zzzimple** [xirixiz/homeassistant-afvalwijzer#334]
### The problem

I'm using Areareiniging and dates for most garbage sensors are correct (papier, restafval, pmd), except the value for "sensor.afvalwijzer_today" and "sensor.afvalwijzer_gft". 

Today (10/12/2024) GFT is collected but the sensor.afvalwijzer_today shows PMD.

Today (10/12/2024) sensor.afvalwijzer_gft shows "Geen" while it should be the date of today.

### Version of afvalwijzer integration having the issue?

2024.12.01

### Version of Home Assistant Core having the issue?

2024.12.1

**Comment by xirixiz** [comment]
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!

**Comment by xirixiz** [comment]
Duplicate: https://github.com/xirixiz/homeassistant-afvalwijzer/issues/348
