### ISSUE TITLE
Add support for Kliko Container Manager

### ISSUE THREAD

**Issue by stijnb1234** [xirixiz/homeassistant-afvalwijzer#337]
### Feature request

My municipality uses KlikoContainerManager (by Kliko Group) starting from 2025. If I'm correct this is not supported yet. Could you add support for it?

### What version of the integration are you using?

2024.12.01

### Additional information

https://klikocontainermanager.com/

My municipality uses a custom subdomain.

**Comment by xirixiz** [comment]
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!

**Comment by stijnb1234** [comment]
Haha no problem, sounds great :+1:

**Comment by sndrsmnk** [comment]
I have kind of implemented this. I'm gonna build a PR.

**Comment by stijnb1234** [comment]
Thanks, implementation works perfectly!
