### ISSUE TITLE
Added new line in Main Functions

### ISSUE THREAD

**Issue by Braakie** [xirixiz/homeassistant-afvalwijzer#338]
### Feature request

I would like to see a new line added to the main_functions.py with "gft & etensresten": "gft",

### What version of the integration are you using?

Afvalwijzer 2024.12.01

### Anything in the logs that might be useful for us?

```txt
No errors
```

### Additional information

I can't use my GFT sensor when I make formatted sensors for automations, I think that's because the "&" sign in the sensor name.
The sensor that is created for me by the integration is called sensor.afvalwijzer_gft_etensresten
while the current state of the sensor is: gft & etensresten

**Comment by xirixiz** [comment]
Code updated. Will be implemented in the next release (somewhere this week).

**Comment by Braakie** [comment]
Thank you very much
