### ISSUE TITLE
Update ruins configuration

### ISSUE THREAD

**Issue by realrolfje** [xirixiz/homeassistant-afvalwijzer#339]
### The problem

The new Afvalwijzer needed to be uninstalled and then re-installed and configured with the wizzard. Migration could be a bit more user friendly by taking existing configuration and migrating it to the new config if needed, without requiring user action.

After de-installing and re-installing the afvalwijzer, all the automations and alerts we set up to warn us about the waste pickup points are broken. The afvalwijzer integration shows "no entities" and does not update anymore.

This is a bit dissapointing.

### Version of afvalwijzer integration having the issue?

2024.12.01

### Version of Home Assistant Core having the issue?

2024.12.3

**Comment by adekloet** [comment]
https://github.com/xirixiz/homeassistant-afvalwijzer/issues/333#issuecomment-2537490865

**Comment by xirixiz** [comment]
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!
