### ISSUE TITLE
Use ISO date format not checked when using configure on integration

### ISSUE THREAD

**Issue by mvdwetering** [xirixiz/homeassistant-afvalwijzer#340]
### The problem

When adding the integration through the configflow I selected the option to use the ISO date format. However when I press Configure it is not checked. I guess this would also disable the option when I would save the form (I did not try it, was just checking what was behind the Configure button)

![image](https://github.com/user-attachments/assets/23ee3505-a2d7-4160-b842-a1dfa1ce4012)

### Version of afvalwijzer integration having the issue?

2024.12.01

### Version of Home Assistant Core having the issue?

core-2024.12.2

### Anything in the logs that might be useful for us?

```txt
No
```

**Comment by canedje** [comment]
see: https://github.com/xirixiz/homeassistant-afvalwijzer/issues/328
It is the same error

**Comment by mvdwetering** [comment]
Ah, indeed. That seems the same. I did scan the titles before submitting, but I thought this was only a presentation issue. Did not try to change anything.

Will close this one because it is duplicate
