### ISSUE TITLE
Warning about setting config_entry explicitly in Home Assistant logs

### ISSUE THREAD

**Issue by mvdwetering** [xirixiz/homeassistant-afvalwijzer#341]
### The problem

In the Home Assistant logging the following warning shows up

```
Logger: homeassistant.helpers.frame
Bron: helpers/frame.py:324
Eerst voorgekomen: 21:32:41 (1 gebeurtenissen)
Laatst gelogd: 21:32:41

Detected that custom integration 'afvalwijzer' sets option flow config_entry explicitly, which is deprecated at custom_components/afvalwijzer/config_flow.py, line 81: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/xirixiz/homeassistant-afvalwijzer/issues
```

Related blog post https://developers.home-assistant.io/blog/2024/11/12/options-flow

### Version of afvalwijzer integration having the issue?

2024.12.01

### Version of Home Assistant Core having the issue?

core-2024.12.2

### Anything in the logs that might be useful for us?

```txt
That is already in the description.
```

**Comment by xirixiz** [comment]
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!

**Comment by xirixiz** [comment]
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!
