### ISSUE TITLE
Changing configuration of the integration gives an error

### ISSUE THREAD

**Issue by canedje** [xirixiz/homeassistant-afvalwijzer#344]
### The problem

If I do try to configger the installed integration it is not showing the configuration module but gives an error

### Version of afvalwijzer integration having the issue?

mijnafvalwijzer

### Version of Home Assistant Core having the issue?

core-2024.12.4

### Anything in the logs that might be useful for us?

```txt
^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 342, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalwijzer/config_flow.py", line 86, in async_step_init
    current_options = self.options or {}
                      ^^^^^^^^^^^^
AttributeError: 'AfvalwijzerOptionsFlow' object has no attribute 'options'
```

### Additional information

![image](https://github.com/user-attachments/assets/e74e7a49-4abd-4c19-8615-9b101d99ec24)

**Comment by Eraser127** [comment]
Same here

**Comment by Remcovf** [comment]
+1

**Comment by DaanSelen** [comment]
This happens when you install it? Or when does this happen?

**Comment by Eraser127** [comment]
@DaanSelen Installed the update, restarted home Assistant, tried to open the configure menu and got the error.

**Comment by Remcovf** [comment]
> @DaanSelen Installed the update, restarted home Assistant, tried to open the configure menu and got the error.

Yup! Same here.

**Comment by DaanSelen** [comment]
Huh weird, I was able to reproduce this issue. Now its fixed suddenly. Please try to use the latest code from: https://github.com/xirixiz/homeassistant-afvalwijzer/blob/main/custom_components/afvalwijzer/config_flow.py and paste it into the `config_flow.py` for a starter.

**Comment by xirixiz** [comment]
Yeah, that is correct. I fixed it for the latest release so it at least is working. Modifying the config after installation is also working, but keeps giving an error. I`ve created an issue for that, so let's wait for a full fix. I anyone still has initial config problems with the component, please let me know. https://community.home-assistant.io/t/config-flow-issue-updating-configuration/812969

**Comment by xirixiz** [comment]
Ah, my bad, 2024.01.02 was indeed broken. I at least uploaded release 2024.01.03 now, which solves the initial config.
All code and bugfixes have been fixed in the latest release. Saver has been added, and Rova has been updated to be a separated provider. The only thing left for now is the final config_flow fix. I`ll first test things properly before delivering a new release, so you don't have any issues with it. Thanks for sharing your solution @DaanSelen

**Comment by canedje** [comment]
Indeed, changing the configuration gives an update failed
![image](https://github.com/user-attachments/assets/3f93206e-8047-40f3-bf57-0e10b963219f)

**Comment by Eraser127** [comment]
> Indeed, changing the configuration after installing 2024.12.03 gives an update failed But it looks like the changes are still stored ![image](https://private-user-images.githubusercontent.com/23150947/397331657-3f93206e-8047-40f3-bf57-0e10b963219f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTY5MDcsIm5iZiI6MTczNDYxNjYwNywicGF0aCI6Ii8yMzE1MDk0Ny8zOTczMzE2NTctM2Y5MzIwNmUtODA0Ny00MGYzLWJmNTctMGUxMGI5NjMyMTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDEzNTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2Yzg0MjAwZDI5NGE5YmJiOWZjYzkxNjdlMDgxZjE3NzI3ZDM2NmI3Y2U0Y2NhYjI1YTBmZmUwNTk5MTQzNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m67Z-E_O_mpK9NjVzvzNKYt0F-DSJIRCFzJp4y4kfWY)

Same here

**Comment by xirixiz** [comment]
Please read my comments properly. I mentioned there is still an issue with it :). I removed the optionsflow for now.
