### ISSUE TITLE
attribute last_update not set

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#346]
### The problem

as title, even though the sensors were created, and updated the attribute `last_update` in dev tools still shows null

on all afvalwijzer entities, so also the 'next' 

### Version of afvalwijzer integration having the issue?

2024.12.02

### Version of Home Assistant Core having the issue?

2024.12.4

### Additional information

<img width="901" alt="Scherm­afbeelding 2024-12-19 om 08 09 47" src="https://github.com/user-attachments/assets/d86654d6-1abe-4b40-aab7-6cbe4d71d086" />

core attribute last_updated/_changed are set see (right side next to the entity field):

<img width="1082" alt="Scherm­afbeelding 2024-12-19 om 10 05 15" src="https://github.com/user-attachments/assets/185b8f98-30a1-4688-a376-6850e7fa091a" />

quoting some response on my search regarding this behavior :

> last_update  is a custom attribute added by the integration and probably relates to the last time it polled the collection service, rather than the last_updated  that all entities have (and are displayed on the right in your screenshot) - the reason it is null is likely because either they stopped using that in some code update, or you have restarted HA since the last time it updated itself and the integration doesn't bother restoring that data across saves

that last aspect would be helpful: _have the integration restore that field upon restart_

**Comment by xirixiz** [comment]
Ahh, stupid mistake. Fixed it (next release it'll be visible again.

**Comment by Mariusthvdb** [comment]
this is working now, but note the difference

<img width="1025" alt="Scherm­afbeelding 2024-12-20 om 12 14 02" src="https://github.com/user-attachments/assets/cabe52e4-2611-49fd-bb35-9d07a684225d" />
