### ISSUE TITLE
Ximmio for Almere still not working after fix for #327

### ISSUE THREAD

**Issue by eleutscher** [xirixiz/homeassistant-afvalwijzer#347]
### The problem

I now get a different error selecting ximmio as waste provider for Almere.

First Address not found!

Second
Logger: homeassistant.components.sensor
Bron: helpers/entity_platform.py:366
integratie: Sensor (documentatie, problemen)
Eerst voorgekomen: 14:48:56 (4 gebeurtenissen)
Laatst gelogd: 19:34:54

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/afvalwijzer/sensor.py", line 57, in async_setup_entry
await _setup_sensors(hass, entry.data, async_add_entities)
File "/config/custom_components/afvalwijzer/sensor.py", line 77, in _setup_sensors
await hass.async_add_executor_job(data.update)
File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/afvalwijzer/sensor.py", line 134, in update
collector = MainCollector(
provider,
...<6 lines>...
default_label,
)
File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 138, in init
self._waste_data = WasteDataTransformer(
~~~~~~~~~~~~~~~~~~~~^
waste_data_raw,
^^^^^^^^^^^^^^^
...<2 lines>...
self.default_label,
^^^^^^^^^^^^^^^^^^^
)
^
File "/config/custom_components/afvalwijzer/common/waste_data_transformer.py", line 25, in init
waste_data_raw.sort(key=lambda item: datetime.strptime(item["date"], "%Y-%m-%d"))
^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sort'

But Ximmio is the waste provider for Almere. See https://modules.ximmio.com/?companyCode=53d8db94-7945-42fd-9742-9bbc71dbe4c1&moduleName=calendarGeneric


### Version of afvalwijzer integration having the issue?

2024.12.02

### Version of Home Assistant Core having the issue?

2024.12.4

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

**Comment by xirixiz** [comment]
@jonisnet thanks for having a look. While it was missing in the docs, it's definitely defined in code.
@eleutscher Could you share  (DM) your postal code and random street number with me so I can perfom some validations?

**Comment by eleutscher** [comment]
I updated Afvalwijzer to 2024.12.04. Reboot HA. Deleted the entries in Afvalwijzer. Added Almere with my postal code and everything is working again. Thx!

**Comment by xirixiz** [comment]
Ah valid point, for the postcal code I automatically make ik upper case. But since this now is via the ui, it shouldn't matter what users type in. I`ll fix it in another release.
