### ISSUE TITLE
Next pickup date

### ISSUE THREAD

**Issue by haaino** [xirixiz/homeassistant-afvalwijzer#348]
### The problem

Hi,

Hope someone can help me out.

While writing this issue the date is 19-12-2024. Today PMD has been collected. 

I noticed the following:
- sensor.afvalwijzer_pmd value is 19-12-2024 (correct)
- sensor.afvalwijzer_next_type also set to PMD (incorrect), this should be GFT 
- sensor.afvalwijzer_next_in_days is set to 0 (incorrect?), should be 4 in my case.

The behavior changed when upgrading to 2024.12.0 and higher

### Version of afvalwijzer integration having the issue?

2024.12.3

### Version of Home Assistant Core having the issue?

2024.12.4

**Comment by xirixiz** [comment]
This is odd indeed. Can you share your postal code and street-/housenumber with me (DM)? 

There is this option to include or exclude today pickups. Not sure if you did something with this option, but default it should be set to exclude, so it then should never be "0" at least. My assumption is that you have this setting enabled.

```
vol.Optional(CONF_EXCLUDE_PICKUP_TODAY, default=True): cv.boolean,
```

**Comment by haaino** [comment]
Hi,

Thank you for the tip. 

I just tried to reconfigure via the UI. It gave an error massage. 

Where can i find the config file so that i can manual check?

**Comment by xirixiz** [comment]
There is an issue with reconfigure. Best is to remove and the re-add the component from scratch.

**Comment by haaino** [comment]
Done.

Let's see if the issue is gone as well.
Keep you update.

Thank you for all the good work. 

Prettige feestdagen alvast!

**Comment by xirixiz** [comment]
Thanks! Prettige feestdagen :)
