### ISSUE TITLE
Integration stopped working, entities gone..

### ISSUE THREAD

**Issue by conforce** [xirixiz/homeassistant-afvalwijzer#351]
### The problem

Hi, I've noticed my entities are gone since the last two updates.. tried to revert to an old backup but no luck... 
<img width="828" alt="Screenshot 2024-12-19 at 21 43 43" src="https://github.com/user-attachments/assets/58ae4b63-2f99-4ace-9493-acd70115d998" />

### Version of afvalwijzer integration having the issue?

latest

### Version of Home Assistant Core having the issue?

latest

**Comment by NicoOosterwijk** [comment]
Hier ook, alle entiteiten onbekend

**Comment by xirixiz** [comment]
Duplicate: https://github.com/xirixiz/homeassistant-afvalwijzer/issues/350

**Comment by xirixiz** [comment]
Duplicate: https://github.com/xirixiz/homeassistant-afvalwijzer/issues/350
