### ISSUE TITLE
Sensors showing "Not available" (starting from release 2024.12.01)

### ISSUE THREAD

**Issue by N1ckXL** [xirixiz/homeassistant-afvalwijzer#353]
### The problem

After installing 2024.12.01, 2024.12.02, 2024.12.03, 2024.12.04 or 2024.12.05 all sensors show "Not available". 
It seems 2024.06.02 is the last correct working version.

### Version of afvalwijzer integration having the issue?

2024.12.01 and higer

### Version of Home Assistant Core having the issue?

2024.12.5

### Additional information

Configuration in configuration.yaml:
 
#Afvalwijzer
  - platform: afvalwijzer
    provider: mijnafvalwijzer # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, afvalstoffendienstkalender or rova
    postal_code: 1234XX # (required, default = '')
    street_number: 0 # (required, default = '')
    suffix: "" # (optional, default = '')
    exclude_pickup_today: true # (optional, default = true) to take or not to take Today into account in the next pickup.
    default_label: geen # (optional, default = geen) label if no date found
    id: "" # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
    exclude_list: "" # (optional, default = '') comma separated list of waste types (case ignored). F.e. "papier, gft"

**Comment by N1ckXL** [comment]
Sorry, didn't read the read me notes.

**Comment by timovd** [comment]
https://github.com/xirixiz/homeassistant-afvalwijzer/blob/2024.12.06/README.md#sensor---configurationyaml
Shouldn't this be removed? This leads to confusion.
