### ISSUE TITLE
No new date 2025 saver for restafval

### ISSUE THREAD

**Issue by niekniek89** [xirixiz/homeassistant-afvalwijzer#354]
### The problem

Today (23-12) the residual waste is collected here.
I see that the residual waste sensor does not show a new date for 2025.
This is already known on the Saver website.
The paper does show a new date for 2025.

### Version of afvalwijzer integration having the issue?

2024.12.02

### Version of Home Assistant Core having the issue?

2024.12.0

### Additional information

![image](https://github.com/user-attachments/assets/320e8f4b-965e-48d1-b7ce-7c25b171e373)

I threw away the whole integration, deleted all old config from config.yaml, restarted HA... and created everything the new way.

**Comment by xirixiz** [comment]
@niekniek89 what is a postal code in your area?

**Comment by niekniek89** [comment]
> @niekniek89 what is a postal code in your area?

Hi @xirixiz,
Postal code: 4708LS

**Comment by xirixiz** [comment]
Het lijkt een issue the zijn bij Saver. Dit krijg ik terug uit de onderstaande URL.
Wanneer je op de URL zoekt in je browser op 2025. dan krijg je maar 1 result terug (papier inderdaad). 
Maart samengevat, de data die ik terug krijg van Saver komt overeen met wat jij in HASS ziet. De data is simpelweg nog niet beschikbaar op de URL die ik moet gebruiken voor het ophalen van de data. Dit komt wel vaker voor bij providers aan het einde van het jaar. Ik zou even een paar dagen wachten.

```
https://saver.nl/rest/adressen/1674200000017081/afvalstromen
2024-12-30
gft+e
None
2024-12-27
pbd / pmd
None
2024-12-23
restafval
None
None
None
None
2025-01-06
papier
```

**Comment by niekniek89** [comment]
Ah oke, dank voor het checken!
Dan lijkt alles nog gewoon goed te werken in HA.
Ik dacht, op de kalender van Saver zag ik al wel een nieuwe datum, maar de integratie gebruikt een andere URL.

**Comment by xirixiz** [comment]
Ja klopt, ook dat komt helaas vaker voor :)

**Comment by niekniek89** [comment]
Heeft nu wel een datum in 2025 ☺️
