### ISSUE TITLE
No discovery

### ISSUE THREAD

**Issue by haaino** [xirixiz/homeassistant-afvalwijzer#355]
### The problem

Logger: custom_components.afvalwijzer.const.const
Source: custom_components/afvalwijzer/sensor.py:48
integration: Afvalwijzer ([documentation](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/main/README.md), [issues](https://github.com/xirixiz/homeassistant-afvalwijzer/issues))
First occurred: 14:28:36 (1 occurrences)
Last logged: 14:28:36

No discovery information provided; sensors cannot be created.

### Version of afvalwijzer integration having the issue?

Latest

### Version of Home Assistant Core having the issue?

2024.12.3

**Comment by xirixiz** [comment]
@haaino Not sure what to do with this. I need some logging errors or aditional information.

If you have the component configured in configuration.yaml, you need to remove it and follow the HASS ui and add the component (config flow)

**Comment by haaino** [comment]
Sorry about this. 

I have afvalwijzer configured via the gui. 

The issue and info I have copy/pasted. It is the first log message I get when HA is starting. 

How can I assist you with further info?

**Comment by gvansteeg** [comment]
I do have same issue.
I have updated afvalwijzer today and after reboot, no sensors are created anymore.

**Comment by xirixiz** [comment]
Check for more info here: https://community.home-assistant.io/t/garbage-pickup-date-mijnafvalwijzer-nl-custom-component/34631/988?u=xirixiz

And here: https://github.com/xirixiz/homeassistant-afvalwijzer?tab=readme-ov-file#installation-via-hacs

The way of configuring the component has been changed.
