### ISSUE TITLE
No future dates from mijnafvalwijzer.nl

### ISSUE THREAD

**Issue by realrolfje** [xirixiz/homeassistant-afvalwijzer#362]
### The problem

Mijnafvalwijzer.nl gives dates for 2025 (see screenshot)
afvalwijzer plugin gives no dates for 2025 (see screenshot)
![Screenshot 2024-12-28 at 10 33 16](https://github.com/user-attachments/assets/dacbeb8d-9798-4eec-993c-d825b7ddd0cf)
![Screenshot 2024-12-28 at 10 33 47](https://github.com/user-attachments/assets/110b31dc-d051-47a2-b035-50c721c9d67f)

### Version of afvalwijzer integration having the issue?

2024.12.05

### Version of Home Assistant Core having the issue?

2024.12.5

**Comment by realrolfje** [comment]
Update: when running
```
python custom_components/afvalwijzer/tests/test.py
```

it does show dates in 2025:

```
md>, <WasteCollection date=2024-10-31 00:00:00 type=papier>, <WasteCollection date=2024-11-01 00:00:00 type=gft>, <WasteCollection date=2024-11-05 00:00:00 type=pmd>, <WasteCollection date=2024-11-08 00:00:00 type=restafval>, <WasteCollection date=2024-11-15 00:00:00 type=gft>, <WasteCollection date=2024-11-19 00:00:00 type=pmd>, <WasteCollection date=2024-11-28 00:00:00 type=papier>, <WasteCollection date=2024-11-29 00:00:00 type=gft>, <WasteCollection date=2024-12-03 00:00:00 type=pmd>, <WasteCollection date=2024-12-06 00:00:00 type=restafval>, <WasteCollection date=2024-12-13 00:00:00 type=gft>, <WasteCollection date=2024-12-17 00:00:00 type=pmd>, <WasteCollection date=2024-12-27 00:00:00 type=gft>, <WasteCollection date=2024-12-27 00:00:00 type=papier>, <WasteCollection date=2024-12-31 00:00:00 type=pmd>, <WasteCollection date=2025-01-03 00:00:00 type=restafval>, <WasteCollection date=2025-01-10 00:00:00 type=gft>, <WasteCollection date=2025-01-11 00:00:00 type=kerstbomen>, <WasteCollection date=2025-01-14 00:00:00 type=pmd>, <WasteCollection date=2025-01-23 00:00:00 type=papier>, <WasteCollection date=2025-01-24 00:00:00 type=gft>, <WasteCollection date=2025-01-28 00:00:00 type=pmd>, <WasteCollection date=2025-01-31 00:00:00 type=restafval>, <WasteCollection date=2025-02-07 00:00:00 type=gft>, <WasteCollection date=2025-02-11 00:00:00 type=pmd>]
```

**Comment by JBS5** [comment]
I was looking for 2025 dates too, but I don't see them on https://mijnafvalwijzer.nl/.
Also your screenshot is not showing 2025 dates?

**Comment by xirixiz** [comment]
> Update: when running
> 
> ```
> python custom_components/afvalwijzer/tests/test.py
> ```
> 
> it does show dates in 2025:
> 
> ```
> md>, <WasteCollection date=2024-10-31 00:00:00 type=papier>, <WasteCollection date=2024-11-01 00:00:00 type=gft>, <WasteCollection date=2024-11-05 00:00:00 type=pmd>, <WasteCollection date=2024-11-08 00:00:00 type=restafval>, <WasteCollection date=2024-11-15 00:00:00 type=gft>, <WasteCollection date=2024-11-19 00:00:00 type=pmd>, <WasteCollection date=2024-11-28 00:00:00 type=papier>, <WasteCollection date=2024-11-29 00:00:00 type=gft>, <WasteCollection date=2024-12-03 00:00:00 type=pmd>, <WasteCollection date=2024-12-06 00:00:00 type=restafval>, <WasteCollection date=2024-12-13 00:00:00 type=gft>, <WasteCollection date=2024-12-17 00:00:00 type=pmd>, <WasteCollection date=2024-12-27 00:00:00 type=gft>, <WasteCollection date=2024-12-27 00:00:00 type=papier>, <WasteCollection date=2024-12-31 00:00:00 type=pmd>, <WasteCollection date=2025-01-03 00:00:00 type=restafval>, <WasteCollection date=2025-01-10 00:00:00 type=gft>, <WasteCollection date=2025-01-11 00:00:00 type=kerstbomen>, <WasteCollection date=2025-01-14 00:00:00 type=pmd>, <WasteCollection date=2025-01-23 00:00:00 type=papier>, <WasteCollection date=2025-01-24 00:00:00 type=gft>, <WasteCollection date=2025-01-28 00:00:00 type=pmd>, <WasteCollection date=2025-01-31 00:00:00 type=restafval>, <WasteCollection date=2025-02-07 00:00:00 type=gft>, <WasteCollection date=2025-02-11 00:00:00 type=pmd>]
> ```

Best thing to use for testing is not test.py or test2.py. I`m exploring a method to make it easier to maintain and/or contribute to this component. Maybe I should move this to a separate branch :).

For testing you should user: test_module.py
-  Comment out ```__init__.py```
- Update ```test_module.py``` with your information (or the information you would like to test with, examples are in that file)
- Then run ```python3 -m afvalwijzer.tests.test_module``` from this path ```<some dir>/homeassistant-afvalwijzer/custom_components```

This way, you make sure you using the same components as they are being used in HASS. This way it's possible to skip the stop/start of HASS a lot of times when just looking at data retrieval issues.

**Comment by xirixiz** [comment]
Can you share a postal code in your area?

**Comment by JBS5** [comment]
> Can you share a postal code in your area?
> 
> People were experiencing some issues due to a bug in the data for next year from mijnafvalwijzer. I've created a workaround for them, but just processing the next 25 items for upcoming year (if any). Maybe this is related.
> 
> This line:
> 
> https://github.com/xirixiz/homeassistant-afvalwijzer/blob/f167a74ffce190c6ca97d02b51d90eb6ee75ca9e/custom_components/afvalwijzer/collector/mijnafvalwijzer.py#L37
> 
> More info: #350 #352

Sure, a postal code in my area is 5685AB 57 (not mine, from Funda).

**Comment by xirixiz** [comment]
What the API returns for 2025 is only this:

```
 'ophaaldagenNext': {'response': 'NOK', 'data': [], 'error': 'No data'}}
```
So in that sense it matches what the output is from mijnafvalwijzer. Mijnafvalwijzer always has API issues each year, so my assumption the data will be available again for you soon.

**Comment by realrolfje** [comment]
That is strange, because if I run the test with my postalcode it does return dates in 2025, so my guess was that the parsing or sorting has a problem (hence my search for unittests ;-) )

**Comment by realrolfje** [comment]
```
----- afvalwijzer ---
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.mijnafvalwijzer.nl'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
No waste data found after the selected date.
Error occurred in __get_next_waste_in_days: 'str' object has no attribute 'date'
{'gft': 'geen', 'kerstbomen': 'geen', 'papier': 'geen', 'pmd': 'geen', 'takken': 'geen'}
...
----------------------------------------------------------------------
```
