### ISSUE TITLE
Services as dropdown instead of free text field

### ISSUE THREAD

**Issue by realrolfje** [xirixiz/homeassistant-afvalwijzer#363]
### Feature request

When configuring the plugin, there is a textbox where the user needs to type the service to connect to. In my case that was "mijnafvalwijzer.nl". If you type "mijnafvalwijzer.nl" (with the .nl) then the plugin does not work, and does not tell you why.
It would be more user-friendly if that text field was a drop-down with only the supported services.

### What version of the integration are you using?

2024.12.06

**Comment by xirixiz** [comment]
Done. Tested and added to be released next release.

https://github.com/xirixiz/homeassistant-afvalwijzer/blob/main/custom_components/afvalwijzer/config_flow.py
