### ISSUE TITLE
Developer manual

### ISSUE THREAD

**Issue by realrolfje** [xirixiz/homeassistant-afvalwijzer#364]
### Feature request

When trying to analyze and run parts of afvalwijzer it is unclear how to run tests.
There are a few files in the `test` folder but none of them are actual unittests.
When trying to create unittests I ran into a problem with (nested) relative imports.
It would be helpful if there was a developer manual explaining how to run and test this code, preferably with unittess so we can test parts of the code without starting up homeassistant.

### What version of the integration are you using?

12.6

**Comment by xirixiz** [comment]
Most people are not interested in testing themselves I noticed, so I decided no docs on how to execute tests on the component standalone. However, this way you should be able to do some standalone data retrieval and parsing tests.

###

For testing you should user: test_module.py

Comment out __init__.py
Update test_module.py with your information (or the information you would like to test with, examples are in that file)
Then run python3 -m afvalwijzer.tests.test_module from this path <some dir>/homeassistant-afvalwijzer/custom_components
This way, you make sure you using the same components as they are being used in HASS. This way it's possible to skip the stop/start of HASS a lot of times when just looking at data retrieval issues.
