### ISSUE TITLE
Failed to import provider modules: cannot import name 'afvalalert'

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#368]
### The problem

as log below.
wapening on latest 24.12.07 and HA 2025.1.0b3 which was used to startup and showed the error.

### Version of afvalwijzer integration having the issue?

24.12.07

### Version of Home Assistant Core having the issue?

2025.1.0b3

### Anything in the logs that might be useful for us?

```txt
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.afvalwijzer.const.const
Bron: custom_components/afvalwijzer/config_flow.py:48
integratie: Afvalwijzer (documentatie, problemen)
Eerst voorgekomen: 20:01:17 (1 gebeurtenissen)
Laatst gelogd: 20:01:17

Failed to import provider modules: cannot import name 'afvalalert' from 'custom_components.afvalwijzer' (/config/custom_components/afvalwijzer/__init__.py)
```

### Additional information

Integrations seems to work fine otherwise, all of my regular sensors are initiated correctly as far as I can see now

**Comment by xirixiz** [comment]
Fixed in the latest release.
