### ISSUE TITLE
Intergration Saver not working

### ISSUE THREAD

**Issue by schijven** [xirixiz/homeassistant-afvalwijzer#373]
### The problem

Intergration with Saver is nog working:
![afbeelding](https://github.com/user-attachments/assets/86762f1f-c39f-440a-b291-98cfa929b782)

Error:
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.afvalwijzer.const.const
Bron: custom_components/afvalwijzer/sensor.py:52
integratie: Afvalwijzer (documentatie, problemen)
Eerst voorgekomen: 08:06:58 (1 gebeurtenissen)
Laatst gelogd: 08:06:58

No discovery information provided; sensors cannot be created.

I'm running the lattest intergration
![afbeelding](https://github.com/user-attachments/assets/e62a8776-f522-4719-93a6-984608e92c27)
![afbeelding](https://github.com/user-attachments/assets/ade8d582-5ee3-4c85-a7db-a8992e22a715)

### Version of afvalwijzer integration having the issue?

2024.12.08

### Version of Home Assistant Core having the issue?

2024.12.5

### Anything in the logs that might be useful for us?

```txt
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.afvalwijzer.const.const
Bron: custom_components/afvalwijzer/sensor.py:52
integratie: Afvalwijzer (documentatie, problemen)
Eerst voorgekomen: 08:06:58 (1 gebeurtenissen)
Laatst gelogd: 08:06:58

No discovery information provided; sensors cannot be created.
```

### Additional information

Settings are:
  - platform: afvalwijzer
    provider: saver        # (required, default = mijnafvalwijzer) choose the provider for your community.
    postal_code: 4706HN              # (required, default = '')
    street_number: 5                # (required, default = '')
    suffix: ''                       # (optional, default = '')
    username: ''                     # (optional, default = '')
    password: ''                     # (optional, default = '')
    exclude_pickup_today: true       # (optional, default = true) to take or not to take Today into account in the next pickup.
    date_isoformat: false            # (optional, default = false) show the date in full isoformat if desired. Example: "2024-01-14T08:40:33.993521"
    default_label: geen              # (optional, default = geen) label if no date found
    id: ''                           # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
    exclude_list: ''                 # (optional, default = '') comma separated list of wast types (case ignored). F.e. "papier, gft, restafval, pmd, etc"

**Comment by xirixiz** [comment]
Did you upgrade recently, or did you follow all the recent upgrades?

Nowadays it's mandatory to use the config flow in HASS for this component: https://github.com/xirixiz/homeassistant-afvalwijzer?tab=readme-ov-file#configuration

In advance you should remove the custom definition in your configuration.yaml file for this component.

If you've already done this, please share a valid postal code and street number in your area so I can have a look.

**Comment by xirixiz** [comment]
Already validated and Saver is working fine with your postal code and street number. So my guess is you're still using the old way of configuring this component.

**Comment by schijven** [comment]
Dear Bram,

After removing and reinstalling it works indeed. Because the definitions in
configuration.yaml are still on de site, i thought this is working also.
Thank you for your support

Op ma 30 dec 2024 om 17:46 schreef Bram van Dartel ***@***.***

**Comment by xirixiz** [comment]
Good to hear! Happy to help and a happy new year Tonight!
