### ISSUE TITLE
No sensor made

### ISSUE THREAD

**Issue by Martijn1234** [xirixiz/homeassistant-afvalwijzer#73]
After updating home assistant the sensors for the trash are not created any more.
I removed en reinstalled the repository but nothing works

**Comment by JBS5** [comment]
Because the URL https://json.mijnafvalwijzer.nl/?method=postcodecheck&postcode=1234AB&street=&huisnummer=1&toevoeging=&langs=nl does not give any data anymore, the sensors could not be setup.

In the HA log, you will see an error like 'Error while setting up afvalwijzer platform for sensor'

**Comment by xirixiz** [comment]
Correct. And for now mijnafvalwijzer doesn't have any plans bringin it back online, but they are interested in home automation, so they're going to look into it. Scraping data is the alternative in the meantime...unfortunately. I'll update the sensor to scrape until a better solution is provided by mijnafvalwijzer.nl

**Comment by Mariusthvdb** [comment]
great if you would!
I noticed you deleted the scraper, and thought to be the lucky none to have saved to from an earlier stage. Reinstalled that, but unfortunately it errored out with an almost identical error....
so, hope you can make it scrape again, including today, tomorrow and dat (day-after-tomorrow)
