### ISSUE TITLE
Obtain api key

### ISSUE THREAD

**Issue by TheRedBull205** [xirixiz/homeassistant-afvalwijzer#76]
Since the api key is personal in the latest version can you tell or adjust the readme how to obtain one?
I can't figure out where to start, the closest thing i found is https://data.overheid.nl/ or to email: info@mijnafvalwijzer.nl

You obtained a key so i guess it should also be possible for the community?

**Comment by xirixiz** [comment]
The whole point of removing it from the code is that the provider doesn't allow the community to connect to their api. Maybe in the future, but not for now unfortunately...

L2 .gitignore...

I'm working on a different way of implementation.

**Comment by xirixiz** [comment]
Oke, I'm almost done with a new and working component without using the API but with all the same functionality.
I`ll release it Tomorrow or the day after Tomorrow
