### ISSUE TITLE
No sensor.trash_luiers anymore

### ISSUE THREAD

**Issue by JBS5** [xirixiz/homeassistant-afvalwijzer#80]
Just updated to 4.4.4 but the _sensor.trash_luiers_ is not available anymore.
As this one is picked up every week, it not the hardest to remember, but the sensor was there before.

**Comment by xirixiz** [comment]
I`ll add luiers. The hard thing is that each community has it's own trash pickups and naming conventions, therefor this way of gathering data is less reliable unfortunatly.

**Comment by xirixiz** [comment]
What is the exact name used when looking at mijnafvalwijzer.nl?

**Comment by JBS5** [comment]
> What is the exact name used when looking at mijnafvalwijzer.nl?

_Luier- en incontinentiemateriaal_

**Comment by xirixiz** [comment]
I mean further at the bottom where you can select for which items you'd like to receive an email

**Comment by JBS5** [comment]
> I mean further at the bottom where you can select for which items you'd like to receive an email

_luiers_

**Comment by xirixiz** [comment]
Done in release 4.4.5

**Comment by JBS5** [comment]
Thanks! Just updated to 4.4.5 and sensor.trash_luiers is now available, with date :-)
