### ISSUE TITLE
count_today: false (default) not working

### ISSUE THREAD

**Issue by avehome** [xirixiz/homeassistant-afvalwijzer#81]
![image](https://user-images.githubusercontent.com/50752001/93931320-ef11f880-fd1e-11ea-9fbe-c9238a589ded.png)

sensor.trash_first_next_in_days still count today?

Sensor setting: 
count_today: false (optional, default = false) to take or not to take Today into account in the next pickup.

**Comment by xirixiz** [comment]
That could be the case indeed, I`ll fix it.

**Comment by xirixiz** [comment]
Fixed in 4.4.9. My screen looks like this btw. The second row sorts trash by date.

![image](https://user-images.githubusercontent.com/11210639/93979056-231c0680-fd7d-11ea-95c0-b4eafe566d53.png)

Lovelace code:
  - type: 'custom:auto-entities'
    card:
      type: glance
    filter:
      include:
        - entity_id: sensor.trash_gft
        - entity_id: sensor.trash_papier
        - entity_id: sensor.trash_pmd
        - entity_id: sensor.trash_restafval
    sort:
      attribute: next_pickup_in_days
      method: attribute
      numeric: true
