### ISSUE TITLE
sensors in google calandar

### ISSUE THREAD

**Issue by Janthenman67** [xirixiz/homeassistant-afvalwijzer#82]
Great to have the sensors back. Now I want to figure out a way to have the sensors show up in google calandar, which i integrated in home assistant. That way the sensor shows up in between hollidays, birthdays and so on. Would be really cool. Any ideas on that?

**Comment by xirixiz** [comment]
Actually that is functionality unrelated to this component. I think the best way to get this done is via the hass community, probably you can even find examples there 😃 . https://community.home-assistant.io/
