### ISSUE TITLE
Format of sensors trash_tomorrow and first_waste_type

### ISSUE THREAD

**Issue by JBS5** [xirixiz/homeassistant-afvalwijzer#84]
The state of the sensors _trash_tomorrow_ and _first_waste_type_ are changed compared to previous versions.
In previous versions it was nicely formatted (comma separated like 'gft, restaval, luers') which makes them immediately usable in notifications. Now the state of the mentioned sensors is like:

`[['gft', 'restafval'], 'luiers']`

Is is possible to format them like before?

**Comment by xirixiz** [comment]
Are you sure you're using the latest release?

I can't find anything which could be causing this issue, and also the output for me is nicely presented. What's you postol code?

```
[{'key': 'day_after_tomorrow', 'value': 'papier, pmd'}, {'key': 'today', 'value': 'Geen'}, {'key': 'tomorrow', 'value': 'Geen'}, {'key': 'first_next_date', 'value': '25-09-2020'}, {'key': 'first_next_in_days', 'value': 2}, {'key': 'first_next_item', 'value': 'papier, pmd'}]
```

**Comment by xirixiz** [comment]
Met gemanipuleerde data met 3+ items zie ik het probleem ook niet helaas:
```
[{'key': 'day_after_tomorrow', 'value': 'gft, papier, pmd, luiers'}, {'key': 'today', 'value': 'Geen'}, {'key': 'tomorrow', 'value': 'Geen'}, {'key': 'first_next_date', 'value': '25-09-2020'}, {'key': 'first_next_in_days', 'value': 2}, {'key': 'first_next_item', 'value': 'gft, papier, pmd, luiers'}]
```

**Comment by JBS5** [comment]
Ik dacht met 4.4.5 van maandag bij te zijn, maar dat bleek niet het geval. Ontwikkeling gaat hard :-)
Gisteravond geüpdatet, en de sensors zijn nu weer netjes geformat. Top!
