### ISSUE TITLE
Example config for newbies

### ISSUE THREAD

**Issue by TheGabeMan** [xirixiz/homeassistant-afvalwijzer#85]
Newbie to HA and trying to get afvalwijzer to run. I copied the example config lines from the readme file but couldn't get things to work. Few hours later I found that I shouldn't have copied the config exactly as it is in the readme. There are # missing behind the sample values. When I now look at it, it is so obvious, but it might help others as well when changing the example to:

 sensor:
    - platform: afvalwijzer
      provider: mijnafvalwijzer       #  (required, default = mijnafvalwijzer) either choose mijnafvalwijzer or afvalstoffendienstkalender
      zipcode: 1111AA                  # (required, default = 1111AA)
      housenumber:  11                # (required, default = 11)
      count_today: false               #  (optional, default = false) to take or not to take Today into account in the next pickup.
      default_label: Geen              #  (optional, default = Geen) label if no date found

**Comment by xirixiz** [comment]
Always like comments how to improve. What even would be nicer is you modifying the file and create a pull request ✌🏻👍🏻

Edit the file online, click commit at the bottom and from there you'll see how to create a pull request 😁

**Comment by TheGabeMan** [comment]
Think I created a pull request. Hope it was done correctly.

**Comment by xirixiz** [comment]
Great! Thanks for your contribution. You've learned and it saved me some time 👍🏻😁
