### ISSUE TITLE
Not all sensors are filled correctly

### ISSUE THREAD

**Issue by P-Verbrugge** [xirixiz/homeassistant-afvalwijzer#88]
I just updated to version 5.0.0 and noticed that all data is not scraped correctly.

For example. The sensor tomorrow is now empty. In my live setup with the older 4.x version I see it is set to Green.
Also the plastic date is incorrect. It has the same date as Paper now.

**Comment by dvb76** [comment]
Mine shows the same for today and tomorrow, while only today is "rest"

**Comment by xirixiz** [comment]
Can you provide me a postal_code and street_number to verify? You're using the scraper, not the api I believe right?
I just checked it again in my env, and all is looking good. The only thing is that I currently don't have any wasttypes to be picked up for the coming days, so I couldn't verify today, tomorrow, and day after tomorrow properly.

**Comment by xirixiz** [comment]
Ik heb de volgende fout gevonden, dat moet ```self.tomorrow``` zijn, maar buiten dat zie ik geen andere issues.

https://github.com/xirixiz/homeassistant-afvalwijzer/blob/ccbe947bf705c6ec6be9b90ce28ed1c18ca67d64/custom_components/afvalwijzer/provider/mijnafvalwijzer.py#L196

**Comment by P-Verbrugge** [comment]
Can I send a private message? Then I can send my postalcode and number.

**Comment by xirixiz** [comment]
Can you pb via the hass community? 👍🏻

**Comment by dvb76** [comment]
The solution is indeed change line 196 of the Afvalwijzer from today to tomorrow.
Worked for me.

**Comment by P-Verbrugge** [comment]
> Can you pb via the hass community? 👍🏻

I send a message in telegram.

**Comment by Mariusthvdb** [comment]
goe here because of a GitHub notification, but there is no release 5.x yet?

**Comment by xirixiz** [comment]
Yes, there was only the error in the code I mentioned earlier, checked and fixed in release 5.0.1
