### ISSUE TITLE
no attribute named_date?

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#91]
Hi,

using 5.0.3 now, I would have expected the named_date attribute, which was introduced in 5.0.2?

however, this is all I see:

<img width="979" alt="Schermafbeelding 2020-09-30 om 23 25 23" src="https://user-images.githubusercontent.com/33354141/94741598-a688b980-0374-11eb-86ae-4c03e0217d91.png">

do we need to enable this in the config maybe?
sorry if I missed the obvious, but do think I couldn't find it.

**Comment by xirixiz** [comment]
Hahaha, sorry, removed it already in 5.0.3. I thing 2 date formats are enough. I wanted to add an additional format, but then I notice you use a lot more formats. So let's keep the code clean instead :)
