### ISSUE TITLE
Integration not working

### ISSUE THREAD

**Issue by niekniek89** [xirixiz/homeassistant-afvalwijzer#92]
I get the error below after a restart:

HTTP error occurred: 404 Client Error: Not Found for url: https://www.mijnafvalwijzer.nl/error

what could be the problem?

after installing the afvalwijzer in HACS, he created the folders himself in custom_components -> waste guide

after the restart of HA i added the following config:

sensor:

platform: afvalwijzer
provider: mijnafvalwijzer
postal_code: 0000XX
street_number: X
suffix: A.
include_date_today: false
default_label: None
after this another reboot

**Comment by niekniek89** [comment]
> I get the error below after a restart:
> 
> HTTP error occurred: 404 Client Error: Not Found for url: https://www.mijnafvalwijzer.nl/error
> 
> what could be the problem?
> 
> after installing the afvalwijzer in HACS, he created the folders himself in custom_components -> waste guide
> 
> after the restart of HA i added the following config:
> 
> sensor:
> 
> platform: afvalwijzer
> provider: mijnafvalwijzer
> postal_code: 0000XX
> street_number: X
> suffix: A.
> include_date_today: false
> default_label: None
> after this another reboot

maybe I miss something, or did I do something wrong?

**Comment by xirixiz** [comment]
After the suffix, I see an ```A```, but behind it I see a dot, hence the error 404 not found.

The page you're trying to access doesn't exist with the street number, postal code and suffix provided, and most probabaly that's related to the dot.

**Comment by niekniek89** [comment]
thanks for your comment. i adjusted it but still get the same error. (see screenshot)

![afvalwijzer1](https://user-images.githubusercontent.com/48858098/94782760-fb0b5380-03cb-11eb-92c4-6ff9a8378e6b.jpg)

**Comment by xirixiz** [comment]
I`m 100% sure this has nothing to do with the component itself, this is a config error.
I`ll help you out further through the hass community.

**Comment by xirixiz** [comment]
You could also set it to debug so you can actually see how the URL is parsed. This has to be put in your configuration.yaml
```
logger:
  default: info
  logs:
    custom_components.afvalwijzer: debug
```
