### ISSUE TITLE
First next item is nu zelfde als morgen?

### ISSUE THREAD

**Issue by Toinieboy** [xirixiz/homeassistant-afvalwijzer#94]
Sinds woensdag ofzo is de first next item is gelijk aan tomorrow, als je de dag van te voren kijkt. Een paar dagen
terug was dit daadwerkelijk het eerstvolgende item na morgen?

Doe ik iets fout? Of is er iets veranderd?

Code is nog steeds hetzelfde:

  Het is tijd om 't {{ states('sensor.afvalwijzer_tomorrow') }} buiten te
  zetten. Over {{ states('sensor.afvalwijzer_first_next_in_days') }} dagen mag
  trouwens het {{ states('sensor.afvalwijzer_first_next_item') }} aan de
  straat! 

Grtz!
![WhatsApp Image 2020-10-01 at 23 41 13](https://user-images.githubusercontent.com/66773265/94866657-0d26d980-0440-11eb-9f8e-3c6042c586f6.jpeg)
![WhatsApp Image 2020-10-01 at 23 46 50](https://user-images.githubusercontent.com/66773265/94866902-76a6e800-0440-11eb-899b-fd9a17d13cab.jpeg)

**Comment by xirixiz** [comment]
Volgens mij is dit inmiddels opgelost... of ervaar je dit nog?

**Comment by Toinieboy** [comment]
Hi,

ik ervaar dit sinds de laatste release. Daarvoor had ik het niet (dus zeg maar die dinsdag klopte het nog, na de update naar de laatste release, die donderdag, wel)

**Comment by xirixiz** [comment]
Ik denk dat er wellicht iets met de configuratie niet goed staat. Bij mij klopt het iig.

![image](https://user-images.githubusercontent.com/11210639/95556336-7647b780-0a13-11eb-919e-93ee7f83a6a6.png)

**Comment by xirixiz** [comment]
Oh wacht even, nu lees ik het goed.

first_next_item is altijd het eerstvolgende item geweest inclusief vandaag of exclusief vandaag.

Dus wanneer er vandaag GFT opgehaald wordt, en morgen PMD en ```include_date_today``` op false (default) staat, dan is het resultaat:
```
sensor.afvalwijzer_first_next_item: PMD
```

en wanneer ```include_date_today``` op true staat, dan is het resultaat:
```
sensor.afvalwijzer_first_next_item: GFT
```
 
Jouw code:
Het is tijd om 't {{ states('sensor.afvalwijzer_tomorrow') }} buiten te
zetten. Over {{ states('sensor.afvalwijzer_first_next_in_days') }} dagen mag
trouwens het {{ states('sensor.afvalwijzer_first_next_item') }} aan de
straat!

Kan op deze manier niet gewerkt hebben, dat kan alleen wanneer je het als volgt had:
Het is tijd om 't {{ states('sensor.afvalwijzer_today') }} buiten te
zetten. Over {{ states('sensor.afvalwijzer_first_next_in_days') }} dagen mag
trouwens het {{ states('sensor.afvalwijzer_first_next_item') }} aan de
straat!

Omdat ik nooit naar rekening heb gehouden met morgen in de logica van de code. first_next_item na morgen heb ik nooit geimplementeerd, dus alleen first_next_item inclusief of exclusief vandaag.

**Comment by Mariusthvdb** [comment]
> first_next_item na morgen heb ik nooit geimplementeerd, dus alleen first_next_item inclusief of exclusief vandaag.

dit komt heel erg in de buurt met het verzoek wat ik al lang heb: op een ophaaldag het first_next_item niet naar vandaag laten wijzen, maar naar de volgende. Zou dat mogelijk zijn? Dan kunnen we namelijk op een ophaaldag zien welke 4 volgende data zich aandienen, in plaats van vandaag plus de volgende 3...

**Comment by xirixiz** [comment]
Alles is mogelijk uiteraard, ik heb dat alleen nooit zo begrepen. Ik vind het eerlijk gezegd nu ook enigszins onduidelijk 😄.

Bedoel je dat je graag zou willen dat first_next_item de optie heeft om naar overmorgen en verder te kijken, en dus vandaag en morgen niet in beschouwing te nemen?

**Comment by Mariusthvdb** [comment]
Wat ik bedoel is als er vandaag afval wordt opgehaald, dat de first_next_item (en date) vandaag buiten beschouwing laten, en pas bij morgen beginnen te checken.

Ik kan het nu niet laten zien (vandaag wordt hier niets opgehaald) maar heb dat op het forum wel al een paar keer gedaan, maar op het onderstaande plaatje zou als er vandaag iets zou worden opgehaald, in de lijst eronder vandaag nogmaals worden getoond. Terwijl dat dan eigenlijk bij de volgende zou moeten beginnen:

<img width="460" alt="Schermafbeelding 2020-10-09 om 10 11 53" src="https://user-images.githubusercontent.com/33354141/95559400-fcfe9380-0a17-11eb-8e80-452fcb52466b.png">

ik ga het forum nog eens doorlopen en dat plaatje zoeken ;-)

**Comment by xirixiz** [comment]
Ah oke, maar dat is weer iets anders, dat staat los van de first_next_item. Je zou willen dat wanneer GFT al op de "today" sensor staat, dat de "gft" sensor vandaag niet meer meerekend. Dat is volgens mij wat je dan bedoeld.

Dus eigenlijk dat alle "basis" sensoren vandaag niet meerekenen.

**Comment by Mariusthvdb** [comment]
ik denk het wel.....
heb de post in de community gevonden:
https://community.home-assistant.io/t/garbage-pickup-date-mijnafvalwijzer-nl-custom-component/34631/448?u=mariusthvdb


btw, had je dit FR al gezien: https://community.home-assistant.io/t/garbage-pickup-date-mijnafvalwijzer-nl-custom-component/34631/458?u=mariusthvdb
is dat iets mogelijks? dan zal ik een aparte FR maken hier in the Repo?

**Comment by xirixiz** [comment]
Dat is mogelijk idd, maak idd maar een FR aan

**Comment by xirixiz** [comment]
Voor de andere vragen, zowel van Tonieboy als dat van jou zal ik eens induiken.

Jouw verzoek is volgens mij doodeenvoudig om te implementeren, maar het verzoek van Tonieboy vergt meer werk, dan gaat het namelijk niet alleen meer op true/false op vandaag, maar ook op morgen, dus dan heb ik meer dan alleen een boolean nodig.

**Comment by Mariusthvdb** [comment]
als ik tronie lees:

> Sinds woensdag ofzo is de first next item is gelijk aan tomorrow, als je de dag van te voren kijkt. Een paar dagen
> terug was dit daadwerkelijk het eerstvolgende item na morgen?
> 

dan is dat toch gewoon de bedoeling? stel het is morgen ophaaldag, en ik kijk vandaag (de dag van te voren) dan moet de first next item ook gelijk zijn aan tomorrow? dat lijkt toch helemaal correct?

dat wordt dan, als je mijn verzoek mogelijk maakt, helemaal perfect. Want op een ophaaldag vandaag, is de vandaag ophaal niet meer de first-next-item, maar de volgende, en dat is morgen ;-)

**Comment by Toinieboy** [comment]
Wow! Ik heb een hele discussie veroorzaakt ☺️. Hoe kan het dan dat ik met 2x dezelfde code, beiden op de avond voor dat het naar buiten moet dus 2 verschillende resultaten krijg? Das toch ook maf?

**Comment by xirixiz** [comment]
No comments, klopt helemaal 😁👍🏻

**Comment by xirixiz** [comment]
> "dat wordt dan, als je mijn verzoek mogelijk maakt, helemaal perfect. Want op een ophaaldag vandaag, is de vandaag ophaal niet meer de first-next-item, maar de volgende, en dat is morgen ;-)"

Je bedoeld niet first-next-item, want die telt vandaag al niet mee, maar je bedoeld de sensor van het afvaltype zelf. Dus wanneer GFT op de "today" sensor staat, dan wil je dat de GFT sensor alvast de volgende ophaaldatum aangeeft.

**Comment by xirixiz** [comment]
Met de fictieve data:
```
{'kerstbomen': 'Geen', 'gft': '09-10-2020', 'pmd': '16-10-2020', 'papier': '22-10-2020', 'restafval': '25-10-2020'}
{'next_date': '10-10-2020', 'today': 'gft', 'tomorrow': 'pmd', 'next_item': 'pmd', 'day_after_tomorrow': 'Geen', 'next_in_days': 1}
```

Zou je dus dit willen zien:
```
sensor.afvalwijzer_kerstbomen: Geen
**sensor.afvalwijzer_gft: 27-10-2020** (voorbeeld van een mogelijk eerstvolgende GFT pickup)
sensor.afvalwijzer_pmd: 16-10-2020
sensor.afvalwijzer_papier: 22-10-2020
sensor.afvalwijzer_restafval: 25-10-2020

sensor.afvalwijzer_today: gft
sensor.afvalwijzer_tomorrow: Geen
sensor.afvalwijzer_day_after_tomorrow: Geen

sensor.afvalwijzer_next_date: 16-10-2020
sensor.afvalwijzer_next_in_days: 7
sensor.afvalwijzer_next_item: pmd
```

En nu is dat:
```
sensor.afvalwijzer_kerstbomen: Geen
**sensor.afvalwijzer_gft: 09-10-2020**
sensor.afvalwijzer_pmd: 16-10-2020
sensor.afvalwijzer_papier: 22-10-2020
sensor.afvalwijzer_restafval: 25-10-2020

sensor.afvalwijzer_today: gft
sensor.afvalwijzer_tomorrow: Geen
sensor.afvalwijzer_day_after_tomorrow: Geen

sensor.afvalwijzer_next_date: 16-10-2020
sensor.afvalwijzer_next_in_days: 7
sensor.afvalwijzer_next_item: pmd
```

Correct?

**Comment by Mariusthvdb** [comment]
yes! beide posts ;-)

**Comment by Toinieboy** [comment]
> Oh wacht even, nu lees ik het goed.
> 
> first_next_item is altijd het eerstvolgende item geweest inclusief vandaag of exclusief vandaag.
> 
> Dus wanneer er vandaag GFT opgehaald wordt, en morgen PMD en `include_date_today` op false (default) staat, dan is het resultaat:
> 
> ```
> sensor.afvalwijzer_first_next_item: PMD
> ```
> 
> en wanneer `include_date_today` op true staat, dan is het resultaat:
> 
> ```
> sensor.afvalwijzer_first_next_item: GFT
> ```
> 
> Jouw code:
> Het is tijd om 't {{ states('sensor.afvalwijzer_tomorrow') }} buiten te
> zetten. Over {{ states('sensor.afvalwijzer_first_next_in_days') }} dagen mag
> trouwens het {{ states('sensor.afvalwijzer_first_next_item') }} aan de
> straat!
> 
> Kan op deze manier niet gewerkt hebben, dat kan alleen wanneer je het als volgt had:
> Het is tijd om 't {{ states('sensor.afvalwijzer_today') }} buiten te
> zetten. Over {{ states('sensor.afvalwijzer_first_next_in_days') }} dagen mag
> trouwens het {{ states('sensor.afvalwijzer_first_next_item') }} aan de
> straat!
> 
> Omdat ik nooit naar rekening heb gehouden met morgen in de logica van de code. first_next_item na morgen heb ik nooit geimplementeerd, dus alleen first_next_item inclusief of exclusief vandaag.

Toch heeft er bij mij nooit today gestaan. Het screenshot wat je ziet(waar het wel 'werkt' is letterlijk dezelfde code als het screenshot waar het niet werkt) en beiden zijn de avond VOOR today gescreenshot.

**Comment by Toinieboy** [comment]
![Screenshot_20201009_211010_nl addcomm afvalwijzer](https://user-images.githubusercontent.com/66773265/95622574-11707980-0a74-11eb-8e17-96ba0c4fdae6.jpg)

**Comment by Mariusthvdb** [comment]
> Met de fictieve data:
> 
> ```
> {'kerstbomen': 'Geen', 'gft': '09-10-2020', 'pmd': '16-10-2020', 'papier': '22-10-2020', 'restafval': '25-10-2020'}
> {'next_date': '10-10-2020', 'today': 'gft', 'tomorrow': 'pmd', 'next_item': 'pmd', 'day_after_tomorrow': 'Geen', 'next_in_days': 1}
> ```
> 
> Zou je dus dit willen zien:
> 
> ```
> sensor.afvalwijzer_kerstbomen: Geen
> **sensor.afvalwijzer_gft: 27-10-2020** (voorbeeld van een mogelijk eerstvolgende GFT pickup)
> sensor.afvalwijzer_pmd: 16-10-2020
> sensor.afvalwijzer_papier: 22-10-2020
> sensor.afvalwijzer_restafval: 25-10-2020
> 
> sensor.afvalwijzer_today: gft
> sensor.afvalwijzer_tomorrow: Geen
> sensor.afvalwijzer_day_after_tomorrow: Geen
> 
> sensor.afvalwijzer_next_date: 16-10-2020
> sensor.afvalwijzer_next_in_days: 7
> sensor.afvalwijzer_next_item: pmd
> ```
> 
> En nu is dat:
> 
> ```
> sensor.afvalwijzer_kerstbomen: Geen
> **sensor.afvalwijzer_gft: 09-10-2020**
> sensor.afvalwijzer_pmd: 16-10-2020
> sensor.afvalwijzer_papier: 22-10-2020
> sensor.afvalwijzer_restafval: 25-10-2020
> 
> sensor.afvalwijzer_today: gft
> sensor.afvalwijzer_tomorrow: Geen
> sensor.afvalwijzer_day_after_tomorrow: Geen
> 
> sensor.afvalwijzer_next_date: 16-10-2020
> sensor.afvalwijzer_next_in_days: 7
> sensor.afvalwijzer_next_item: pmd
> ```
> 
> Correct?

Hi Bram, 

was this already implemented, (I ask now you've closed the issue here)?

thanks
Marius

**Comment by xirixiz** [comment]
Nope, not yet.... testing it :D

**Comment by xirixiz** [comment]
Yes, volgens mij is het gelukt in deze dev release. Ik heb de API functionaliteit er ook uitgehaald, dus let op dat je het als scraper gebruikt... maar ik verwacht dat het al het geval is. Willen jullie deze release testen?

https://github.com/xirixiz/homeassistant-afvalwijzer/tree/dev_release

**Comment by xirixiz** [comment]
Het is gerelateerd aan de option ```include_date_today```. Maar aangezien die default op false staat zou het resultaat moeten zijn wat jullie wensen zijn 😄

**Comment by Toinieboy** [comment]
> 
> 
> Yes, volgens mij is het gelukt in deze dev release. Ik heb de API functionaliteit er ook uitgehaald, dus let op dat je het als scraper gebruikt... maar ik verwacht dat het al het geval is. Willen jullie deze release testen?
> 
> https://github.com/xirixiz/homeassistant-afvalwijzer/tree/dev_release

Sure thing! Ik laat je het resultaat weten!:)

**Comment by Mariusthvdb** [comment]
voor (release):

<img width="507" alt="Schermafbeelding 2020-10-29 om 09 28 48" src="https://user-images.githubusercontent.com/33354141/97544974-a0651780-19ca-11eb-90a1-a7b367110ab7.png">

na (dev):
<img width="499" alt="Schermafbeelding 2020-10-29 om 09 38 53" src="https://user-images.githubusercontent.com/33354141/97545018-afe46080-19ca-11eb-8bd3-46e88a38a927.png">

saver app:

![20201029_083458000_iOS](https://user-images.githubusercontent.com/33354141/97545353-2aad7b80-19cb-11eb-8376-255c88ed90c8.png)

lijkt identiek.... 
wat vooral ook belangrijk is , is dat een tussenliggende ophaal van dezelfde type wordt overgeslagen.

zal nog een restart doen, om te zien of er niet iets in de cache is blijven hangen

**Comment by Mariusthvdb** [comment]
Yes, beter!
dus toch (moest the oude CC folder weghalen, en niet alleen hernoemen...)
<img width="503" alt="Schermafbeelding 2020-10-29 om 09 54 55" src="https://user-images.githubusercontent.com/33354141/97546579-eae79380-19cc-11eb-9d3b-eb7af2d116dc.png">

alleen is er een foutje in de volgende afhaal ophaal te zien boven in. 
Ah.... ook mooi! `first_next` is nu gewoon `next`, zoals gevraagd ;-)

templates aangepast:

<img width="514" alt="Schermafbeelding 2020-10-29 om 10 00 54" src="https://user-images.githubusercontent.com/33354141/97547226-d5269e00-19cd-11eb-9910-0b1eaf24ff9f.png">

en dan natuurlijk ook de markup in the lovelace card:

<img width="509" alt="Schermafbeelding 2020-10-29 om 10 01 11" src="https://user-images.githubusercontent.com/33354141/97547286-e7a0d780-19cd-11eb-954a-ea2d5f8f4013.png">

kortom: mission accomplished! helemaal perfect.

dank je wel! super.

**Comment by xirixiz** [comment]
Super! Bedankt voor het testen... ik had idd hetzelfde. Maar wanneer het via HACS gaat is het geen issue denk ik.

**Comment by xirixiz** [comment]
Release 5.1.0 available now!

**Comment by Toinieboy** [comment]
> 
> 
> Release 5.1.0 available now!

Hero!

**Comment by Mariusthvdb** [comment]
<img width="491" alt="Schermafbeelding 2020-10-29 om 11 27 52" src="https://user-images.githubusercontent.com/33354141/97556530-eaa1c500-19d9-11eb-936b-bb719a05754e.png">

zag hem al binnenkomen ;-)
