### ISSUE TITLE
HTTP error occurred: 404 Client Error: Not Found for url: https://www.mijnafvalwijzer.nl/error

### ISSUE THREAD

**Issue by iamkarlson** [xirixiz/homeassistant-afvalwijzer#95]
But the reason is that this address is not supported by mijnafvalwijzer:
```
Uw adres is niet bekend bij ons. Neem contact op met uw gemeente
```

Is there anything I can do in order to make it working?

**Comment by xirixiz** [comment]
Ah, too bad. That's most probably because they use another provider to present the data. In which township/city do you live?

**Comment by iamkarlson** [comment]
@xirixiz my city is Zwanenburg. You can try with 1161AE and house number 17. This is not my address but it's quite close.

**Comment by xirixiz** [comment]
https://inzamelkalender.meerlanden.nl/modules/800bf8d7-6dd1-4490-ba9d-b419d6dc8a45/kalender/


Is the provider. Google for meerlanden afvalkalende home assistant and you'll find the proper custom integration 😁👍🏻
