### ISSUE TITLE
Integratie met Afvalinfo

### ISSUE THREAD

**Issue by L4ngeFrank** [xirixiz/homeassistant-afvalwijzer#97]
Ik begrijp het even niet meer, ben al vanalles aan het proberen. Is het nodig om ook de 'Afvalinfo' repository te installeren naast deze? Dit is niet helemaal duidelijk bij de info op je Github pagina. Afvalinfo werkt namelijk perfect, maar krijg het niet voor elkaar om de data van afvalwijzer in HA te zien. En als ik alleen de repo 'afvalwijzer' installeer zie ik onderstaande foto, maar zonder info. 

Of is het alléén beschikbaar voor data van afvalwijzer en afvalstoffendienstkalender?

` - platform: afvalwijzer
    provider: mijnafvalwijzer
    api_token: None
    postal_code: !secret PSC
    street_number: !secret NMB`

![afval](https://user-images.githubusercontent.com/37044307/95661146-42f94b80-0b2d-11eb-89c4-1944f504cae4.png)

**Comment by xirixiz** [comment]
Dit is een standalone component en is dus onafhankelijk van afvalinfo. Ik heb een deel van de code mogen gebruiken nadat er een beperking is opgelegd door de provider (geen api toegang). Volgens mij is de info harstikke duidelijk dat ik een deel van de code heb mogen kopieren, maar dat terzijde.

Het betreft verder een component dat werkt voor mijnafvalwijzer en afvalstoffendienstkalender. Op de onderstaande manier zou het moeten werken. api_token moet je weglaten wanneer je het niet nodig hebt, daarop gaat het nu mis. Het request wordt nu gemaakt met een api token met de waarde None, en dat werkt niet.

```
- platform: afvalwijzer
  provider: mijnafvalwijzer
  postal_code: !secret PSC 
  street_number: !secret NMB
```

Mocht dat niet werken dan je kan je zoals is te lezen in de README ook debug logging aanzetten:
```
logger:
  default: info
  logs:
    custom_components.afvalwijzer: debug
```

Overigens werkt afvalinfo ook goed, alleen dat is net anders opgezet en bevat net wat minder sensoren.

**Comment by L4ngeFrank** [comment]
Thanks voor je heldere antwoord. Voor mij kwam het echt over alsof jou mooie addon een skin was over die van afvalinfo, maar dat terzijde  ;)

Als ik het goed begrijp maken sommige gemeenten dus geen gebruik van de pagina's; mijnafvalwijzer en afvalstoffendienstkalender, heeft het voor mensen die in zo'n gemeente wonen dus geen meerwaarde aangezien deze data niet kan worden uitgelezen. Mijn gemeente werkt via: http://www.deafvalapp.nl/.
Hopelijk kunnen jullie elkaars codes vergelijken/gebruiken zodat beide diensten in de toekomst dezelfde sensoren bevatten. 

Keep up the good work!

**Comment by xirixiz** [comment]
Klopt, mijnafvalwijzer en afvalstoffendienstkalender zijn slechts 2 aanbieders. Het dekt overigens een vrij groot gebied en het onderhoud daarvan vergt helaas behoorlijk wat tijd, uitbreiding daarvan zie ik voorlopig niet zitten eerlijk gezegd. Overigens gebruiken afvalinfo en dit component dezelfde sensoren, alleen heb ik een andere visie op de inrichting daarvan. 

Je kan het eigenlijk vergelijken met applicaties. Er zijn bijvoorbeeld tig mailclients beschikbaar en men kiest diegene die het beste aansluit op de wensen.
